### ISSUE TITLE
Routing path and url configuration

### ISSUE THREAD

**Issue by techkoka** [spring-cloud/spring-cloud-netflix#1009]
I have the below configuration in my yaml file
```
zuul:
  host:
  routes:
    abc:
      path: /app/service/users/
      url: http://10.20.21.11:1010/v1/customers/logins
      stripPrefix: false
```
I'm not using eureka nor ribbon (Just Spring Zuul)

When I trigger a request to zuul, instead of sending the url http://10.20.21.11:1010/v1/customers/logins, it  appends path in to url  http://10.20.21.11:1010/v1/customers/logins/app/service/users/  

Looked around, couldn't find a valid solution or configuration that could resolve the proble,
