### ISSUE TITLE
Not possible to clear sensitive-headers list in ZuulRoute

### ISSUE THREAD

**Issue by Koizumi85** [spring-cloud/spring-cloud-netflix#1012]
Hello,

at the moment it is no longer possible to clean the sensitive-headers list in a specific ZuulRoute. Instead the default sensitive-headers from ZuulProperties are always applied if you try to clean the list like the following:

```
zuul:
  routes:
    user-service: 
      service-id: user-service
      path: '/user-service/**'
      sensitive-headers:
```

It seems, that it is caused by the following commit:

https://github.com/spring-cloud/spring-cloud-netflix/commit/ea1a4c5add949d16117fffeb5fa3ef5385d4bac8
