### ISSUE TITLE
Zuul integration with hystrix for static routes

### ISSUE THREAD

**Issue by todzheng** [spring-cloud/spring-cloud-netflix#1048]
My Zuul routes are defined as static routes with urls (Eureka is not used), is it possible to enable hystrix/circuit breaker for calls to other services?

**Comment by aivans** [comment]
yes, you need to configure a indirection: a "virtual" service + Ribbon Client
http://cloud.spring.io/spring-cloud-static/spring-cloud.html#spring-cloud-ribbon-without-eureka

**Comment by aivans** [comment]
Let me give you an example:
```
zuul:
  routes:
    echo:
      path: /echo/**
      serviceId: echo-service
      stripPrefix: true

hystrix:
  command:
    echo-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: ...

echo-service:
  ribbon:
    listOfServers: http://yourserviceurl1,http://yourserviceurl1
    ConnectTimeout: 1000
    ReadTimeout: 3000
    MaxTotalHttpConnections: 500
    MaxConnectionsPerHost: 100  
```
