### ISSUE TITLE
Zuul Routes with serviceId + path

### ISSUE THREAD

**Issue by huhuhong** [spring-cloud/spring-cloud-netflix#1069]
I'm using Zuul + Eureka with 2  micro-services register as Eureka client:
customer-service: v2/plans
pricing-service: v2/plans

I want to have different url path for both of them in Zuul routes

```
zuul:
    ignoredServices: "*"
    routes:
        customer-services:
          path: /v2/billing-plans/**
          serviceId: customer-service/plans
          stripPrefix: false
        pricing-services:
          path: /v2/pricing-plans/**
          serviceId: pricing-service/plans
          stripPrefix: false
```

Is this possible?

**Comment by ouaibsky** [comment]
Hi

sure it's possible, we use it like that every days.
You can also have many routes (with different path) on same serviceId (in this case I guess the first that is matching win)
Christophe

**Comment by huhuhong** [comment]
So you mean serviceid can combine with it own url? Let me try
just to clarify again, both [customer-service] and [pricing-service] is the eureka id.

**Comment by huhuhong** [comment]
Anyone have any thought?!

**Comment by ouaibsky** [comment]
We ust it like that:
```yaml

    requests:
      serviceId: onyx-request
      path: /api/requests/**
      stripPrefix: false

    route1:
      serviceId: id1
      path: /api/foo/**
      stripPrefix: false

    route2:
      serviceId: id1
      path: /api/bar/**
      stripPrefix: false

    route3:
      serviceId: id2
      path: /api/foobar/**
      stripPrefix: false
```

**Comment by huhuhong** [comment]
With your sample routes, id1 must always contain /api/bar or /api/foo
what if i want to expose different path name to public, example api/barcounter and it actually map /api/bar of id1.

```
route1:
      serviceId: id1/bar  -- map to id1
      path: /api/barcounter/** -- this exposed to public
      stripPrefix: false

```

**Comment by patrickse** [comment]
Facing the same problem. Trying to create a frontend for an old service that uses a different ressource layout...

```
EdgeService (*new*)
http://<zuul>/api/service_a/people

Service_A (*old*)
http://<service_a>/api/v1/service_a/people
```

So I want to map the ressource `people` of Service_A to ressource `people` on the edge. It´s no problem to achive what I want with using the url feature of zuul. But I am struggeling to get it to work with serviceId.

```yaml
zuul:
  ignored-services: "*"
  routes:
    service_a:
      path: /service_a/**
      url: http://localhost:9005/api/v1/service_a/
```

But I want to use service discovery... Any idea?
