### ISSUE TITLE
Add a whitelist for networkInterfaces and/or a network to choose the IP from to bind the service to

### ISSUE THREAD

**Issue by mrumpf** [spring-cloud/spring-cloud-netflix#1082]
Currently there is only a blacklisting of network interfaces possible: #788 
During our staging through different environments we noticed an issue that the microservice bound itself to the wrong network interface and IP addres.
Unfortunately there is no simple pattern which can be configured via the Spring Cloud property:
```
spring:
  cloud:
    inetutils:
      ignoredInterfaces:
        - tun.*
```

We have one public network IP and several network interfaces for administrative access.
* eth3 - public
* eth4 - admin
* eth5 - admin

On another machine it is like this:
* eth4 - public
* eth3 - admin
* eth5 - admin

Our current workaround is is to use the parameter from above on the first environment
```
spring:
  cloud:
    inetutils:
      ignoredInterfaces:
        - eth[^3]
```
and 
```
spring:
  cloud:
    inetutils:
      ignoredInterfaces:
        - eth[^4]
```
on the other environment.

A more stable approach would be to have a whitelist like this:
```
spring:
  cloud:
    inetutils:
      preferredInterfaces:
        - eth3
```
Or even better to be able to select an interface from the network it is assigned to:
```
spring:
  cloud:
    inetutils:
      preferredNetworks:
        - 192.168.5.0/24
```
The latter would survive creating a new network interface on the VMWare server, as long as the IP network is not changed.
