### ISSUE TITLE
Unable to use Turbine with Sidecar

### ISSUE THREAD

**Issue by tkvangorder** [spring-cloud/spring-cloud-netflix#1122]
I am trying to use Turbine to aggregate the various hystrix streams published when using spring-cloud-sidecar.

The sidecar is a companion to a node.js application and the configuration looks as follows: 

```
server:
  port: 8082

sidecar:
  port: 3000

```

The problem appears to be that turbine is attempting to use the port published with Eureka, which in this case is 3000, but the hystrix stream is actually being published on 8082.

Is there a way to tell Turbine to use the correct port?

**Comment by tkvangorder** [comment]
To answer my own question: 

In the turbine configuration, I had to add the following: 

```yaml
turbine:
  instanceInsertPort: false
  instanceUrlSuffix: ':8082/hystrix.stream'
```
