### ISSUE TITLE
Could not resolve placeholder 'spring.application.instance_id' when deploying to CF

### ISSUE THREAD

**Issue by kmarabet** [spring-cloud/spring-cloud-netflix#1214]
When deploying microservice (with spring-actuator) to CloudFoundry with @EnableDiscoveryClient with the following configuration in application.yml:
```
spring:
  profiles: cloud
eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id}
```
Getting the following error:

`Could not resolve placeholder 'spring.application.instance_id' in string value "${spring.application.name}:${spring.application.instance_id}"...
`
Which means that the spring.application.instance_id is not populated for some reasons by CF.

Any idea why this could happen?
