### ISSUE TITLE
@EnableDiscoveryClient does not register with Eureka in 1.1.5.RELEASE

### ISSUE THREAD

**Issue by hetzijzo** [spring-cloud/spring-cloud-netflix#1227]
In version **1.1.5.RELEASE** having a `@EnableDiscoveryClient` annotated application, will not lead to registering in Eureka. Exactly the same configuration in **1.1.4.RELEASE** (default of **BRIXTON.SR3**) does register the Client with Eureka.

- spring-cloud-netflix:1.1.4.RELEASE :white_check_mark: 
- spring-cloud-netflix:1.1.5.RELEASE :x:

My setup:

```groovy
//build.gradle
buildscript {
    ext {
        javaVersion = 1.8
        springBootVersion = '1.4.0.RELEASE'
        springCloudVersion = 'Brixton.SR3'
    }
    ext['spring-cloud-netflix.version'] = '1.1.5.RELEASE'

    repositories {
        jcenter()
    }
    dependencies {
        classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
    }
}

apply plugin: 'java'
apply plugin: 'application'
apply plugin: 'spring-boot'

dependencies {
    compile('org.springframework.boot:spring-boot-starter-actuator')
    compile('org.springframework.boot:spring-boot-starter-data-jpa')
    compile('org.springframework.boot:spring-boot-starter-web')
    compile('org.springframework.cloud:spring-cloud-starter-eureka')
    compile('org.springframework.cloud:spring-cloud-starter-feign')
    compile('org.projectlombok:lombok:1.16.10')

    runtime('com.h2database:h2')
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
    }
}

task wrapper(type: Wrapper) {
    gradleVersion = '2.14'
}
```

```java
@SpringBootApplication
@EnableDiscoveryClient
@EnableFeignClients
public class Application {
    public static void main(String[] args) {
        SpringApplication.run(Application .class, args);
    }
}
```

```yml
#bootstrap.yml
spring:
  application:
    name: my-application
```

```yml
#application.yml
server:
  port: ${PORT:8080}
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
```
