### ISSUE TITLE
[ Question / Feature Request] Complex Prefixes

### ISSUE THREAD

**Issue by matanshukry** [spring-cloud/spring-cloud-netflix#1235]
I would like to have 2 "groups" of routes in my configuration:

(1), a group that starts with /api, which will be stripped.
e.g.
- request to /api/users/*\* -->http://user-service/users/**
- request to /api/images/*\* --> http://image-service/images/**

(2) A group that starts with /web, which will be stripped
- request to /web/login/*\* --> http://web-service/login

It seems each one of those options is possible by it's own, using a global prefix (either "/api" or "/web"), and strip-prefix (set to false) at the service level. However, how can I achieve them both in the same zuul?

If it's not possible, what you guys think about this as a feature?

**Comment by spencergibb** [comment]
There are many routing requests about, such as #435. You can always write your own `pre` filter to do this. Maybe at that point you could contribute it back.

**Comment by kakawait** [comment]
@spencergibb the fact that routing requests become more and more present, we can think about proposing a programmatic interface to write your custom routing rules? Something less generic than `ZuulFilter`

**Comment by spencergibb** [comment]
@kakawait we're open to suggestions.

**Comment by kakawait** [comment]
@spencergibb I'm working on it (solution not suggestions)

**Comment by matanshukry** [comment]
@kakawait - can you share you're solution (idea), so I'll know if it should work for me as well?

**Comment by kakawait** [comment]
@matanshukry you could try that filter https://gist.github.com/kakawait/31ee67170cf22652fe0a51ed3415e4c2

**ATTENTION** is just a POC and it will break any `zuul.routes.<serviceId>.url=` that not using `serviceId` as hostname

In your case try following configuration

```
zuul:
  routes:
    user-service:
      path: /api/users/**
      url: http://user-service/users
      strip-prefix: true
    image-service:
      path: /api/images/**
      url: http://image-service/images
      strip-prefix: true
    web-service
      path: /web/login/**
      url: http://web-service/login
      strip-prefix: true
```

If any issue please continue discussion on gist
