### ISSUE TITLE
Zuul routes not working with serviceId but working with URL Part 2

### ISSUE THREAD

**Issue by asandez** [spring-cloud/spring-cloud-netflix#1299]
Hi, 
     I'm developing a Micro services application with Zuul , Config Server and Eurika, consuming Rest services from another server.
When I use Zuul with  **url:** the services are route correctly, but when I use Eurika and serviceID, zuul raise exceptions.
The services **Aviones** is listed on Eureka and Zuul is also listed in Eurika, for that reason I consider that Zuul has connection with Eurika.
Using Postman application, I send the request hit and correctly the Rest service **Aviones**, the problem is in the way back inside of Zuul. 

**With this configuration Zuul works** 
```
--- 
ribbon: 
  ConnectTimeout: 30000
  ReadTimeout: 990000
  maxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  eureka:
    enabled: false
server: 
  port: 8080
zuul: 
  ignoredServices: '*'
  routes:
    aviones:
      path: /aviones/**
      url: "http://localhost:8686/"
      stripPrefix: false
    autos:
      path: /autos/**
      url: "http://localhost:8777/"`
```
**With this configuration Zuul doesn´t work** 
```
--- 
ribbon: 
  ConnectTimeout: 30000
  ReadTimeout: 990000
  maxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  eureka:
    enabled: true
server: 
  port: 8080
zuul: 
  ignoredServices: '*'
  routes:
    aviones:
      path: /aviones/**
      serviceId: aviones
      stripPrefix: false
    autos:
      path: /autos/**
      serviceId: autos
      stripPrefix: false
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 20000
```
