### ISSUE TITLE
A property on Zuul Route to define a server context would be useful

### ISSUE THREAD

**Issue by wgorder** [spring-cloud/spring-cloud-netflix#130]
I think it would be useful to have a server context on a Zuul route.  Say I want to route /auth-server/login to the auth-server service registered in Eureka.  But if the auth-server has a context of 'uaa' a bit more extra configuration needs to be done.  I know there are ways currently I can make that work but I think a simple option for the route to just know that the forward needs to include the context would be useful.

**Comment by wgorder** [comment]
Actually its not so bad to just do this:

```

zuul:
  routes:
    auth-server:
      path: /uaa/**
      stripPrefix: true

```

I think that will work, but my brain had quite working there for a minute.
