### ISSUE TITLE
Allow Zuul route url to be file:// 

### ISSUE THREAD

**Issue by bplies-IAS** [spring-cloud/spring-cloud-netflix#1307]
Feature request

ZuulProperties.ZuulRoute.setLocation() allows for http:// and https://, but would be great if we could support file:// in cases where UI-only applications are on the same host as Zuul (as opposed to a CDN).  So we can avoid all the http & routing overhead and need not worry about also running an http service just to serve those same files.  Might as well let Zuul do it since it is already serving the request.  This scenario is more common when running all microservices as Spring Boot JARs and no hosts bother to install any kind of general http service.

**Comment by spencergibb** [comment]
I don't think I would want to do that. We support forwarding to the local spring boot app via the `forward:` prefix. Since boot supports serving static files, I'd let it do its job.

**Comment by bplies-IAS** [comment]
Static content is not inside of Spring Boot is what I'm saying.  It isn't wrapped in Java at all.  Like an exploded tar.gz of html, fonts, css, js, images.

**Comment by spencergibb** [comment]
I don't want to reinvent something that boot already does. You could write your own filter to do whatever you need.

**Comment by bplies-IAS** [comment]
We aren't talking about static resources within a Spring Boot app.  We aren't discussing alternative ways to accomplish this with Filters.  We're describing declaring route urls in Zuul configuration properties with a url scheme that isn't http or https.  

Why shouldn't we define a file:// route url in the same way as other route urls?

```
zuul:
  routes:
    demo-hello-service:
      path: /api/hello/**
      url: http://localhost:9090/
    user-service:
      path: /api/user/**
      url: http://localhost:9999/user
    user-ui:
      path: /ui/**
      url: file://var/www/ui/
```
