### ISSUE TITLE
Document working with multiple zones in eureka

### ISSUE THREAD

**Issue by liangchouzhou** [spring-cloud/spring-cloud-netflix#1327]
i google and read the doc and can't find some detailed description or example for config eureka server & client in multiple zones.

in cloud env, there are 2 zones in 1 region. i want to deploy eureka server1 in zone1, eureka server2 in zone2. 

Service deployed in zone1, registered in eureka server1.
service deployed in zone2, registered in eureka server2.

for request route to zone1, prefer to route to service in zone1; and route to service in zone2 in case of service in zone1 is down
for request route to zone2, prefer to route to service in zone2; and route to service in zone1 in case of service in zone2 is down.

how to config the eureka server and client? Thanks.

**Comment by ryanjbaxter** [comment]
Having the services register with the correct Eureka Server for their zone is just a matter of setting the URL to the Eureka server in `eureka.client.serviceUrl.defaultZone`.

To enable the case where a request to route to a service in another zone when the service in its zone is unavailable you need to make sure the Eureka servers in all zones are set up as peers of each other.  More information on that can be found in #1251.

To specify zone information you have two options.
1.  If the hostnames of the services will be different in each zone you can set `ribbon.eureka.approximateZoneFromHostname` to `true` and zone information for a service will be calculated based on the host name.  (assuming you are using ribbon)
2.  You can specify the zone for a service by setting `eureka.instance.metadataMap.zone`.

**Comment by liangchouzhou** [comment]
@ryanjbaxter 
my eureka server and client config as below, eureka server 1 and server 2 replicated each other. eureka client in service or api-gateway (zuul), register for server 1 and server2.

**eureka server1 config**
```
eureka:
  instance:
    hostname: 10.8.0.1
  client:
    serviceUrl:
      defaultZone: http://10.8.0.2:8761/eureka/
  server:
    enable-self-preservation: false
```

**eureka server2 config**
eureka:
```
  instance:
    hostname: 10.8.0.2
  client:
    serviceUrl:
      defaultZone: http://10.8.0.1:8761/eureka/
  server:
    enable-self-preservation: false
```

**eureka client config  (zone1 service)**
```
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.8.0.1:8761/eureka/, http://10.8.0.2:8761/eureka/
  instance:
    preferIpAddress: false
```

**eureka client config (zone1 api gateway: zuul)**
```
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.8.0.1:8761/eureka/, http://10.8.0.2:8761/eureka/
  instance:
    preferIpAddress: false
```


how to config eureka server1 to zone1 and eureka server 2 to zone2?

at zuul, i config 2 URLs in serviceUrl.defaultZone, the 1st one is zone1 eureka server, the 2nd one is zone2 eureka server. if this config is enough when zone1 service is unavailable, the request is routed to zone2 service?

at zuul / service, how to config to route the request to service the same zone?

**2. You can specify the zone for a service by setting eureka.instance.metadataMap.zone.**
this way?
**eureka client config  (zone1 service)**
```
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.8.0.1:8761/eureka/, http://10.8.0.2:8761/eureka/
  instance:
    preferIpAddress: false
    metadataMap:
       zone: zone1
```

btw, how to config region info for eureka and config 2 zones under this region?

Thanks.

**Comment by ryanjbaxter** [comment]
It looks like your Eureka server configuration is not correct.  You should configure them as follows.

**eureka server1 config**
```
eureka:
  instance:
    hostname: 10.8.0.1
  client:
    serviceUrl:
      defaultZone: http://10.8.0.2:8761/eureka/,http://10.8.0.1:8761/eureka/
  server:
    enable-self-preservation: false
```
**eureka server2 config**
```
eureka:

  instance:
    hostname: 10.8.0.2
  client:
    serviceUrl:
      defaultZone: http://10.8.0.1:8761/eureka/,http://10.8.0.2:8761/eureka/
  server:
    enable-self-preservation: false
```

In your Eureka Clients you should set `defaultZone` to the URL of the Eureka server in the same zone.  So for example if Eureka server 1 is in zone 1 and Eureka server 2 is in zone 2, your client deployed to zone 1 would look like

```
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.8.0.1:8761/eureka/
  instance:
    preferIpAddress: false
    metadataMap:
       zone: zone1
```

And you client deployed to zone 2 would look like

```
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.8.0.2:8761/eureka/
  instance:
    preferIpAddress: false
    metadataMap:
       zone: zone2
```

Since the two Eureka servers are set to be peers of each other they will replicate service information with each other.

On the clients when a request is made to a service we will use the zone information obtained from Eureka about the various services to determine which service to try first.

**Comment by liangchouzhou** [comment]
thanks, @ryanjbaxter 

i try the following config and it works:

eureka server config is just as above and the eureka client config in service is below:

### service1 in zone1
```
eureka:
  instance:
    preferIpAddress: false
    metadataMap:
      zone: zone1
  client:
    serviceUrl:
      defaultZone: http://10.8.0.1:8761/eureka/, http://10.8.0.2:8761/eureka/
    preferSameZoneEureka: true
```

### zuul1 in zone1

```
eureka:
  instance:
    preferIpAddress: false
    metadataMap:
      zone: zone1
  client:
    serviceUrl:
      defaultZone: http://10.8.0.1:8761/eureka/, http://10.8.0.2:8761/eureka/
    preferSameZoneEureka: true
```

then zuul1 will route request to services in zone1 first and if services in zone1 is down, will route request to services in zone2.
