### ISSUE TITLE
Are there any examples of using Feign with Eureka?

### ISSUE THREAD

**Issue by mingfang** [spring-cloud/spring-cloud-netflix#133]
The documentations has examples of using Fiegn without Eureka, but I'm unable to get Feign working with Eureka and can't find any examples or documentation on it.

**Comment by mingfang** [comment]
I figured it out.
If you have @FeignClient("helloservice") then your application.yml needs this
```
helloservice:
  ribbon:
    DeploymentContextBasedVipAddresses: helloservice
    NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
```
