### ISSUE TITLE
EurekaClient without Registration

### ISSUE THREAD

**Issue by gondor** [spring-cloud/spring-cloud-netflix#1347]
One of the most common problems we've had in my organization in development is having to bring up a local Eureka and any related services.   

I've tried creating a configuration so engineers can turn on a discovery profile in development and it will use the remote Spring Cloud Netflix Eureka server as a lookup and no registration.

I don't want local dev instances registering as a source in the registry but want the ability they can use existing services in CI.

Is this possible?  Here's the config below I've been trying and I end up getting the following error:

```
2016-09-15 15:39:27,546 [PollingServerListUpdater-0] WARN  c.n.n.l.DiscoveryEnabledNIWSServerList "cid":""  - EurekaClient has not been initialized yet, returning an empty list
```

Config Profile:
```
---
spring:
  profiles: discovery

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
          defaultZone: http://remotehost:8761/eureka/
```
