### ISSUE TITLE
zuul.stripPrefix=false  not work for all route?

### ISSUE THREAD

**Issue by Dreampie** [spring-cloud/spring-cloud-netflix#1365]
//work fine
```
zuul:
  routes:
    user-api-provider:
      path: /usr/**
      stripPrefix: false
    common-api-provider:
      path: /cmn/**
      stripPrefix: false
    log-api-provider:
      path: /log/**
      stripPrefix: false
    ddcms-api-provider:
      path: /ddcms/**
      stripPrefix: false
    area-api-provider:
      path: /are/**
      stripPrefix: false
    limit-api-provider:
      path: /lmt/**
      stripPrefix: false
```

//not work
```
zuul:
  stripPrefix: false
  routes:
    user-api-provider: /usr/**
    area-api-provider: /are/**
    limit-api-provider: /lmt/**
    log-api-provider: /log/**
    common-api-provider: /cmn/**
    ddcms-api-provider: /ddcms/**
```
