### ISSUE TITLE
Enable basic auth for eureka server.

### ISSUE THREAD

**Issue by Mavlarn** [spring-cloud/spring-cloud-netflix#1408]
As mentioned in doc, I can just enable basic security by adding this in eureka server application properties:
```
eureka:   
    client:   
        serviceUrl:   
            defaultZone: http://myuser:mypassword123@localhost:${server.port}/eureka
```
But it can not work. I also tried to add this in eureka server application properties:
```
security:
  basic:
    enabled: true
```
How can I use basic authentication for eureka server?
Thanks.
