### ISSUE TITLE
Zuul seems not to be peer aware

### ISSUE THREAD

**Issue by dschroe** [spring-cloud/spring-cloud-netflix#1418]
If zuul connects to a **standalone** eureka server like in the following configuration, then the forwarding to my microservice works fine.

```
server:
  port: 8900
eureka:
  client:
    service-url:
      defaultZone: http://eureka:admin@localhost:8761/eureka
```

But when zuul connects to a eureka server **cluster** like in the following configuration

```
server:
  port: 8900
eureka:
  client:
    service-url:
      defaultZone:   
         http://eureka:admin@localhost:8761/eureka,http://eureka:admin@localhost:8762/eureka
```

then i get the following **error**
![error](https://cloud.githubusercontent.com/assets/9927627/19621406/7629b642-9891-11e6-821a-35f4b9d40763.PNG)

Am i missing something in the zuul configuration to work with a cluster?
