### ISSUE TITLE
X-Forwarded-Prefix not applied for '/**' path mapping

### ISSUE THREAD

**Issue by sirianni** [spring-cloud/spring-cloud-netflix#1445]
With this setup:
```yaml
zuul:
  routes:
    users:
      path: /myusers/**
      url: http://mycompany.com/newapp
    legacy:
      path: /**
      url: http://mycompany.com/legacy
```
I would expect forwarded request to `legacy` to have the header `X-Forwarded-Prefix: /`.  This is required for HTTP redirects originating from the `legacy` app to avoid exposing the `legacy` context path (using `ForwardedHeaderFilter`).

However, this code in `SimpleRouteLocator` avoids setting a route prefix of `/`
```java
int index = route.getPath().indexOf("*") - 1;
if (index > 0) {
	String routePrefix = route.getPath().substring(0, index);
	targetPath = targetPath.replaceFirst(routePrefix, "");
	prefix = prefix + routePrefix;
}
```

This has the undesirable side effect of redirects generated from my legacy app exposing the `/legacy` context path.  If I instead deploy my gateway app at a context path other than `ROOT`, the `X-Forwarded-Prefix` is set.

These semantics are a bit odd.  I would expect `X-Forwarded-Prefix` to be set regardless of at which Context path I choose to deploy the Zuul app.

Is there a specific case why the code is avoiding setting the prefix by the `if (index > 0) {` check?

**Comment by spencergibb** [comment]
How does that code affect if `X-Forwarded-Prefix` is set? If a route has a location (somewhere to go) and `zuul.addProxyHeaders` is true, headers are added.

**Comment by sirianni** [comment]
route.getPrefix() is `""` instead of `/`. `PreDecorationFilter` then does not add the `X-Forwarded-Prefix` header to the forwarded request.

With the above configuration here is what I observe.
### App deployed at `ROOT` context path
Expected: `X-Forwarded-Prefix: /`
Actual: `X-Forwarded-Prefix` not present

### App deployed at `foo` context path
Expected: `X-Forwarded-Prefix: /foo`
Actual: `X-Forwarded-Prefix: /foo`

**Comment by spencergibb** [comment]
`PreDecorationFilter` doesn't check `route.getPrefix()` that I see, but `route.getLocation()`.

**Comment by spencergibb** [comment]
sorry, I've been looking at the wrong header

**Comment by spencergibb** [comment]
The prefix is something that we potentially strip, we don't strip `/`

**Comment by spencergibb** [comment]
You can use a custom filter that runs after `PreDecorationFilter` as a workaround.

**Comment by sirianni** [comment]
My current workaround is:
```java
@Component
class CustomRouteLocator extends SimpleRouteLocator {

    @Inject
    CustomRouteLocator(ServerProperties serverProperties, ZuulProperties zuulProperties) {
        super(serverProperties.getServletPrefix(), zuulProperties);
    }

    @Override
    public Route getMatchingRoute(String path) {
        return adjustPrefix(super.getMatchingRoute(path));
    }

    @Override
    public List<Route> getRoutes() {
        return super.getRoutes()
            .stream()
            .map(this::adjustPrefix)
            .collect(Collectors.toList());
    }

    private Route adjustPrefix(Route route) {
        if (route == null) {
            return null;
        }
        if (StringUtils.isEmpty(route.getPrefix())) {
            route.setPrefix("/");
        }
        return route;
    }

}
```

**Comment by spencergibb** [comment]
Have you tried setting the prefix in config?
```
zuul:
  routes:
    users:
      path: /myusers/**
      url: http://mycompany.com/newapp
    legacy:
      path: /**
      url: http://mycompany.com/legacy
      prefix: /
      strip-prefix: false
```
