### ISSUE TITLE
Ribbon + Zuul + Eureka & Feign do not appear to honor ribbon configuration parameters

### ISSUE THREAD

**Issue by jzampieron** [spring-cloud/spring-cloud-netflix#1446]
Spring Boot 1.4.1.RELEASE with Camden.SR1:

I have an application.yml file with the following in it:
```
ribbon:
  CustomSSLSocketFactoryClassName: com.netflix.http4.ssl.AcceptAllSocketFactory
  IsHostnameValidationRequired: false
  IsSecure: true
  MaxAutoRetries: 5
  OkToRetryOnAllOperations: true
  MaxRetriesPerServerPrimeConnection: 3
  GZipPayload: true
  EnableGZIPContentEncodingFilter: true
  # service discovery.
  eureka:
    enabled: true
```
None of these parameters were reflected in the IClientConfigs generated by 
`org.springframework.cloud.netflix.ribbon.RibbonClientConfiguration.class:ribbonClientConfig()`

Either the code isn't picking up the "outer" ribbon namespace as the defaults for all Eureka discovered Feign clients or the documentation isn't clear that this is expected behavior (this should be a large warning box, as its not intuitive).

It seems like only select parameters are honored from that set.
