### ISSUE TITLE
 Zuul, Spring MVC and trailing slash

### ISSUE THREAD

**Issue by marvindaviddiaz** [spring-cloud/spring-cloud-netflix#1475]
I have the same error as the incident  #919 (Closed by inactivity)
```
zuul:
    routes:
      security-view-angular: 
        path: /security-view-angular/**
        service-id: security-view-angular
        strip-prefix: false
```

When I go to: http://localhost:8080/security-view-angular/, everything is ok.
But, when I go to: http://localhost:8080/security-view-angular (without last slash) zuul redirect me to http://172.16.5.79:9080/security-view-angular/
