### ISSUE TITLE
Zuul rewrite url and load balance with Ribbon

### ISSUE THREAD

**Issue by nmnellis** [spring-cloud/spring-cloud-netflix#1488]
I have a backend url that i need to route to that does not conform to our client specifications. I would like to proxy the client url /service1/endpoint1 to backend /service2/endpoint2 and then use ribbon to load balance between a list of servers. Does anyone know how i can achieve this? Is this something that can be done in a filter before the RibbonRoutingFilter picks up the request?

My example so far
```yaml
zuul:
  routes:
    service1:
      path: /service1/endpoint1
service1:
  ribbon:
    listOfServers: http://www.servera.com/,http://www.serverb.com/
ribbon:
  eureka:
    enabled: false
```

**Comment by nmnellis** [comment]
I have tried adding a prefix to strip the incoming request and add the backend url to the end of the list of servers as before but it looks like Ribbon only stores the host name.

```yaml
zuul:
  prefix: /service1/endpoint1
  routes:
    service1:
      path: /**
service1:
  ribbon:
    listOfServers: http://www.servera.com/service2/endpoint2, http://www.serverb.com/service2/endpoint
```

**Comment by nmnellis** [comment]
I found a working solution but it required extending the RibbonRoutingFilter and changing the uri in the buildCommandContext method.
I also had to disable the default routing filter
```yaml
zuul:
  RibbonRoutingFilter:
    route:
      disable: true
```
