### ISSUE TITLE
Zuul returning 200 OK for any request which does not route to service and log 500 in the zuul server

### ISSUE THREAD

**Issue by smitkumar** [spring-cloud/spring-cloud-netflix#1532]
Zuul Spring boot application is sometime return 200 Status code while in server it log with status code 500 internal server error. Looks like it is not routing to the service given in the route url,

my yml configuration:
```
zuul:
  routes: 
    service_1: 
      path: /myorder/**
      service-id: test
      url: "http://localhost:9999/process"
```
when i place order to zuul on http://localhost:8080/myorder it return 200 ok but in the zuul server it is loging 500 status code without message body. request is not reaching to server http://localhost:9999/process .

is there any issue with zuul framework where it return 200 for status code 500 without any message body.
