### ISSUE TITLE
Question: Is there a Zuul route addPrefix that works opposite to stripPrefix

### ISSUE THREAD

**Issue by madheshr** [spring-cloud/spring-cloud-netflix#1557]
Hi
  The stripPrefix option in Zuul route configuration works great to route requests to microservices by either stripping or retaining the prefix (based on stripPrefix being true or false).  We have an opposite situation and was wondering if there is a way to add a fixed Prefix (corresponding to the context path of the microservice) to each route

We have a microservice that we need to move to another tomcat with a seperate contextpath (myweb)
.  
Microservice configuration
```
server:
    port: 8096
    context-path: /myweb
```

The Gateway has below configuration
```
zuul:
  routes:
    hello:
       path: /Hello/**
       serviceId: hello
       stripPrefix: false
       sensitiveHeaders: Cookie,Set-Cookie,Authorization 
ribbon:
  eureka:
    enabled: false
  restclient:
    enabled: false
hello:
  ribbon:
    listOfServers: <new-host>:8096
```

We have other consumers for the Microservice who used access the service like
http://<host>/Hello/greet

Now that the greet endpoint has moved to a new location with a seperate context path.. The service can be internally accessed like this
http://<new-host>:8096/myweb/Hello/great

The question is how to route requests to the Gateway (http://<gateway>/Hello/greet  
to hit the new service endpoint http://<new-host>:8096/myweb/Hello/great

We need to add a fixed contextPath  (in this case /myweb) on all incoming requests to /Hello/*.
The route path cannot be changed from /Hello/**   (this is used by external clients and we cannot ask them to move to something like /myweb/Hello/**).  Is there a work around to achieve this?  

I tried adding the fixed context path in a route filter, but this is causing it to miss the route match itself.  Any suggestion?

**Comment by kakawait** [comment]
You can't do with built-in configuration. What can I suggest you is:

1. Use `zuul.routes.<serviceId>.url` like following 

```yml
zuul:
  routes:
    hello:
       path: /Hello/**
       url: http://<new-host>:8096/myweb/Hello/
       strip-prefix: true
```

2. Create your own `Zuul` filter to manage that case

**However** both solutions have major drawback, for **1.** you can't use anymore client load balancing `Ribbon` and for **2.** you can't configure that route inside `yml`.

I had similar issue so I personally mixed the goods from both solutions to get *my* ultimate solution:

[DiscoveryHostUrlFilter.java](https://gist.github.com/kakawait/546955e79f902913ae61b63325cb0545) Zuul filter

Please read related javadoc for more information, but to be short you can now describe your route like:

```yml
zuul:
  routes:
    hello:
       path: /Hello/**
       url: http://hello/myweb/Hello/#discovery
       strip-prefix: true
```

**ATTENTION** two important thing:

1. `http://hello/...` here `hello` is `<serviceId>` and any load balancing (and circuit-breaking) features will work with that url. Is exactly the same philosophy than `@LoadBalanced RestTemplate` url syntax.
2. `#discovery` is just a marker for `DiscoveryHostUrlFilter` to know that you should *load balance* (`Ribbon`) the url, it will be deleted before routing.

---

PS: I'm not *Spring* or *Pivotal* developer, this solution is just part of my own experience and may not *bug-less*
