### ISSUE TITLE
Spring redirect url when behind Zuul proxy

### ISSUE THREAD

**Issue by steventong** [spring-cloud/spring-cloud-netflix#1567]
I have an authentication server, with url: "http://localhost:8081/login"
 
behind zuul, it is "http://localhost:8082/users/login", with domain, "http://example.com/users/login"

my security config set the loginPage with "/login", when i am not login, the url "http://example/users/test" redirect to  "http://example.com/login", but what i want is "http://example.com/users/login"

my zuul service config:

```
zuul:
    routes:
        userService:
            path: /users/**
            serviceId: user-service
            sensitiveHeaders: none
    add-host-header: true
```

also not work at controller
open "http://example.com/users/test2"
   ```
 @RequestMapping(value = "/test2", method = RequestMethod.GET)
    public String index() {
        return "redirect:/test3";
    }
```

want redirect to "http://example.com/users/test3" but to "http://example.com/test3"
