### ISSUE TITLE
Problems with Ribbon/Feign/Zuul retry

### ISSUE THREAD

**Issue by eacdy** [spring-cloud/spring-cloud-netflix#1577]
I'm using Spring Cloud Camden SR3, and I wonder whether am I right.

## Ribbon Retry

Configuration below can make ribbon retry.

```yaml
spring:
  cloud: 
    loadbalancer:
      retry: 
        enabled: true
client:
  ribbon:
    MaxAutoRetries: 3
    MaxAutoRetriesNextServer: 3
    OkToRetryOnAllOperations: true
```

## Feign Retry

In Spring Cloud Camden SR3, Feign has its own retry logic. if I want to disable feign's retry, I can use:

```java
@Bean
public Retryer retryer() {
	return Retryer.NEVER_RETRY;
}
```

## Zuul Retry

```yaml
zuul:
  retryable: true
ribbon:
  MaxAutoRetries: 3
  MaxAutoRetriesNextServer: 3
  OkToRetryOnAllOperations: true 
```

## My Questions

* Am I right? 
* Is there any properties to config feign's retry? I think properties configuration is better than java configuration.
* **What's the best practise?**

## B.T.W
I've read the post https://github.com/spring-cloud/spring-cloud-netflix/issues/1290
