### ISSUE TITLE
Zuul filter should support multiple hosts router

### ISSUE THREAD

**Issue by huangfushun** [spring-cloud/spring-cloud-netflix#1583]
zuul currently can do "simple host router" by http client, which is one-one router,  I think  it should be able to use ribbon client if need to support multiple hosts router for load balance purpose.

**Comment by ryanjbaxter** [comment]
Zuul already does use Ribbon.  Can you elaborate?

**Comment by huangfushun** [comment]
it is one suggestion for "SimpleHostRoutingFilter" which construct url from 
[SimpleRouteLocator#81](https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/zuul/filters/SimpleRouteLocator.java)  currently it does not support load balance . and I would like to see if we can 
only can do  any change like [executeWithLoadBalancer](https://github.com/Netflix/ribbon/blob/master/ribbon-loadbalancer/src/main/java/com/netflix/client/AbstractLoadBalancerAwareClient.java)

**Comment by ryanjbaxter** [comment]
If you do not want to use Eureka to provide service information to Zuul you can provide a list of servers to Ribbon for Zuul to use and load balance between.

```
zuul:
  routes:
    users:
      path: /myusers/**
      serviceId: users

ribbon:
  eureka:
    enabled: false

users:
  ribbon:
    listOfServers: example.com,google.com
```

**Comment by huangfushun** [comment]
yes, it works, but  we should think about not to change service discovery and just additionally support like below config:
<pre>
zuul:
  routes:
    users:
      path: /myusers/**
      listOfServers: example.com,google.com
</pre>

**Comment by ryanjbaxter** [comment]
Zuul does not necessarily need to use Ribbon so having those properties under `zuul` does not make sense.

**Comment by spencergibb** [comment]
You can also leave ribbon enabled and set 

```
users:
  ribbon:
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    listOfServers: example.com,google.com
```

Closing as there is a way to do this currently and adding the feature is more work and maintenance than the few lines of configuration.
