### ISSUE TITLE
Using with UAA's Identity Zones 

### ISSUE THREAD

**Issue by bryantp** [spring-cloud/spring-cloud-netflix#1628]
Hello All,

Is there anyway to use Spring Cloud Netflix with UAA's Identity Zones? The problem I am having is that I create a user in a specific zone and then login through the zone's subdomain, but am unable to obtain an access token. I spoke with the UAA team and it is because in order to obtain an access token, I must do so through the subdomain of the Identity Zone. Spring Cloud lets me define the OAuth connection information in the application.yml file, like I have here:

```
security:
  oauth2:
    client:
      accessTokenUri: http://uaa.mydomain.io/uaa/oauth/token
      userAuthorizationUri: http://uaa.mydomain.io/uaa/oauth/authorize
      clientId: user-info-service
      clientSecret: secret
      authorizedGrantTypes: client_credentials,authorization_code,refresh_token,password
      scope: scim.write,uaa.resource
      authorities: scim.write,uaa.resource,zones.write,uaa.admin
    resource:
      jwt:
        keyUri: http://uaa.mydomain.io/uaa/token_key
```

but the access token uri is hardcoded to the default url (and the default zone). Is there anyway to define a more dynamic url for the access token uri? For example, for an Identity Zone:

`coke`

the url for the access token would be 

`coke.uaa.mydomain.io/uaa/oauth/token`

Thanks for any help.
