### ISSUE TITLE
Connection Refused

### ISSUE THREAD

**Issue by diogocapistrano** [spring-cloud/spring-cloud-netflix#1638]
I'm using zuul proxy for redirect requests (I use zuul filter to determine what origin server the request go) and load balancer (ribbon). I have 3 pools (or services-ids) on my configuration application.yml, for example:

```
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 120000

ribbon:
  ReadTimeout: 130000
  ConnectTimeout: 130000
  eureka:
    enabled: false

zuul:
  ignoredServices: "*"
  routes:
     sales:
         stripPrefix: false
         path: /sales/**
         service-id: sales-blue
      customer:
         stripPrefix: false
         path: /customer/**
         service-id: customer-blue

filter:
   configuration:
      blueOrGreen:
         enabled: true
         regex: '^[\d]+[0]$'
         routeMatch: sales-green
         routeNoMatch: sales-blue

sales-blue:
   ribbon:
      listOfServers: 15.15.55.10:8080, 15.15.55.11:8080
      ServerListRefreshInterval: 15000

sales-green:
   ribbon:
      listOfServers: 15.15.55.12:8080, 15.15.55.13:8080
      ServerListRefreshInterval: 15000

customer-blue:
   ribbon:
      listOfServers: 15.15.55.14:8080, 15.15.55.15:8080
      ServerListRefreshInterval: 15000

customer-green:
   ribbon:
      listOfServers: 15.15.55.16:8080, 15.15.55.17:8080
      ServerListRefreshInterval: 15000
```

The zuul pre filter set a service-id using headers parameters, so the zuul proxy route request for correct origin server.

My problem is when one pool is offline and zuul proxy redirect a request for it then occurrs "Connection Refused" error (it's correct, why the server is down, i know). I want zuul proxy don't redirect when server is offline, is there any way for the zuul proxy to find out that the server is offilne?
