### ISSUE TITLE
Zuul - Prefix is stripped but not path

### ISSUE THREAD

**Issue by gonzalad** [spring-cloud/spring-cloud-netflix#1657]
Hello, I want to call an log endpoint `http://localhost:7777` from my zuul gateway.
The client is expected to call this from this zuul URL : http://mygateway.com/api/logs

My gateway configuration :
```
zuul:
  prefix: /api
  routes:
    log:
      path: /logs
      url: http://localhost:7777
      strip-prefix: true
    users:
      path: /users
      url: ${server.iam.url}
```

Problem is that my zuul just removes the prefix, but not the path from the URL, so the gateway relays this request `http://localhost:7777/logs`, not on `http://localhost:7777`.

Is there a way to remove the path ?

Thanks,

Notes: From what I see all related code is in : 
 * store 'path' as requestURI request attribute : https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/zuul/filters/pre/PreDecorationFilter.java#L88
 * retrieves the saved path to build the URL : https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/zuul/filters/ProxyRequestHelper.java#L91

The URL is built from https://github.com/spring-cloud/spring-cloud-netflix/blob/d76bd84466616f53e5eee6879fee9a823d767841/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/zuul/filters/route/SimpleHostRoutingFilter.java#L179
