### ISSUE TITLE
Eureka - Ribbon - Service Version strategy

### ISSUE THREAD

**Issue by ivarulz** [spring-cloud/spring-cloud-netflix#168]
What strategy do you suggest for different service versions?

1)  change the `spring.application.name`?
ServiceA1.0 and ServiceA2.0 as values for application.name in Eureka Server

vs

2) Eureka custom metadata
```
eureka:
  instance:
    metadataMap:  
      version: ${spring.serviceVersion}
```

I can see this information in Eureka Server, but I am not sure it is usable by Ribbon.
