### ISSUE TITLE
Zuul with ribbon routing unable to validate custom ssl certificates

### ISSUE THREAD

**Issue by atiwari54** [spring-cloud/spring-cloud-netflix#1684]
In my application i want to search service with service id but my zuul is not connecting with eureka service, can any one help me out. 
1. when i hit http://localhost:8761/   then zuul is not showing there
2. If i comment the serviceid and enable the url then it will run as per requirement

here is my application.yml for zuul

```
spring:
  application:
    name: ZUUL

server:
  port: 8090

ribbon:
  eureka:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    test:
      path: /**
      serviceId: main
#     url: http://localhost:9080
```
