### ISSUE TITLE
RibbonUtils.updateToHttpsIfNeeded Should Deal With URI Equal To Empty String

### ISSUE THREAD

**Issue by ryanjbaxter** [spring-cloud/spring-cloud-netflix#1690]
I have the following configuration in my Zuul server.

```
server:
  port: 8080

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

zuul:
  routes:
    greeting:
      path: /greeting/**
      serviceId: greeting

ribbon:
  eureka:
    enabled: false

greeting:
  ribbon:
    listOfServers: localhost:8443
```

When I make a request to `http://localhost:8080/greeting` `RibbonLoadBalancingHttpClient.reconstructURIWithServer` will be called.  Since the `greeting` server has a port that ends in `443` we will try to set the scheme to `https` in `RibbonUtils.updateToHttpsIfNeeded`.  However the URI from the request is the empty string so when calling `uriComponentsBuilder.build(true).toUri()` the URI in `uriComponentsBuilder` is just `https` and this fails because it is not a valid URI.  I think there should be a check in `RibbonUtils.updateToHttpsIfNeeded` to make sure the URI is not the empty string.  @spencergibb what do you think?
