### ISSUE TITLE
eureka client don't use ip address in docker container 

### ISSUE THREAD

**Issue by niral22** [spring-cloud/spring-cloud-netflix#1710]
i have created simple spring cloud app with eureka server and client registering to eureka service. i've below in bootstrap.yml for eureka client. 
`eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone:  ${eureka.url:http://localhost:8761/eureka/,http://localhsot:8762/eureka/}
  instance:
    preferIpAddress: true
    ipAddress: 192.168.1.148
`
when running as direct spring boot apps, it works fine and registers client using IP address to eureka server. But when i run client as docker container, it always uses docker container id to register in eureka server. 

I am using docker for mac version 1.13.1.  and spring boot version 1.4.1. I looked at issue #1646 but it seems that issue was resolved and it was not with docker for mac. so, not sure.

Any help is appreciated. Thank you

**Comment by ryanjbaxter** [comment]
It is really hard to tell if your YAML is correct because of the way it is formatted, can you fix that?

**Comment by niral22** [comment]
sorry about that.. putting yml below again :
```
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone:  ${eureka.url:http://localhost:8761/eureka/,http://localhsot:8762/eureka/}
  instance:
    preferIpAddress: true
    ipAddress: 192.168.1.148
```
