### ISSUE TITLE
Zuul routing and static resources

### ISSUE THREAD

**Issue by ahmed-haggag82** [spring-cloud/spring-cloud-netflix#1755]
I have got 404 http error code for any resource when using zuul routing as a gateway

that is my configuration for routing

```
zuul:
 routes:

   api:
      path: /api/**
      url: http://localhost:8085
      sensitive-headers:
```

Please advise
