### ISSUE TITLE
How to register a SSL endpoint with eureka

### ISSUE THREAD

**Issue by craigivy** [spring-cloud/spring-cloud-netflix#176]
Hi, I'm running spring boot with SSL.  I'm wondering how I can properly register my SSL service with eureka.  Thanks for any advice.

I've configured spring boot with:

```
server:
  port: 8443
  ssl:
    protocol: "TLSv1.2"
    key-store: "classpath:my.keystore"
    key-store-password: secret
    key-password: secret
```

I've also tried forcing the port to be used during registration with:

```
eureka:
  instance:
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: 8443
```
