### ISSUE TITLE
EurekaClientAutoConfiguration#eurekaInstanceConfigBean incorrectly configures statusPageUrl and healthCheckUrl

### ISSUE THREAD

**Issue by strelok1** [spring-cloud/spring-cloud-netflix#1795]
If the application is setting `management.context-path` the statusPageUrl and healthCheckUrl are constructed without it if you don't specifically override like so:
```
eureka:
  instance:
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
```

example:

application.yml
```
management:
  port: 9090
  context-path: /manage
```

The resulting eureka instance config data is showing:
```
...
<statusPageUrl>http://mymachine:9090/info</statusPageUrl>
<healthCheckUrl>http://mymachine:9090/health</healthCheckUrl>
...
```
It would be good if EurekaClientAutoConfiguration#eurekaInstanceConfigBean picked up the managementPort automatically and configured the urls properly:
```
...
<statusPageUrl>http://mymachine:9090/manage/info</statusPageUrl>
<healthCheckUrl>http://mymachine:9090/manage/health</healthCheckUrl>
...
```
