### ISSUE TITLE
How can Services running in a Docker VM and running on localhost register at EUREKA dynamically?

### ISSUE THREAD

**Issue by srehker** [spring-cloud/spring-cloud-netflix#1810]
Hello everyone,

I have a problem with my Eureka Configuration. Normally all my services are running as docker containers in a VM. My configuration looks as follows:

```
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 192.168.99.100
```

Sometimes I want to debug a service and start it locally as spring-boot application and it still registers with the IP above. As far as I understood, the IP in the config simply overrides the real IP. My idea to solve this problem, is a configuration profile, which overrides the Docker VM IP. However my machine IP is changing regularly. Is there a way to let the configuration of the IP change dynamically according to my machines IP.

```
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 192.168.99.100
---

spring:
  profiles: local

eureka:
  instance:
    ip-address: TODO change dynamically
```

If this is not yet implemented, can I implement it myself somehow? Thanks a lot! :)
