### ISSUE TITLE
Zuul not returning gzip responses correctly

### ISSUE THREAD

**Issue by aabutaleb** [spring-cloud/spring-cloud-netflix#1818]
When I hit one of my services that returns gzipped data but Zuul always return plain-text responses.
At first I thought it was ignoring the Accept-Encoding header but it seems to be forwarding it correctly.

They're both running on Spring Cloud: Camden.RELEASE

The configuration for the service includes:

```
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/json;charset=UTF-8
    min-response-size: 64
```

**Comment by spencergibb** [comment]
Not sure there were any related changes or not, but can you try with the latest Camden.SR6?

**Comment by aabutaleb** [comment]
Tried just now, Camden.SR6 doesn't make any difference. Might it be a default configuration I need to overwrite in Zuul in order to proxy gzipped payloads?

**Comment by aabutaleb** [comment]
I made it work by enabling server compression in zuul. As a workaround it works, but still don't understand why it decides to decompress the response from the service and return it plain text instead of just proxying.

**Comment by spencergibb** [comment]
What exactly did you do to "enabl[e] server compression in zuul"?

**Comment by loesak** [comment]
I'm having what appears to be the same issue.

We're using spring-cloud-starter-zuul:1.2.1.RELEASE (zuul-core:1.3.0).

This is the request made from the browser to Zuul:
```
GET /...snip.../theme.json HTTP/1.1
Host: ...snip...:8873
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Accept: application/json
X-Requested-With: XMLHttpRequest
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.110 Safari/537.36
DNT: 1
Referer: http://...snip...:8873/
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8
Cookie: SESSION=...snip...
```
This is the request Zuul is sending to Nginx (which has gzip compression on):
```
GET /...snip.../theme.json HTTP/1.1
accept: application/json
x-requested-with: XMLHttpRequest
user-agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36
referer: http://...snip...:8873/
accept-language: en-US,en;q=0.8
authorization: bearer eyJhbGciOiJSUzI1Ni...snip...
x-forwarded-host: ...snip...:8873
x-forwarded-proto: http
x-forwarded-port: 8873
x-forwarded-for: ...snip...
Accept-Encoding: gzip
Host: localhost:80
Connection: Keep-Alive
```

This is the response being sent back from Nginx to Zuul:
```
HTTP/1.1 200 OK
Server: nginx/1.10.0 (Ubuntu)
Date: Thu, 27 Apr 2017 18:39:57 GMT
Content-Type: application/json
Last-Modified: Sun, 23 Apr 2017 17:29:01 GMT
Transfer-Encoding: chunked
Connection: keep-alive
Vary: Accept-Encoding
ETag: W/"58fce45d-3393"
Content-Encoding: gzip
```
And this is the response the browser receives back from Zuul:
```
HTTP/1.1 200
X-Application-Context: zuul-ui-proxy:monitored:0
Date: Thu, 27 Apr 2017 18:36:52 GMT
Last-Modified: Sun, 23 Apr 2017 17:29:01 GMT
Vary: Accept-Encoding
ETag: W/"58fce45d-3393"
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY
Content-Type: application/json
Transfer-Encoding: chunked
```

We would have expected something similar to the response:
```
HTTP/1.1 200 OK
Server: nginx/1.10.0 (Ubuntu)
Date: Thu, 27 Apr 2017 18:28:58 GMT
Content-Type: application/javascript
Last-Modified: Fri, 21 Apr 2017 17:53:07 GMT
Transfer-Encoding: chunked
Connection: keep-alive
Vary: Accept-Encoding
ETag: W/"58fa4703-1dbd6"
Content-Encoding: gzip
```

This is the pretty much the config we're using:
```
spring:
  session:
   store-type: HASH_MAP
server:
  use-forward-headers: true
security:
  ignored: /logoutSuccess,/css/**,/img/**,/favicon.ico
  user:
    password: none
  oauth2:
    client:
      client-id: ...snip...
      client-secret: ...snip...
      access-token-uri: http://...snip.../oauth/token
      user-authorization-uri: http://...snip.../oauth/authorize
      authorized-grant-types: authorization_code
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
         ...snip...
          -----END PUBLIC KEY-----
management:
  context-path: /management
zuul:
  ignored-patterns: /user,/logoutSuccess,/css/**,/img/**,/favicon.ico
  routes:
    api:
      path: /api/**
      url: http://...snip.../
    ui:
      path: /**
      url: http://...snip.../
```
When I get time, I will try with latest spring-cloud-starter-zuul:1.3.0 but wondering if this was even an issue with 1.2.1

**Comment by loesak** [comment]
@spencergibb 
I can confirm that is still happening on version 1.2.6.RELEASE which is the version referenced from Camden.SR6. Zuul is not returning the gzipped content it received from (e.g. no Content-Encoding: gzip header).

**Comment by zarezadeh** [comment]
It seems the problem arises when using `SimpleHostRoutingFilter`. `ResponseContentEncoding` interceptor should be disabled when creating new client in `SimpleHostRoutingFilter.newCient()` with calling `disableContentCompression `on `httpClientBuilder`

**Comment by cesartl** [comment]
Using `spring-cloud-dependencies:Cambden.SR5` I am observing the same issue.
The response from Zuul has:
```
Transfer-Encoding: chunked
```
and no `Content-Encoding` header.

After upgrading to `spring-cloud-dependencies:Dalston.SR1` I am seeing the expected response:

```
Transfer-Encoding: chunked
Content-Encoding: gzip
```

So as far as I am concerned this has been fixed

**Comment by cesartl** [comment]
Interestingly gzip compression is working when I'm using direct urls in the route configuration:

```yaml
zuul:
    routes:
        web-frontend:
            path: /**
            url: http://web-frontend:3000
```

however when I deploy to k8s, I use Kubeflix discovery:

```yaml
rm-web-frontend-nodejs:
    ribbon:
        ConnectTimeout: 250
        MaxAutoRetries: 0
        MaxAutoRetriesNextServer: 3
        OkToRetryOnAllOperations: true
        ReadTimeout: 8000
        ServerListRefreshInterval: 2000
        NIWSServerListClassName: io.fabric8.kubeflix.ribbon.KubernetesServerList
        KubernetesNamespace: ${k8sNAMESPACE}
        PortName: tcp80

zuul:
    routes:
        rm-web-frontend-nodejs:
          path: /**
          service-id: rm-web-frontend-nodejs
```

the gzip compression isn't working. I can see the `Accept-Encoding` header being passed to the downstream service, but the reply from zuul is not gzipped. I think this is the only difference I can spot. Does it make sense? Should I raise an issue on the kubeflix project?
