### ISSUE TITLE
GET request 411 error on zuul proxy for eureka clients.

### ISSUE THREAD

**Issue by beku8** [spring-cloud/spring-cloud-netflix#1824]
After updating to _Camden_ release, previously reported issue #1042 (411 content length required) is appearing again for ```GET``` requests. 

I've following config on my [small demo](https://github.com/beku8/zuul-411) app. :
```
zuul:
  ignoredServices: '*'
  routes:
    rs: /api/rs/**
    httpbin: 
      path: /api/httpbin/**
      url: http://httpbin.org
```
I've 2 routes: eureka client ```rs``` and direct proxy for ```httpbin```. 
Eureka client was throwing 411 error on GET requests. The difference was eureka client is setting unnecessary additional ```Transfer-Encoding: chunked``` header.

If we can't remove this header, I think we can set ```Content-Length: 0```, as it was handled [previously](https://github.com/spring-cloud/spring-cloud-netflix/issues/1042#issuecomment-227826025).

My config app is running with simple default config (no custom ```RibbonCommandFactory```):
```
@SpringBootApplication
@EnableZuulProxy
@EnableDiscoveryClient
public class Zuul411Application {

	public static void main(String[] args) {
		SpringApplication.run(Zuul411Application.class, args);
	}

}
```

p.s This issue is only apparent for certain network and ISPs.
