### ISSUE TITLE
custom route property

### ISSUE THREAD

**Issue by hodeh** [spring-cloud/spring-cloud-netflix#1854]
Is there a way to have custom property in a Route definition at configuration and then I can use it later in a filter.
----Config File-----
```
    route-x:
      path: /v1.0/route/x/**
      service-id: route-x
      strip-prefix: false
      custom-property-x: value-x
```
