### ISSUE TITLE
Cookies not passed across requests even with global zuul.sensitiveHeaders  set to blank

### ISSUE THREAD

**Issue by madheshr** [spring-cloud/spring-cloud-netflix#1867]
Hi
In our system we have Auth Service and other microservices behind Zuul Gateway.  Initially the auth service sets a cookie (upon successful authentication)... This cookie is then passed back and forth on each request (through the gateway to other microservices).  When a user directly accesses a microservice (without authentication), he is forced to authenticate first and then there is a subsequent redirect.  

The problem is that the Authentication services sets the response cookie but when the subsequent redirection request comes, the cookie is not present.  I have the global setting
zuul.sensitiveHeaders: 

What am i missing here?

**Comment by madheshr** [comment]
Just to add - there are no overriding sensitiveHeaders setting at individual route level.

**Comment by ryanjbaxter** [comment]
Can you provide a sample that reproduces what you are seeing?

**Comment by madheshr** [comment]
Hi
I am not able to extract a working code; but here's the full application.yml.  Note that we are not using Eureka.  We will have multiple instances in the Ribbon... (below is the test setup on my local) 
We need to pass the cookies back and forth both upstream and downstream

```
spring:
  application:
    name: platform-gateway
zuul:
  routes:
    psm:
      path: /platform-services-manager/**
      serviceId: psm
      stripPrefix: false
    platform-home:
      path: /platform-home/**
      serviceId: ph
      stripPrefix: false      
    session:
      path: /SessionTracker/**
      serviceId: session
      stripPrefix: false
psm:
  ribbon:
    listOfServers: localhost:9080
session:
  ribbon:
    listOfServers: localhost:9080
ph:
  ribbon:
    listOfServers: localhost:9080

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000
 
zuul.sensitiveHeaders: 
```
