### ISSUE TITLE
Zuul prefix can't set / * ？

### ISSUE THREAD

**Issue by fudali113** [spring-cloud/spring-cloud-netflix#1889]
my configuration is 
```yaml
zuul:
  ignoreLocalService: true
  ribbon:
    eager-load:
      enabled: false
  routes:
    elk-ms:
      path: /elk/**
      serviceId: elk-ms
    old-api:
      path: /**
      url: http://api.domain.com
  prefix: /*
```
run my app found route con`t get right path 
my request url is `/api/elk/test`, but `route.getPath() is /api/test`

[https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/zuul/filters/SimpleRouteLocator.java#L137](https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/zuul/filters/SimpleRouteLocator.java#L137)
```java
int index = route.getPath().indexOf("*") - 1;
if (index > 0) {
	String routePrefix = route.getPath().substring(0, index);
	targetPath = targetPath.replaceFirst(routePrefix, ""); // this code has bug ?               
	prefix = prefix + routePrefix;
}
```
