### ISSUE TITLE
use springfox:2.6.0 with eureka, view service information port exception at localhost:8761

### ISSUE THREAD

**Issue by taoyingqi** [spring-cloud/spring-cloud-netflix#1904]
## eureka client config
```
server.port: 10000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    appname: ${spring.application.name}
    prefer-ip-address: true
```
## spring fox 2.6.0
```
<!--swagger-ui-->
<dependency>
  <groupId>io.springfox</groupId>
  <artifactId>springfox-swagger2</artifactId>
  <version>${springfox.version}</version>
</dependency>
<dependency>
  <groupId>io.springfox</groupId>
  <artifactId>springfox-swagger-ui</artifactId>
  <version>${springfox.version}</version>
</dependency>
<dependency>
  <groupId>io.springfox</groupId>
  <artifactId>springfox-staticdocs</artifactId>
  <version>${springfox.version}</version>
</dependency>
```
## exception
click service status link at the Instances currently registered with Eureka table, open the tab link is http://localhost:8080, the port always is default.
But I use springfox:2.6.1, there is no problem
