### ISSUE TITLE
Possibility of introducing the new microservice to zuul without its redeployment

### ISSUE THREAD

**Issue by dmitry-naumovich** [spring-cloud/spring-cloud-netflix#1937]
Hello everyone! Could you please help me?

Imagine that the microservice distributed application is running, it leverages the basic Netflix Spring Cloud Stack, and Zuul is configured like that:
```
server:
  port: 9999
zuul:
  routes:
    microservice-a: /hello/**
    microservice-b: /hello/**
    cloud-config: /config/**
    cloud-discovery: /discovery/**
    cloud-dashboard: /dashboard/**
    elasticsearch: /elk/**
    kibana: /kibana/**
```

Later, when the application is run I'm introducing a new microservice, say, `microservice-c`, and I have to put a new route to it in Zuul. 
The questions is, is it possible to dynamically add new microservice (or it can be just the newer version of the existing microservice) to the zuul routing map without reloading/redeploying Zuul?

I assume that the zuul config should probably be moved outside of the project, e.g. to the external file

It's not correct to hit `/refresh` endpoint with a Scheduler because it causes the exhausting app overload. Maybe I can leverage Nicobar or other stuff using groovy to dynamically reload configuration?

Zuul is discovery (Eureka) client with `@EnableEurekaClient ` enabled.
