### ISSUE TITLE
Eureka & Ribbon - Retry on HTTP status

### ISSUE THREAD

**Issue by acorcoran-daon** [spring-cloud/spring-cloud-netflix#1938]
Hi,

Hi, I am using using Eureka discovery. However I only seem to get retries on catastrophic failures e.g. network outage rather than HTTP status codes. I have the following configuration:
```YML
spring:
  cloud:
    loadbalancer:
      retry:
        enabled: true

doc-processor:
  ribbon:
    retryableStatusCodes: 404, 503
      MaxAutoRetriesNextServer: 2
      MaxAutoRetries: 2
      OkToRetryOnAllOperations: true
```

My spring boot application is annotated with:
```Java
@enableeurekaclient
@springbootapplication
@componentscan
@enableretry
```
I am using RestTemplate which is configured to be loadbalanced:
```Java
@loadbalanced
@bean
RestTemplate getRestTemplate() {
    return new RestTemplate();
}
```
However I only see the next server being retried if there is a network error or similar.

I am using Dalston.RELEASE. It appears from the small amount of debugging that the configuration is not being picked up when eureka discovery is in use.

Am I missing something? 
Thanks
