### ISSUE TITLE
ZuulProperties does not set id for new routes in yml on refresh

### ISSUE THREAD

**Issue by digitaljoel** [spring-cloud/spring-cloud-netflix#196]
If I add a new route to configuration AFTER zuul has already started, such as:
```
zuul:
  routes:
    blah:
      path: /blah/**
      serviceId: blah
      stripPrefix: false
```
and then hit /refresh, the route is configured and a handler is mapped as shown in the log:

    Mapped URL path [/blah/**] onto handler of type [class org.springframework.cloud.netflix.zuul.web.ZuulController]

but the id property of the route is left as null because the init method in ZuulProperties is only called on @PostConstruct of the but not on refresh.  This causes a NullPointerException when attempting to dispatch to the new route

Modifying ZuulProxyConfig$ZuulRefreshListener.reset to call init on zuulProperties allowed the handler to be configured correctly without an application restart.

This is against BUILD-SNAPSHOT.
