### ISSUE TITLE
Configuration eureka.instance.ip-address Should be validated.

### ISSUE THREAD

**Issue by eacdy** [spring-cloud/spring-cloud-netflix#1963]
My friend `村正` makes a mistake. He sets `eureka.instance.ip-address = true`. When the program starts, it does not make any warning message.

I find that even do I set `eureka.instance.ip-address` an invalid IP, no warning message will comes out.
For example:

```
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: abcde.bbb.ccc.ddda
```

In this case, I set `eureka.instance.ip-address =abcde.bbb.ccc.ddda ` .
Not any exception nor warning message will remind me. Program will starts, but Can never work.

So, I think that the `eureka.instance.ip-address` Should be validated.

I think in the code  `org.springframework.cloud.netflix.eureka.EurekaInstanceConfigBean#setIpAddress` May add some code to validate whether do I set a valid value.

I will make a PR if needed.
