### ISSUE TITLE
Zuul route to management port with Eureka

### ISSUE THREAD

**Issue by j-ramos** [spring-cloud/spring-cloud-netflix#1977]
Hi,

I have all my services set up with Eureka as service discovery and I'm using zuul to route request into them. However I have a different management port on all of them (eg. port :8888 for regular and :8887 for management).

Right now I have this working using a static definition of the URL (example below) but I was wondering if there is a way I can implement something that'll fetch the url from Eureka similar to using serviceId for the regular port.

```
zuul:
  ignored-services: "*"
  strip-prefix: false
    config-service:
      path: /config-service/**
      serviceId: config-service
      strip-prefix: false
    config-service-mgmt:
      path: /config-service-mgmt/**
      url: http://localhost:8887/config-service/
      strip-prefix: true
```
