### ISSUE TITLE
Zuul stripPrefix problem

### ISSUE THREAD

**Issue by aivans** [spring-cloud/spring-cloud-netflix#199]
I am playing with the customers-stores sample.
I routed all traffic from the UI app to go through a separate Zuul server.

Problem:
- in the UI I have these configurations:

```
  .constant('appConfiguration', {
   customerApiUrl: 'http://localhost:8765',
    storeApiUrl: 'http://localhost:8765/stores'    
  })
```

- in Zuul:

```
zuul:
  ignored-services: "*"
  routes:
    stores:
      path: /stores/**
      stripPrefix: false
    customers:
      path: /customers/**
      stripPrefix: false  
```

According to the documentation:

application.yml

```
 zuul:
  routes:
    users:
      path: /myusers/**
      stripPrefix: false
```

In this example requests to "/myusers/101" will be forwarded to "/myusers/101" on the "users" service.

But, it doesn't really work like that. In the Zuul console:

```
Matching patterns for request [/customers] are [/customers/**]
RestClient sending new Request(GET: ) http://CLUJPC100:9000
```

So, it strips the suffix "customers". Am I missing something?
From an API Gateway perspective it does not make sense to have "/customers/customers" anyway.
