### ISSUE TITLE
Eureka dead instance eviction problem

### ISSUE THREAD

**Issue by aivans** [spring-cloud/spring-cloud-netflix#202]
I am trying to find a good configuration for creating a cluster of Eureka nodes.
During the experiment I found a weird problem. An Eureka instance which I closed manually is not removed from the Eureka information that other nodes have.

**peer1** (serviceURL points to itself):

```
spring:
  profiles: peer1 # not standalone
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://user:${eureka.password}@localhost:8761/eureka/
```

**peer2** (serviceURL points to peer1):

```
spring:
  profiles: peer2 # not standalone
server:
  port: 8762
eureka:
  instance:
    hostname: localhost
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}     
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://user:${eureka.password}@localhost:8761/eureka/
```

**peer3** (serviceURL points to peer1):

```
spring:
  profiles: peer3 # not standalone
server:
  port: 8763
eureka:
  instance:
    hostname: localhost
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}     
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://user:${eureka.password}@localhost:8761/eureka/
```

I closed peer3  manually and after 15 minutes I can still see the instance in info stored by peer1.
Even more, I have a service which at every 5 seconds displays the info it has about Eureka nodes and the node which has `isCoordinatingDiscoveryServer==true`. Actually peer 3 appears here and it is the `coordinatingDiscoveryServer: Discovery server host: localhost:8763`.

Note: peer2 and peer3 point to peer1 (serviceUrl) and peer1 points to itself, so no cross reference.
