### ISSUE TITLE
Hystrix Dash fails to load static resources when server.contextPath is set

### ISSUE THREAD

**Issue by NickPadilla** [spring-cloud/spring-cloud-netflix#204]
Hello,

I believe this commit has caused some problems with my setup, https://github.com/spring-cloud/spring-cloud-netflix/commit/9fb833e4a90f4d20b9e01c595b21c3a683f898ca  Here is the configurations. 
Zuul Config
```
zuul:
  routes:
    micloudhystrix:
      path: /micloudhystrix/**
      stripPrefix: false
      retryable: true
```
Hystrix Config
```
server:
  contextPath: /${spring.application.name:}
  port: ${SERVER_PORT:7979}
```
When working with Zuul, before the commit, it was serving the static resources correctly. I did try to remove the server.contextPath setting from Hystrix and removed the stripPrefix from Zuul. With this configuration I was never able to even reach the Hystrix Dashboard. Here is the browser console output.

![screen shot 2015-02-06 at 10 55 20 am](https://cloud.githubusercontent.com/assets/1381015/6130498/adac4062-b102-11e4-96ec-19363917a244.png)
