### ISSUE TITLE
Unable to register instance on eureka server if server.port is set to 0

### ISSUE THREAD

**Issue by ronakhingar** [spring-cloud/spring-cloud-netflix#2076]
I am running many APIs currently on different VMs. Each of the API was using a dedicated server port initially . As I don't want to get in the business of port assigning I changed the property of server.port to 0 to use a random available port. But doing that fails my API registrations with Eureka Server which is running on a fixed port (8761)  .
```
eureka:
  instance:
    prefer-ip-address: false
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
    secure-port-enabled: true
    non-secure-port-enabled: false
    secureVirtualHostName: ${spring.application.name}
  client:
    initialInstanceInfoReplicationIntervalSeconds: 5
    instance-info-replication-interval-seconds: 5
  server:
    response-cache-update-interval-ms: 5000

server:
  port: 0

```
