### ISSUE TITLE
Eureka registration prefer hostname instead of IP

### ISSUE THREAD

**Issue by dhanvi** [spring-cloud/spring-cloud-netflix#2084]
Is there a way for eureka to register via hostname instead of IP, I have tried setting eureka.instance.preferIpAddress to false but it takes hostname some times and IP address sometime. [Related stackoverflow Question](https://stackoverflow.com/questions/44689202/springboot-client-unable-register-with-eureka-using-docker-container-id)

Using hostname is useful when running micro services with docker swarm, as docker-id (which is same as hostname of the container) of the container is resolvable to all the containers (even if the containers are on different nodes/VM's)

I am aware of setting preferIpAddress as true and [ignoring networks](http://cloud.spring.io/spring-cloud-static/spring-cloud.html#ignore-network-interfaces) but I am looking for a straight forward solution.

Thanks in Advance.

**Comment by ryanjbaxter** [comment]
Could you provide your configuration?

**Comment by dhanvi** [comment]
Eureka
```
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://discovery-eureka:8761/eureka/
```
client
```
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://discovery-eureka:8761/eureka/
  instance:
    preferIpAddress: false
```

Here discovery-eureka is the docker service name (In docker swarm you can hit the containers using the service name) and we have only one instance (container) of eureka running.
