### ISSUE TITLE
Zuul default route 

### ISSUE THREAD

**Issue by Sunrry** [spring-cloud/spring-cloud-netflix#2137]
In my project, I use Zuul to route the incoming request to correct service component, all of my service components are registered to consul, and the api-gateway (zuul) configuration is as below:
```
...
zuul:
  routes:
    auth:
       path: /auth/**
       serviceId: auth
...
```

And then, I have a new service to register to the consul, namely user service,and this user service has succeeded in registering itself in consul, the instance name is `user`, but I forget to add the route configurations just as showed in code blocks above.
But, surprisedly， I found I can get the right endpoint response back by the address: `http://localhost:8888/user/info` (Here, 8888 is the service port of api-gateway service), and here I want to request the /info Actuator endpoint provided by spring cloud. 
And my question is : How can this request go through the api-gateway(zuul), and find the correct user service ?

Thanks a lot
Sunrry

**Comment by dyc87112** [comment]
Zuul  will create default route for every service：

path: /<ServiceName>/**
serviceId: <ServiceName>

When your `user` service registering，zuul create a route： path is `/user/**`，serviceId is `user`

If you do not want user service export，you can set ：

```java
zuul:
  ignoredServices: user
```

**Comment by spencergibb** [comment]
I'm afraid I don't quite understand. By default, our zuul code adds routes for all services in discovery. To ignore them, use the tip from @dyc87112 above.

**Comment by Sunrry** [comment]
@dyc87112 So you mean the default route will be set by Zuul once our service is registered to consul, and this default route does not need any configuration like:
```
zuul:
    routhes:
        user:
            path: /user/**
            serviceId: user 
```
Because I alway think that all of routes of Zuul need to be declared by configurations, so there are many routes in my project like:
```
zuul:
    routhes:
        auth:
            path: /auth/**
            serviceId: auth
         expense:
            path: /expense/**
            serviceId: expense
        monitor:
            path: /monitor/**
            serviceId: monitor
```
It seems I do a lot of needless work. 
Thanks
