### ISSUE TITLE
Spring Boot 1.5.1 and Spring Cloud Dalston.M1 Config client connection refused 

### ISSUE THREAD

**Issue by binitdatta** [spring-cloud/spring-cloud-netflix#2156]
I am trying to use Spring Boot 1.5.1.RELEASE and Spring Cloud Dalston.M1 to develop

A Spring cloud Eureka Server 
A Spring Cloud Config Server
A Spring Cloud Config Client

with three Docker images built with Gradle se.transmode.gradle:gradle-docker:1.2.

These are my Repos that I am using in my gradle build file.

repositories {
	mavenCentral()
	maven { url "https://repo.spring.io/milestone" }
}

Once the Docker images are built, I am trying to use a docker-compose.yml (shown later) file to bring all three services up together.

What happens is this

1. My Eureka comes up nicely.
2. After sometime the Configserver comes up nicely as well.
3. I see in the console the Config Server being registered with Eureka
4. I navigate to http://localhost:8761/ and see the ConfigServer registered there
5. I test the config server in a browser http://10.0.75.1:8888/products-search-service/dev and that brings up properties for me.
6. However, the config client fails with this

products-search-service | 2017-07-25 14:16:15.340  WARN [products-search-service,,,] 5 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://config:8888/products-search-service/dev": Connection refused (Connection refused); nested exception is java.net.ConnectException: Connection refused (Connection refused)

I suspected something wrong with my Windows for Docker environment and tried another git repo that I forked from a Git contributor sqshq.

https://github.com/binitdatta/PiggyMetrics

This repository is using Spring Boot 1.3.5.RELEASE and Spring Cloud Brixton.RELEASE. When I followed his instructions and started docker-compose up in the project clone directory, it came up nicely. I tried to emulate all properties from his config server and config client, to my own but it did not help and the connection issues persist. 

My config-client bootstrap.yml

```
spring:
  application:
    name: products-search-service  
  cloud:
    config:
      uri: http://config:8888
      fail-fast: true
      password: ${CONFIG_SERVICE_PASSWORD}
      username: user
```

My config client application.yml

---
```
eureka:
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/
      fetchRegistry: true
server:
  port: ${SERVER_PORT:8081} 
```

My Config Server application.yml

```
---
eureka:
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/
      fetchRegistry: true
server:
  port: ${SERVER_PORT:8888}
spring:
  cloud:
    config:
      server:
        git:
          uri: <git_repo>
          username: <username>
          password: <password>
          search-paths: '{application}'     
security:
  user:
    password: ${CONFIG_SERVICE_PASSWORD}
```

There is probably no username and password issues as I can clone the properties repo using the same username and password and this http://10.0.75.1:8888/products-search-service/dev works.

My Config server bootstrap.properties

spring.application.name=configserver

My Eureka Server application.yml

```
server:
  port: ${PORT:8761}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0 
```

Any clues / help from the experts in the community would be highly appreciated.

Here is my docker-compose file.

```
version: '2.1'
services:
  registry:
    environment:
      CONFIG_SERVICE_PASSWORD: detachment
    image: retailpoc-service-registry-server
    container_name: registry
    restart: always
    ports:
      - 8761:8761
    logging:
      options:
        max-size: "10m"
        max-file: "10"
  config:
    environment:
      CONFIG_SERVICE_PASSWORD: detachment
    image: retailpoc-config-server
    container_name: configserver
    restart: always
    depends_on:
      - registry
    ports:
      - 8888:8888
    logging:
      options:
        max-size: "10m"
        max-file: "10"
  products-search:
    environment:
      CONFIG_SERVICE_PASSWORD: detachment
      SPRING_PROFILES_ACTIVE: dev
    image: retailpoc-products-search-service
    container_name: products-search-service
    restart: always
    depends_on:
      - registry
      - config
    links:
      - config
    ports:
      - 8081:8081
    logging:
      options:
        max-size: "10m"
        max-file: "10"
```

**Comment by ofir-popowski** [comment]
I think I'm having the exact same issue with Dalston.SR1, but I was using docker-compose version 3.3.

**Comment by ryanjbaxter** [comment]
Have you tried the latest Dalston releases?

**Comment by binitdatta** [comment]
Ryan, Thanks for your interest. I think I tired  Spring Boot 1.5.2.RELEASE with Spring Cloud Dalston.SR1. However, will try again and confirm.

What surprised me is this https://github.com/sqshq/PiggyMetrics

This uses a complete Microservices application along with Auth, Registry and Config. I followed the instruction and it worked on the same laptop where I am struggling with my own, using the config client the same way PiggyMetrics does.  This application uses
1.3.5.RELEASE and Brixton.RELEASE.

I will run with the latest Dalston.SR1 and confirm tomorrow,

Thanks,

Binit

**Comment by binitdatta** [comment]
Hi Ryan,

I did try the Spring Boot 1.5.2.RELEASE AND Spring Cloud Dalston.SR1. As per the spring.io these are latest spring cloud versions.

Here is my sample build.gradle file

```
buildscript {
	ext {
		springBootVersion = '1.5.2.RELEASE'
	}
	repositories {
		mavenCentral()
	}
	dependencies {
		classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
		classpath('se.transmode.gradle:gradle-docker:1.2')
	}
}

apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'org.springframework.boot'
apply plugin: 'docker'

jar {
	baseName = 'retailpoc-config-server'
	version = '0.0.1-SNAPSHOT'
}

sourceCompatibility = 1.8
targetCompatibility = 1.8

repositories {
	mavenCentral()
	maven { url "https://repo.spring.io/milestone" }
}


dependencies {
	compile('org.springframework.boot:spring-boot-starter-actuator')
	compile('org.springframework.cloud:spring-cloud-config-server')
	compile('org.springframework.cloud:spring-cloud-starter-eureka-server')
	testCompile('org.springframework.boot:spring-boot-starter-test')
}

dependencyManagement {
	imports {
		mavenBom "org.springframework.cloud:spring-cloud-dependencies:Dalston.SR1"
	}
}

task buildDocker(type: Docker, dependsOn: build) {
	push = false
	applicationName = jar.baseName
	dockerfile = file('src/main/docker/Dockerfile')
	doFirst {
		copy {
			from jar
			into stageDir
		}
	}
}
```
I am however, still receiving the same error

retailpoc-hellow-world-two    | Caused by: org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://config:8888/products-search-service/dev": Connection refused (Connection refused); nested exception is java.net.ConnectException: Connection refused (Connection refused)

I also deleted my local Gradle cashe and downloaded the dependencies fresh again. Situation persists.

Thanks,

Binit

**Comment by ofir-popowski** [comment]
I know it sounds obvious, but the exact same thing happened to me when I forgot to `mvn clean install` after changing the eureka url in the properties files, so docker ended up creating an image with a misconfigured jar.

**Comment by ryanjbaxter** [comment]
To be honest this is kind of hard for me to troubleshoot without the docker images.  Its unlikely a problem with Spring Cloud given that it is an connection issue.  The key is figuring out why the container cant reach `http://config:8888/products-search-service/dev`.  Have you sshed into the container and looked at the hostname configuration?  Maybe tried pinging the config container?

**Comment by binitdatta** [comment]
Thanks, Ryan for the suggestions. I am pretty sure that the jars are proper. I checked them a number of times. However, let me try sshing into the Docker container as you suggested. Let me also try the hostname with the config clients. 

Thanks,
Binit

**Comment by binitdatta** [comment]
Hi Ryan,

Here are my three containers

```
C:\Work\RetailPOC\LatestDev>docker ps
CONTAINER ID        IMAGE                               COMMAND                  CREATED             STATUS              PORTS                    NAMES
8e644e71d4d1        retailpoc-products-search-service   "sh -c 'java $JAVA..."   21 minutes ago      Up 8 seconds        0.0.0.0:8081->8081/tcp   products-search-service
42291f8c616b        retailpoc-config-server             "sh -c 'java $JAVA..."   23 minutes ago      Up 9 minutes        0.0.0.0:8888->8888/tcp   configserver
ba859c2bb43e        retailpoc-service-registry-server   "sh -c 'java $JAVA..."   6 hours ago         Up 9 minutes        0.0.0.0:8761->8761/tcp   registry
```

I could ssh into the retailpoc-products-search-service with id 8e644e71d4d1 and ping the configserver with and without the port 8888

```
C:\Work\RetailPOC\LatestDev>docker exec -i -t 8e644e71d4d1 /bin/sh
/ # ping configserver:8888
PING configserver:8888 (172.18.0.3): 56 data bytes
64 bytes from 172.18.0.3: seq=0 ttl=64 time=0.121 ms
64 bytes from 172.18.0.3: seq=1 ttl=64 time=0.071 ms
64 bytes from 172.18.0.3: seq=2 ttl=64 time=0.152 ms
64 bytes from 172.18.0.3: seq=3 ttl=64 time=0.083 ms
64 bytes from 172.18.0.3: seq=4 ttl=64 time=0.121 ms
64 bytes from 172.18.0.3: seq=5 ttl=64 time=0.071 ms
64 bytes from 172.18.0.3: seq=6 ttl=64 time=0.077 ms
64 bytes from 172.18.0.3: seq=7 ttl=64 time=0.115 ms
```

And without the port

```
C:\Work\RetailPOC\LatestDev>docker exec -i -t 8e644e71d4d1 /bin/sh
/ # ping configserver
PING configserver (172.18.0.3): 56 data bytes
64 bytes from 172.18.0.3: seq=0 ttl=64 time=0.097 ms
64 bytes from 172.18.0.3: seq=1 ttl=64 time=0.090 ms
64 bytes from 172.18.0.3: seq=2 ttl=64 time=0.095 ms
64 bytes from 172.18.0.3: seq=3 ttl=64 time=0.073 ms
64 bytes from 172.18.0.3: seq=4 ttl=64 time=0.082 ms
64 bytes from 172.18.0.3: seq=5 ttl=64 time=0.073 ms
```
I reconfirmed that the jars are build properly.

Thanks,

Binit

**Comment by binitdatta** [comment]
Hi Ryan,

I could also ssh inside the container and do a curl and here is the output which is working

```
/ # curl http://configserver:8888/products-search-service/dev
{"name":"products-search-service","profiles":["dev"],"label":null,"version":null,"state":null,"propertySources":[{"name":"https://wmp.visualstudio.com/DefaultCollection/WMP-HighPerformanceArchPOC/_git/RetailPOC-configuration-store/products-search-service/products-search-service-dev.yaml","source":{"cors.allowOrigins":"http://wmp-retailpoc-ui-web.s3-website-us-west-2.amazonaws.com"}},{"name":"https://wmp.visualstudio.com/DefaultCollection/WMP-HighPerformanceArchPOC/_git/RetailPOC-configuration-store/application-dev.yml","source":{"spring.cloud.bus.enabled":true,"spring.cloud.stream.bindings.springCloudBusInput.destination":"springCloudBus"}}]}/ #
```
thanks,

Binit

**Comment by bijukunjummen** [comment]
Happened to notice that the url in @ryanjbaxter message was `http://config:8888/products-search-service/dev` whereas in yours @binitdatta is `http://configserver:8888/products-search-service/dev`..is there a typo in your configuration somewhere, `config` vs `configserver`

**Comment by spencergibb** [comment]
I noticed the same thing, but @bijukunjummen got to it before me. Either way, connection refused are likely not a code problem, but a configuration problem.

**Comment by binitdatta** [comment]
Thanks to both of you for helping.  I changed it from config to configserver in all the relevant places. However, I can ping and curl both the http://configserver:8888/products-search-service/dev and http://config:8888/products-search-service/dev from inside the config client container.

I can do this http://localhost:8888/products-search-service/dev and it works

and this

http://10.0.75.1:8888/products-search-service/dev

Here is my bootstrap.yml for the products-search service

```
spring:
  application:
    name: products-search-service  
  cloud:
    config:
      uri: http://configserver:8888
      fail-fast: false
      password: ${CONFIG_SERVICE_PASSWORD}
      username: user
```
The docker-compose file is unchanged from above. 

Here is my config server application.yml

```
---
eureka:
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/
      fetchRegistry: true
server:
  port: ${SERVER_PORT:8888}
spring:
  cloud:
    config:
      server:
        git:
          uri: https://wmp.visualstudio.com/DefaultCollection/WMP-HighPerformanceArchPOC/_git/RetailPOC-configuration-store
          username: 
          password: 
          search-paths: '{application}'     
security:
  user:
    password: ${CONFIG_SERVICE_PASSWORD}

```
thanks,

Binit
