### ISSUE TITLE
Zuul‘s property `zuul.ribbon.eager-load.enabled` has no effect

### ISSUE THREAD

**Issue by dyc87112** [spring-cloud/spring-cloud-netflix#2159]
When I set `zuul.ribbon.eager-load.enabled=true` in Zuul has no effect。But when I set：

```java
ribbon.eager-load.enabled=true
ribbon.eager-load.clients=service-a
```
It has effect. Whether `zuul.ribbon.eager-load.enabled` property has some bugs?

**Comment by bijukunjummen** [comment]
Checking - internally it is the same functionality, just that `zuul.ribbon.eager-load.enabled` should have collected the clients based on the `zuul.routes`.

**Comment by bijukunjummen** [comment]
@dyc87112, can you please paste your `zuul.*` configuration. Does it look like this:

```
zuul:
  ignoredServices: '*'
  ribbon:
    eager-load:
      enabled: true
  routes:
    servicea:
      path: /servicea/**
      stripPrefix: false
      serviceId: service-a
```
