### ISSUE TITLE
Zuul route: Use alternate path for actual backend

### ISSUE THREAD

**Issue by msamad** [spring-cloud/spring-cloud-netflix#2191]
Hi guys,
I've got a use case:
Use an alternate path instead of actual path for the backend service.
e.g. If I want to route calls on `/users/service` to `/newusers/newservice`, there is no way I can do that. The stripPrefix does not help in this scenario since path is appended to the url. This is going to be helpful to port the legacy endpoints to new ones.

Adding something like `appendPath` flag would be useful which will replace the path instead of appending it to the url.
```
zuul:
  routes:
    users:
      path: /myusers/service
      url: http://user-service/newusers/newservice
      appendPath: false
```
I can do the PR for this, what do you guys think?

Cheers!
