### ISSUE TITLE
Zuul route: Ability to change timeout for a specific route

### ISSUE THREAD

**Issue by msamad** [spring-cloud/spring-cloud-netflix#2192]
Hi guys,
Got another use case:
Ability to add a timeout value for a route instead of a default timeout value. Not all backend services have the same timeout, some can have less and some can have large timeouts.
```
zuul:
  routes:
    users:
      path: /users/service
      url: http://user-service
      timeout: 20000
    orders:
      path: /orders/service
      url: http://order-service
```
In the above example `users` will have a timeout of `20000` milliseconds while the `orders` will have a default timeout value.

Around the same note, it would be nice to have a map object with each route. It would make customization so much easier and different properties could be attached to routes and used for multiple purposes.

I can do the PR for these if you guys agree.

Cheers!

**Comment by ryanjbaxter** [comment]
I wondering if this is only a problem when not using Ribbon.  With Ribbon you should be able to specify the timeout for a given service.  However when not using Ribbon, I don't think we have a way of doing this.  Have you looked into whether this is possible using Ribbon?

**Comment by msamad** [comment]
Hi,
Not using Ribbon, just wanted to have this functionality without Ribbon.

**Comment by ryanjbaxter** [comment]
So one approach you could take is to use Ribbon but use the a static server list.  Then you can set timeouts for specific ribbon services.

**Comment by indrabasak** [comment]
If you are using hystrix, here is an example for setting different timeouts for different routes:

```yaml
hystrix:
    users:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
    orders:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
```
