### ISSUE TITLE
Properties are not resolved in statusPageUrlPath or healthCheckUrlPath

### ISSUE THREAD

**Issue by wgorder** [spring-cloud/spring-cloud-netflix#222]
```
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: ${management.contextPath}/info
    healthCheckUrlPath: ${management.contextPath}/health
```

produces this output when hitting /eureka/apps

```
<statusPageUrl>
http://Williams-MacBook-Pro.local:9000${management.contextPath}/info
</statusPageUrl>
<healthCheckUrl>
http://Williams-MacBook-Pro.local:9000${management.contextPath}/health
```
