### ISSUE TITLE
Hystrix command properties not working

### ISSUE THREAD

**Issue by sargurgn** [spring-cloud/spring-cloud-netflix#2230]
hystrix.command.* properties are not taking effect. Due to default time out always the fallback method is getting called. STS also does not recognise these properties. Does the service need to be registered to eureka for hystrix command properties to work? Cant i override the fallback timeout configuration with just hystrix-starter jar?

<img width="315" alt="screen shot 2017-08-28 at 12 44 49 pm" src="https://user-images.githubusercontent.com/12994842/29762967-bd668d04-8bee-11e7-9fae-44f234669d84.png">

**Comment by indrabasak** [comment]
I think your syntax is slightly incorrect. Here is what I am using:
```yaml
hystrix:
    serviceA:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
    serviceB:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
```
