### ISSUE TITLE
Hystrix Thread Pool Isolation Strategy Not Working

### ISSUE THREAD

**Issue by indrabasak** [spring-cloud/spring-cloud-netflix#2233]
I tried creating separate thread pools for **Zuul Hystrix Ribbon Commands** but ended up creating a single thread pool named **RibbonCommand**.  I was expecting **serviceA** and **serviceB** to use separate thread pools while **serviceC** using semaphore.

<img width="450" alt="screen shot 2017-08-28 at 12 25 36 pm" src="https://user-images.githubusercontent.com/18181722/29790077-3da1d958-8bed-11e7-8a0e-e68443d492a5.png">

I am using Spring cloud **Dalston.SR3** and Spring Boot **1.5.6.RELEASE** versions. I also followed the configuration specified [here](https://github.com/Netflix/Hystrix/wiki/configuration#execution.isolation.strategy). Here is my configuration:

```yaml
zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  ignoredPatterns: /health/**
  remove-semicolon-content: true
  # doesn't work
  # ribbonIsolationStrategy: THREAD
  # threadPool:
  #  useSeparateThreadPools: true
  routes:
    serviceA: /v1/aaa/**
    serviceB: /v1/bbb/**
    serviceC: /v1/ccc/**
    
hystrix:
  command:
    serviceA:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 10000
    serviceB:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 10000 
```
