### ISSUE TITLE
Is it possible to set specific Ribbon and Hystrix config for a Eureka service endpoint in Zuul routes?

### ISSUE THREAD

**Issue by abaculus** [spring-cloud/spring-cloud-netflix#224]
Hi

If I'd like to have a specific config (e.g. MaxAutoRetries, ConnectTimeouts, threadPool sizes etc) for Ribbon and Hystrix when calling a specific route:

```
zuul:
  routes:
    users:
      path: /myusers/**
      serviceId: users_service
```

Is it possible and if so how could I do this?

Thanks!
