### ISSUE TITLE
How Could I specify services to monitor When I use Turbine Stream?

### ISSUE THREAD

**Issue by eacdy** [spring-cloud/spring-cloud-netflix#2245]
I use turbine to aggregate hystrix stream. Here goes Turbine's dependencies:

```xml
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-turbine-stream</artifactId>
</dependency>
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-stream-kafka</artifactId>
</dependency>
```

Code:

```java
@SpringBootApplication
@EnableTurbineStream
@EnableDiscoveryClient
public class TurbineApplication {
	public static void main(String[] args) {
		SpringApplication.run(TurbineApplication.class, args);
	}
}
```

application.yml

```yaml
server:
  port: 8989
management:
  port: 8990
spring:
  cloud:
    stream:
      kafka:
        binder:
          zk-nodes: 10.5.2.194:2181
          brokers: 10.5.2.194:9092
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true
```

Now, I have two services, one is  `service-1` and the other one is `service-2` .Now Turbine will monitor both of them.

**I don't wanna monitor all of the services connecting to kafka.**

HOW to monitor only one of them, like using `localhost:8989?cluster=service-1` monitoring `service-1` or other way. Could you help me?
