### ISSUE TITLE
Is it possible for Zuul to call itself via a filter? 

### ISSUE THREAD

**Issue by indrabasak** [spring-cloud/spring-cloud-netflix#2288]
I know it's possible for Zuul to make a request to an endpoint backed by one of its custom REST controllers. However, this internal call is not routed through any of its **Zuul Filter**s. 

I am trying to find out if it's possible to **route an internal call through one or more of its Zuul filter(s)**.

**Comment by eacdy** [comment]
`SendForwardFilter` .

```yaml
zuul:
  routes:
    abc: 
      path: /abc/**
      url: forward:/abc
```
