### ISSUE TITLE
Eureka client not auto-configuring secure port when server.port is 0

### ISSUE THREAD

**Issue by raiRaiyan** [spring-cloud/spring-cloud-netflix#2303]
The following is my application.yml

```yaml
spring:
  application:
    name: sandbox-spring


server:
  port: 0
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: springisawesome
    keystoretype: pkcs12
    keyalias: 1

eureka:
  client:
    service-url:
      defaultZone: https://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: false
    secure-port-enabled: true
```

Here when I retrieve application list from eureka server 
```xml
<application>
  <name>SANDBOX-SPRING</name>
  <instance>
    <instanceId>localhost:sandbox-spring:0</instanceId>
    <hostName>loclahost</hostName>
    <app>SANDBOX-SPRING</app>
    <ipAddr>172.25.2.163</ipAddr>
    <status>UP</status>
    <overriddenstatus>UNKNOWN</overriddenstatus>
    <port enabled="true">33877</port>
    <securePort enabled="true">443</securePort>
...
```

`securePort` defaults to 443, whereas the `port` is set to the poper value.  

`EurekaAutoServiceRegistration` changes only the non secure port when registering with eureka server. Should it not change the secure port too?
