### ISSUE TITLE
How to set proxy for routing server in zuul?

### ISSUE THREAD

**Issue by fisache** [spring-cloud/spring-cloud-netflix#2320]
Hi,
My pc is using proxy server when connect network, and I ran _spring-cloud-netflix-zuul_ in that.
I set gradle and java proxy but zuul can't connect external routing server such as google.com..
Just result in timeout. (although set ribbon and histrix connect time changed) 
gradle proxy in {HOME}/.gradle/gradle.property and java build with -DproxyHost, proxyPort
What's setting I need to use zuul?
Thanks.

**Comment by ryanjbaxter** [comment]
It all might depend on how you are using Zuul.  Can you supply your configuration?

**Comment by fisache** [comment]
I set for gradle proxy in {HOME}/.gradle/gradle.properties
```
systemProp.http.proxyHost={proxy_ip}
systemProp.http.proxyPort={proxy_port}
```
and maybe for java when build gradle
```
./gradlew bootRun -Dhttp.proxyHost={proxy_ip} -Dhttp.proxyPort={proxy_port}
```
application.yml is just routes setting
```
zuul:
  host:
    connect-timeout-millis: 5000
    socket-timeout-millis: 10000
  routes:
    test:
      path: /test/**
      serviceId: test
      url: http://www.google.com
    test2:
      path: /test2/**
      serviceId: test2
      url: http://localhost:3010
```
In case 'test' like external connection, result in timeout fail,
but 'test2' like internal connection, result in success
Thx @ryanjbaxter
