### ISSUE TITLE
Add unified username、password for eureka.client.serviceUrl

### ISSUE THREAD

**Issue by kimjuny** [spring-cloud/spring-cloud-netflix#2323]
## 1. Currently

```
eureka:
  client:
    serviceUrl:
      defaultZone: ${ZONE}
```

`ZONE` -> `http://uname:pwd@abc.com/eureka/,http://uname:pwd@bcd.com/eureka/,http://uname:pwd@cde.com/eureka/`

## 2. Suggestion

```
eureka:
  client:
    serviceUrl:
      defaultZone: ${ZONE}
      username: uname
      password: password
```

`ZONE` -> `http://abc.com/eureka/,http://bcd.com/eureka/,http://cde.com/eureka`

It will be very helpful if I can make username & password stay in the `.yml` configuration, or I'll have to pass them from env `ZONE`. Is this feature suggestion viable?
