### ISSUE TITLE
Inconsistent registration IP in Eureka using docker swarm.

### ISSUE THREAD

**Issue by kimjuny** [spring-cloud/spring-cloud-netflix#2324]
I have `docker service create` a bunch of Eureka clients, but their IP type is inconsistent, sometimes it's containerId and sometimes it's numeric IP address.

![screenshot](https://imgur.com/4KaX6ni.jpg)

And the numeric IP address - I don't really know where they are from - doesn't belong to my public or private  IP address. I suppose numeric address comes from overlay network or docker inside.

Has anyone encountered the same problem like me?

Here are my eureka client config snippets.

```
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS}

spring:
  application:
    name: api
  redis:
    host: ${server.remote}
    port: 6379
  boot:
    admin:
      url: ${ADMIN_ADDRESS}
      username: ${security.admin.name}
      password: ${security.admin.password}
      client:
        metadata:
          user:
            name: ${security.admin.name}
            password: ${security.admin.password}
```

<b>Supplement</b>

I used `docker stack deploy` to deploy my Eureka server (2 instance aware of each other).

I used `docker service create` to deploy my Eureka client (STOCK-SERVICE) and feign consumer (API).

All of my instances (server、client、consumer) are all under same overlay network.

**Comment by doernbrackandre** [comment]
Hi @kimjuny,

have you tried this?
```
eureka:
  instance:
    preferIpAddress: true
```

This sets the IP as hostname which is, at leased from what I've had learned, a good idea in docker environments.

**Comment by kimjuny** [comment]
@doernbrackandre Hi, I've just tried setting `preferIpAddress: true`, still no luck. I have added some supplement to my question.

**Comment by kimjuny** [comment]
Check this out, this fixes my problem.

```
spring:
  cloud:
    inetutils:
      ignored-interfaces:
        - eth0
        - eth1
        - eth2
        - eth3
        - lo
```

Set this to my service-provider and service-consumer configurations, and now they are all using IP address rather than `container-id`.
