### ISSUE TITLE
Hystrix properties not working

### ISSUE THREAD

**Issue by christianf2029** [spring-cloud/spring-cloud-netflix#2325]
I have a similar error to [issue 2230](https://github.com/spring-cloud/spring-cloud-netflix/issues/2230) using Spring Cloud Dalston.SR3 and Spring Boot 1.5.7 versions. I have the following hystrix dependency corresponding to this version in my gateway using ZuulProxy:

```
<dependency>
         <groupId>org.springframework.cloud</groupId>
         <artifactId>spring-cloud-starter-hystrix</artifactId>
</dependency>
```
The only hystrix properties available in my `application.yml` are:

```
hystrix:
   metrics:
     enabled: foo
     polling-interval-ms: foo
```

I wanted to set the isolation metrics beyond the default of 1000ms, for example:
`hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 15000`

But it does not work, it does not recognize these commands -- neither my jar, nor the STS. When I check the `/health`, I only get a response without the set properties:
```
{
     ... ,
    "hystrix": {"status": "UP"} 
}
```
  What to do?

**Comment by spencergibb** [comment]
The ide won't recognize Hystrix properties at all

**Comment by christianf2029** [comment]
Do not recognize? Even if so, the set properties have no effect.

**Comment by spencergibb** [comment]
There is no metadata about them since they come from a 3rd party jar

**Comment by christianf2029** [comment]
How so? In several places, I have seen these settings defined through properties ...

**Comment by spencergibb** [comment]
Having them be valid for an application and completable by the ide are two very different things

**Comment by christianf2029** [comment]
Okay, but I created this component in main class, still in ZuulProxy, as seen in the documentation:

```
    @Component
    public class Teste {

        @HystrixCommand(groupKey = "Service",
                commandProperties = {
                @HystrixProperty(name = "execution.isolation.thread.timeoutInMilliseconds", value = "6000") })
        public String readingMockService() {
            System.out.println("asdpasdpokspoka");
            URI uri = URI
                    .create("https://localhost:8075/any/cached");
            return new RestTemplate().getForObject(uri, String.class);
        }

        public String reliableMock() {
            return "eae";
        }
    }
```

**Comment by christianf2029** [comment]
This [properties](https://github.com/Netflix/Hystrix/wiki/Configuration#circuitBreaker.enabled), for example, not work. It's not that I want the IDE to be completable, I just want them working.

**Comment by spencergibb** [comment]
Can you explain what "But it does not work, it does not recognize these commands" means?

**Comment by christianf2029** [comment]
Well, I have some services that are being closed by the circuit breaker because of the timeout, which means they are delaying more than one second (default timeout), which would be normal for them (their functionality) and is closed (which I not want). I have tried some properties I see in some examples, documentation to solve this problem, like the following:

- Routes in Zuul Proxy Server:
```
zuul:
  routes:
    AnyService:
      path: /any/**
      sensitive-headers: Set-Cookie, Authorization
   ...
```
- Properties that I have tried to disable the timeout checking and did not work:
```
hystrix:
    command:
        AnyService:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 15000
            circuitBreaker:
                ...
            metrics:
                ...
```
I get this error:
`Caused by: com.netflix.hystrix.exception.HystrixRuntimeException: StilingueUrlFetchService timed-out and no fallback available.`

- Property for disable the circuit breaker that I tried last case (that also did not work):
`hystrix.command.default.circuitBreaker.enabled: false`

So I even tried to set these properties via java code and I also could not make things work, I'm new to Spring Cloud. I need a way forward, I need to deliver this functionality that is being a barrier in our development. Some idea for I debug this problem?
