### ISSUE TITLE
Zuul routing - strip prefix problem

### ISSUE THREAD

**Issue by aivans** [spring-cloud/spring-cloud-netflix#235]
I am trying to setup an api gateway routing example.

```
zuul:
  ignored-services: "*"
  prefix: /api
  strip-prefix: true
  routes:
    stores:
      path: /stores/**
```

From my understanding the prefix is "/api" and this string only should be subtracted from the downstream path, so the call to stores service should have the path "..:8081/stores".

Routes look like:

```
{

    "/api/stores/**": "stores",
    "/api/customers/**": "customers"

}
```

Mappings:

```
"/api/stores/**": {

    "bean": "zuulHandlerMapping"

},
```

**Comment by dsyer** [comment]
So what are you actually seeing in practice? 

P.S. please use fencing (or any Markdown trick you like) to surround code and console output.

**Comment by aivans** [comment]
Hi Dave,
Sorry for the markdown.

I am a bit lost. I tried this combination:
```
zuul:
  ignored-services: "*"
  prefix: /api
  strip-prefix: false
  routes:
    stores:
      path: /stores/**
```
Request url: http://localhost:8765/api/stores
Downstream request from Zuul to Stores is:  http://localhost:8081/api

Honestly I expected that the downstream request url to be: http://localhost:8081/stores.

**Comment by dsyer** [comment]
If the homepage for stores is "http://localhost:8081/" I would expect the downstream request to be "http://localhost:8081/api" (both prefixes are stripped by default, but you switched off the global prefix stripping). If you want it to be "http://localhost:8081/store" you would need

```
zuul:
  prefix: /api
  routes:
    stores:
      path: /stores/**
      strip-prefix: false
```
