### ISSUE TITLE
External location headers should not be re-written

### ISSUE THREAD

**Issue by Anthares** [spring-cloud/spring-cloud-netflix#2365]
Hi,

We've an application based on spring-cloud-netflix and Zuul which allows us to proxy a legacy app while progressively migrating it to a microservices architecture.

Our zuul configuration looks like the following :
```yml
zuul:
  routes:
    some-service:
      path: /api/some/**
      service-id: some-service
      strip-prefix: true
      sensitive-headers:
    other-service:
      path: /api/other/**
      service-id: other-service
      strip-prefix: true
      sensitive-headers:
    api:
      path: /api/**
      service-id: api
      strip-prefix: true
      sensitive-headers:
    web:
      path: /**
      service-id: web
      strip-prefix: false
      sensitive-headers:
```

Since we are still using `spring-cloud-starter-zuul:1.3.5`, I ported `LocationRewriteFilter` introduced by PR #1863 in `1.4.0.M1` into our zuul app.

But our legacy app sometimes needs to redirect users to external sites, which doesn't work any more since `LocationRewriteFilter` rewrites host as well.
Because our `web` route matches everything, external redirects are matched against it and rewritten as well.

Maybe `LocationRewriteFilter` should avoid rewriting location header when location header's URI targets a different host than the original URI ?
If not, it might be useful to be able to configure it.

I'm aware this use case might be edgy, but I wanted to bring your attention on it.

Thanks in advance.

Regards.
