### ISSUE TITLE
Zuul - hierarchical specification for routes

### ISSUE THREAD

**Issue by aivans** [spring-cloud/spring-cloud-netflix#237]
Hi,

I would be nice to configure routes in a hierarchical way:
```
/api
    /v1
         /route1
         /route2
   /v2
        /route1
        /route2
```

So far it is possible to specify just the top level prefix /api

**Comment by dsyer** [comment]
You can, of course, do that already with

```
zuul:
  routes:
     v1route1: /v1/route1/**
     v1route2: /v1/route2/**
     v2route1: /v2/route1/**
     v2route1: /v2/route2/**
```

If you can make a proposal for the YAML format of your "hierarchical" model, we can have a sensible discussion about how it might be implemented.
