### ISSUE TITLE
Read Timeout/ Socket timeout in Zuul

### ISSUE THREAD

**Issue by mirak94** [spring-cloud/spring-cloud-netflix#2379]
I've read some issues while researching for the problem of `java.net.SocketTimeoutException: Read timed out` but all of them are saying the proposed solutions, which are the following: if you are using ribbon so increase the `ribbon.Readtimeout` and if you are using zuul routes so increase `zuul.host.socket-timeout-millis`.
I am using zuul routes and I am getting the above exception, but I am seeing that the default value for `zuul.host.socket-timeout-millis` is `10000`, and this is enough I guess.
I can't figure out what may be causing the problem, my internal services are not taking more than 10 seconds for example to send data.
I need help in identifying the possible causes for this problem, because I guess just going and increase the socket timeout is not the solution.
I also need also some insights about the problems that may occur as result of high socket timeout, and when should I say that socket timeout of `x` mills is considered high, and `y` is considered low.
Actually I need somehow to be able to define the parameters that I should take in consideration when I see this problem (Read timed out).

Thanks!

**Comment by ryanjbaxter** [comment]
Can you tell us what version of Spring Cloud you are using and how you are configuring your Zuul routes?

**Comment by tmelhiser** [comment]
We are seeing this same behavior, using Edgware.RELEASE.

Zuul is 1.4.0, using Ribbon 2.2.4, with Eureka Client 1.7.0.

Ribbon is dynamically populating the routes via Eureka Discovery.  The discovery and population of the routes works perfectly.  However on the first run against the routes, we receive a SocketTimeoutException.

Eventually, subsequent runs are successful, but the initial few requests fail.

I have tried these settings inside the zuul spring-boot application.yml , but the timeout does not seem to change:
```yml
zuul:
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
    max-total-connections: 200
    max-per-route-connections: 20
    time-unit: MILLISECONDS
    time-to-live: 10000
    
ribbon:
  eureka:
    enable: true
  isSecure: false
  readTimeout: 60000
  connectTimeout: 60000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
```
