### ISSUE TITLE
about eureka replication configuration?

### ISSUE THREAD

**Issue by jmbkeyes** [spring-cloud/spring-cloud-netflix#2413]
it works as excepted with the following yml config.
```
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/
```
But the replication does not work as expected with the following config.
```
eureka:
  instance:
    hostname: peer2
  client:
     service-url:
     default-zone: http://peer1:8761/eureka/
```
The main differences are "serviceUrl" and "service-url",  "defaultZone" and "default-zone".
So shall I always use the first yml config for replication?

**Comment by spencergibb** [comment]
service url is a map, so the keys inside of it (`defaultZone`) are case sensitive.

**Comment by jmbkeyes** [comment]
but eureka client can successfully register to server with the following yml config  
```
eureka:
  client:
     service-url:
     default-zone: http://peer1:8761/eureka/
```
