### ISSUE TITLE
Netflix - configure number of retries and retry timeout interval.

### ISSUE THREAD

**Issue by Tsvetoslav88** [spring-cloud/spring-cloud-netflix#2418]
I need to " configure number of retries and retry timeout interval." when the Server application is down. I'm using this dependency:
```
<dependency>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-starter-hystrix</artifactId>
</dependency>
```

Here is my restTemplate method:

```
    @LoadBalanced
    @Bean
    RestTemplate restTemplate() {
        ResourceOwnerPasswordResourceDetails passwordCredentials = new ResourceOwnerPasswordResourceDetails();
        passwordCredentials.setClientId( "***" );
        passwordCredentials.setClientSecret( "ignored" );
        passwordCredentials.setGrantType( "password" );
        passwordCredentials.setAccessTokenUri("tocken" );
        passwordCredentials.setUsername( username );
        passwordCredentials.setPassword( password );
        OAuth2RestTemplate rt = new OAuth2RestTemplate( passwordCredentials, clientContext );
        rt.setRequestFactory( new HttpComponentsClientHttpRequestFactory() );
        return rt;
    }

```
Here is how I call it:
        `String runtimeModel = restTemplate().exchange( URL, HttpMethod.GET, null, String.class ).getBody();`

I've tried with something like this: https://github.com/spring-cloud/spring-cloud-netflix/issues/1577 but it's not working 

Thanks!

**Comment by holy12345** [comment]
@Tsvetoslav88 Hello, i would like to use ribbon with spring-retry to solve retry :)

**Comment by Tsvetoslav88** [comment]
@holy12345 
Is it enough to set this in "bootstrap.yml" or I need to add something more:
spring:
  cloud: 
    loadbalancer:
      retry: 
        enabled: true
client:
  ribbon:
    MaxAutoRetries: 3
    MaxAutoRetriesNextServer: 3
    OkToRetryOnAllOperations: true

Thanks! :)

**Comment by holy12345** [comment]
@Tsvetoslav88 
In the source code ribbon set retry the content as follows
public class RibbonAutoConfiguration {
	@Bean
	@ConditionalOnClass(name = "org.springframework.retry.support.RetryTemplate")
	@ConditionalOnMissingBean
	public LoadBalancedRetryPolicyFactory loadBalancedRetryPolicyFactory(SpringClientFactory clientFactory) {
		return new RibbonLoadBalancedRetryPolicyFactory(clientFactory);
	}
}
So in addition to the configuration file you give, you should add spring-retry pom like this
<dependency>
    <groupId>org.springframework.retry</groupId>
    <artifactId>spring-retry</artifactId>
    <version>1.1.2.RELEASE</version>
</dependency>
This is what I think, please try it. Hope to help you！ ：）

**Comment by Tsvetoslav88** [comment]
I added in my pom.xml file:
```
<dependency>
	<groupId>org.springframework.retry</groupId>
	<artifactId>spring-retry</artifactId>
</dependency>
```

Also here is me bootstrap.yml file:
```
cloud:
    loadbalancer:
      retry: 
        enabled: true
    bus:
      enabled: false
    discovery:
      enabled: false   
    consul:
      enabled: false
      host: localhost
      port: 8500   
      discovery:
        instanceId: ${spring.application.name}:${instanceId}
        healthCheckPath: ${server.contextPath}/health
        healthCheckInterval: 15s
client:
  ribbon:
    MaxAutoRetries: 3
    MaxAutoRetriesNextServer: 3
    OkToRetryOnAllOperations: true
```
Here are the annotations on the top of my service method which calls RestTemplate:
```
@HystrixCommand( commandProperties = { @HystrixProperty( name = "execution.isolation.strategy", value = "SEMAPHORE" ),
        @HystrixProperty( name = "execution.isolation.semaphore.maxConcurrentRequests", value = "100" ),
        @HystrixProperty( name = "execution.isolation.thread.timeoutInMilliseconds", value = "2000" ) } )
```
But I hit the same error:

> SEVERE: Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.reflect.UndeclaredThrowableException] with root cause
> java.util.concurrent.TimeoutException
> 	at com.netflix.hystrix.AbstractCommand.handleTimeoutViaFallback(AbstractCommand.java:980)
