### ISSUE TITLE
Zuul and Static Resources

### ISSUE THREAD

**Issue by ccit-spence** [spring-cloud/spring-cloud-netflix#249]
First: My goal is to have Zuul frontend all components of Spring Cloud.  i.e. Eureka, Hystrix, others.  I am finding that I can't get static resources to route properly.  They show 404's in the browser.  

Eureka example: 

Access URL from Zuul: `http://hostname/discovery/` this returns the page without any of the static resources.

In the browser it shows trying to get `http://hostname/eureka/css/wro.css` results in a 404.

The static resource is located @ `http://hostname/discovery/eureka/css/wro.css`

I have tried the following Zuul route configs:

No route config, just using default.

and

```
zuul:
    routes:
        discovery:
            path: /discovery/**
            stripPrefix: true
```

and

```
zuul:
    routes:
        discovery:
            path: /discovery/**
            stripPrefix: false
```

This same error happens with other Spring based applications such as VanRoy's `spring-cloud-dashboard`.

I did add a HAL browser to a different service and used a static folder under resources "using default static resource mapping behavior of Spring Boot" and that works properly.
