### ISSUE TITLE
Zuul not forwarding client certificate to backend service

### ISSUE THREAD

**Issue by qcastel** [spring-cloud/spring-cloud-netflix#2498]
Hello!

We noticed that our zuul application is not forwarding the client certificate to the backend service.

For the moment, the closest answer I found related to that problem is a question from Andrew Serff which is unfortunately unanswered.

Our configuration of Zuul is pretty basic:

```
zuul:
  sensitiveHeaders: Set-Cookie
  routes:
    rs-api:
      path: /rs-api/**
      serviceId: rs-api

ribbon:
  eureka:
    enabled: true

eureka:
  client:
    registerWithEureka: false

server:
    hostname: XXX
    port: 8089
    ssl:
        enabled: true
        key-alias: "XXX"
        clientAuth: want
```

```
@SpringBootApplication
@EnableZuulProxy
@EnableEurekaClient
@RestController
public class ZuulServerApplication {

    public static void main(String[] args) {
        new SpringApplicationBuilder(ZuulServerApplication.class).web(true).run(args);
    }
}
```

Let me know if you need more information from me. I'm looking at how I can do that using a custom filter at the moment.

Thanks!
