### ISSUE TITLE
Modifying server names during RibbonRoutingFilter in zuul

### ISSUE THREAD

**Issue by mirak94** [spring-cloud/spring-cloud-netflix#2508]
I am using zuul as a reverse proxy for my requests and using ribbon for identifying backend servers as follows:

```
zuul:
  routes:   
    service-a:
      path: api/service-a/etc
      stripPrefix: false
      serviceId: service-a
sevice-a:
   ribbon:
    listOfServers: http://server_a.com
```
Now service-a's server/host is identified at routing layer (during the `RibbonRoutingFilter`), and I would like to modify `http://server_a.com` after being identified by ribbon, like adding a prefix (based on a service that runs for every request and tells this prefix for each request).
I can't find a way to catch the host name after being identified by the `RibbonRoutingFilter` to modify it.
Any help is greatly appreciated!
Thanks

**Comment by ryanjbaxter** [comment]
You should be able to extend `RibbonRoutingFilter` and override the `buildCommandContext` method to create the `uri` that you need.  You should be able to make this an `@Primary` bean in a configuration class.  Doesnt look like there is a conditional on that bean in `ZuulProxyAutoConfiguration`.  https://github.com/spring-cloud/spring-cloud-netflix/blob/ef755f3ad3b938c2cddea0d18a3cd7e731c88a82/spring-cloud-netflix-zuul/src/main/java/org/springframework/cloud/netflix/zuul/filters/route/RibbonRoutingFilter.java#L124

**Comment by mirak94** [comment]
Thanks @ryanjbaxter for replying!
But I don't want to modify the `uri`, I would like to modify the server name (which is `http://server_a.com` above) after being identified by ribbon to `http://prefix_a_server_a.com` for example, based on some service that runs for every request.
For example if I have a request as follows: GET - `http://server_a.com/user/{userId}` --> after service runs request should be GET - `http://prefix_a_server_a.com/user/{userId}`.

**Comment by ryanjbaxter** [comment]
Not following, that seems like you are modifying the URL to me.

**Comment by mirak94** [comment]
Okay we can say Yes we are modifying the `URL`, but only the part before the `uri` (because url = host + uri) --> I'm modifying only the host.
If not using ribbon, I will have something like this:
```
zuul:
  routes:   
    service-a:
      path: api/service-a/etc
      url: http://server_a.com
      stripPrefix: false
```
This gives me the capability to override the `routeHost` in `RequestContext` to `http://prefix_a_server_a.com`, but because I want to customize timeouts per requests, I have to use ribbon instead.
Let me know if something is not clear yet so that I can explain further.

Thank you very much
