### ISSUE TITLE
Eureka configuration inconsistence between Dalston.SR4 and Edgware

### ISSUE THREAD

**Issue by Ziemowit** [spring-cloud/spring-cloud-netflix#2525]
Using:
a) spring-boot => 1.5.4
b) spring-cloud => Dalston.SR4

and having following configuration:
```
server:
  port: 8765
eureka:
  instance:
    nonSecurePortEnabled: false
    securePortEnabled: true
    ....
```
The result is following (after checking registered apps on eureka server)
```
<port enabled="false">8765</port>
<securePort enabled="true">443</securePort>
```

But using:
a) spring-boot => 1.5.9
b) spring-cloud => Edgeware.RELEASE

and **the same configuration** the result  is following

```
<port enabled="false">8765</port>
<securePort enabled="true">8765</securePort>
```
So secure/not-secure ports are the same.

Shouldn't in 2nd case the **securePort** be still 443?

Seems like an inconsistence with previous versions.
