### ISSUE TITLE
DiscoveryEnabledNIWSServerList Load balancer does not have available server for client: XXX

### ISSUE THREAD

**Issue by xiezhaofeng** [spring-cloud/spring-cloud-netflix#2531]
eureka-provider)application.xml

```
server:
  port: 8800/8801
spring:
  application:
    name: eureka-provider
eureka:
  instance:
    virtualHostName: eureka-provider-vip
    preferIpAddress: true
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    statusPageUrlPath: ${management.context-path:}/info
    healthCheckUrlPath: ${management.context-path:}/health
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

```

eureka-provider)controller

```
@RestController
@RequestMapping("/user")
public class UserController {
    @RequestMapping("/hello/{fallback}")
    @HystrixCommand(fallbackMethod="helloFallbackMethod")
    public String hello(@PathVariable("fallback") String fallback){
        LOGGER.info("execute method hello, fallback: {}", fallback);
        if("1".equals(fallback)){
            throw new RuntimeException("...");
        }
        return "hello";
    }

    public String helloFallbackMethod(String fallback){
        return "fallback :"+fallback;
    }
}
```

eureka-provider)application

```
@SpringBootApplication
@EnableEurekaClient
@EnableHystrix
public class ProviderApplication {

	public static void main(String[] args) {
		SpringApplication.run(ProviderApplication.class, args);
	}
}
```

 eureka-server)application.xml

```
 server:
  application:
    name: eureka-server
  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
zuul:
  routes:
    eureka-provider:
      path: /usersystem/**
      serviceId: eureka-provider
ribbon:
  eureka:
    enabled: false
eureka-provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule
    NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
    UseIPAddrForServer: true
    DeploymentContextBasedVipAddresses: eureka-provider-vip
#    listOfServers: 127.0.0.1:8800, 127.0.0.1:8801

```

eureka-server)application
```
@SpringBootApplication
@EnableEurekaServer
@EnableZuulProxy
public class EurekaServerApplication {

	public static void main(String[] args) {
		SpringApplication.run(EurekaServerApplication.class, args);
	}
}
```

demo1)
use: `listOfServers: 127.0.0.1:8800, 127.0.0.1:8801` 
url:http://localhost:8761/usersystem/user/hello/2
return:success

demo2)
use:`NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList`
url:http://localhost:8761/usersystem/user/hello/2
return: Internal Server Error
server: Load balancer does not have available server for client: eureka-provider

 need help?
