### ISSUE TITLE
can't fetch service from zuul in docker

### ISSUE THREAD

**Issue by jomalonejia** [spring-cloud/spring-cloud-netflix#2546]
i have a simple spring cloud project,and it contains 4 services:

- config:8888

- registry(eureka):8761

- gateway(zuul):8080

- service-1:9527

the project has no problem if deployed in localhost,

i can successfully fetch service-1's api by zuul without 

> http://localhost:8080/service-1/test

but when i deployed with docker, it throws error: 

`Caused by: java.lang.RuntimeException: org.apache.http.conn.HttpHostConnectException: Connect to registry:9527 [registry/172.21.0.4] failed: Connection refused (Connection refused)`

i can only fetch with service-1's api

> http://localhost:9527/test

PS: the two services(gateway,service-1) has been success registry to eureka

here is my docker-compose yml :

```
version: '3'
services:
  config:
    build: ./config
    ports:
      - "8888:8888"
  registry:
    build: ./registry
    ports:
      - "8761:8761"
    depends_on:
      - config
    environment:
      - SPRING_PROFILES_ACTIVE=prd
  gateway:
    build: ./gateway
    depends_on:
      - config
    links:
      - registry
      - service-1
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prd
  service-1:
    build: ./service-1
    ports:
      - "9527:9527"
    depends_on:
      - config
    links:
      - registry
    environment:
      - SPRING_PROFILES_ACTIVE=prd
```
 
can i can solved the error  , thanks!
