### ISSUE TITLE
Hystrix stream treat ribbon timeouts like failures

### ISSUE THREAD

**Issue by rphlmr** [spring-cloud/spring-cloud-netflix#2648]
When using ribbon timeout instead of hystrix timeout (hystrix timeout > (ribbon ReadTimeout + ReadTimeout) x MaxAutoRetries x MaxAutoRetriesNextServer) with a `FeignClient`, in case of timeout, hystrix.stream (and dashboard) treat these timeouts like failures.

Using the given configuration to reproduce : 
```
feign:
  okhttp.enabled: true
  hystrix.enabled: true

ribbon:
  OkToRetryOnAllOperations: true
  ConnectTimeout: 500
  ReadTimeout: 800
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0

hystrix:
  metrics:
    enabled: true
  command:
    default:
      execution:
        timeout.enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 500
          strategy: THREAD
```

If I set no ribbon config and use only hystrix timeout, hystrix.stream treat timeouts like timeouts.

This is a screenshot of hystrix dashbord and console output : 

![ribbon_timeout_like_failures-min](https://user-images.githubusercontent.com/20722140/34919998-f222c89c-f96b-11e7-9aaf-fbc89c451957.PNG)

Logger from fallbackFactory clearly says it's timeout.

Hope it helps

([demo project can be found here](https://github.com/rphlmr/spring-cloud-netflix-contrib/tree/master/hystrix/routeplanner-api))
