### ISSUE TITLE
when i used zookeeper discoveryclient,but the turbine's stream not data  

### ISSUE THREAD

**Issue by 1991wangliang** [spring-cloud/spring-cloud-netflix#2691]
my turbine application.
![image](https://user-images.githubusercontent.com/5245347/35470967-a882465a-038d-11e8-9c11-04faf01de3a8.png)

appliaction.properties

```
server.port=19090
spring.application.name=turbine
#turbine.appConfig=discovery-zookeeper-client
#turbine.aggregator.clusterConfig= MAIN
#turbine.ConfigPropertyBasedDiscovery.MAIN.instances=127.0.0.1,192.168.2.103

spring.cloud.zookeeper.connect-string=192.168.2.210:2181

```

application.yml 

```
#turbine:
#  aggregator:
#    clusterConfig: MAIN
#    #http://localhost:8095/turbine.stream?cluster=POLICY-SERVICE
#  appConfig: discovery-zookeeper-client


turbine:
  aggregator:
#    clusterConfig: http://127.0.0.1:8081/hystrix.stream
  appConfig: discovery-zookeeper-client
#  clusterNameExpression: metadata['cluster']
```

my discovery-zookeeper-client application 

````
spring.application.name=discovery-zookeeper-client
server.port=8081

feign.hystrix.enabled=true
spring.cloud.zookeeper.connect-string=192.168.2.210:2181


spring.zipkin.base-url=http://localhost:9411
````

![image](https://user-images.githubusercontent.com/5245347/35470980-ed0976b8-038d-11e8-9215-b3739d85378a.png)

zookeeper can't support turbine ? ? on eureka was ok.
