### ISSUE TITLE
ignoredPatterns not applied when servlet-path is set to /

### ISSUE THREAD

**Issue by szpigielm** [spring-cloud/spring-cloud-netflix#2695]
Hi,

My application uses servlet-path set to "/", so servlet can handle large files. However, we would like to prevent some of the paths from being proxied so we are using "ignoredPatterns" config which is not being applied. The configuration we are using is:

```
server:
  port: 8080
zuul:
  ignoredPatterns: /version, /health
  routes:
    serviceA:
      path: /**
      url: http://localhost:8888
      sensitiveHeaders:
      stripPrefix: false
  servlet-path: /
```

**Comment by ryanjbaxter** [comment]
Did you mean to say they are not being ignored?

**Comment by szpigielm** [comment]
Yes as in /version is proxied to the serviceA but should be ignored

**Comment by spencergibb** [comment]
What is the full request that is being matched, since `ignoredPatterns` is a regex. Also set `logging.level.org.springframework.cloud.netflix.zuul.filters=DEBUG` and provide the information from that logger.

**Comment by szpigielm** [comment]
Hi, I created repo [here](https://github.com/szpigielm/zuul-bug) to demonstrate the issue. The zuul gateway has an endpoint `/version` as well there is only one route to another service which is mapped to `/**`. Because `/version` is covered by this same regex as `/**` and I don't want `/version` to be proxied to any other service, only to be served by zuul so I used `zuul:
  ignoredPatterns: /version`. This works as expected with default servlet and when I call `/version` zuul serves me correct response. As soon as I add `servlet-path: /` to redirect all traffic through ZuulServlet and I call `/version` zuul returns 200 with no body and the logs `WARN 6704 --- [o-auto-1-exec-1] o.s.c.n.z.f.pre.PreDecorationFilter      : No route found for uri: /version`. I created 2 tests with and without `servlet-path: /` to show this behavior.

**Comment by spencergibb** [comment]
I see. If you set the zuul servlet to `/**` you've effectively removed the spring dispatcher servlet, which is what hosts `/version`.

**Comment by szpigielm** [comment]
I see... still it feels like this should work :). I found a workaround to this problem by creating a route to itself.
```
zuul:
  routes:
    serviceA:
      path: /**
      url: http://localhost:8888
      sensitiveHeaders:
      stripPrefix: false
    version:
      path: /version
      url: http://localhost:8888/version
      sensitiveHeaders:
      stripPrefix: false
  servlet-path: /
```

Is there any other downside of using the ZuulServlet vs spring DispatcherServlet like for example would spring security work with it? I only had to use it because we needed to handle large files and we didn't want to have different endpoints with default prefix `/zuul`
