### ISSUE TITLE
Ribbon not loading a list of servers during spring boot startup or initialisation

### ISSUE THREAD

**Issue by RohitGupta31** [spring-cloud/spring-cloud-netflix#2705]
Bug:

I want to use the listofservers which are defined in a configuration file during spring boot startup (i.e. in a @Postconstruct annotation) to connect to an aws s3 instance.
```
  ribbon:
    listOfServers: localhost:8080
    ServerListRefreshInterval: 15000
```
Eureka is disabled.

This is being set using the
``` 
@RibbonClient(name = "test", configuration = TestConfiguration.class).
```
Am autowiring the loadbalacer client
```
    @Autowired
    private LoadBalancerClient loadBalancer;
```
```
eg: @PostConstruct
loadBalancer.choose("test").getUri().toString()
```
& loading the servers in a config file as 
```
   @Bean
    public ServerList<Server> ribbonServerList(IClientConfig config) {
        ConfigurationBasedServerList serverList = new ConfigurationBasedServerList();
        serverList.initWithNiwsConfig(config);
        return serverList;
    }.
```
But the list of servers during initialization is always empty, so i get back an exception that riboon client cannot find the list of servers during springboot startup.
```
: No up servers available from load balancer: DynamicServerListLoadBalancer:{NFLoadBalancer:name=s3,current list of Servers=[],Load balancer stats=Zone stats: {},Server stats: []}ServerList:com.netflix.loadbalancer.ConfigurationBasedServerList@3efedc6f
WARN 19548 --- [main] c.netflix.loadbalancer.BaseLoadBalancer  : LoadBalancer [s3]:  Error choosing server for key default
```
even though the serverList is defined in the application.yml file, if i don't read the serverList from @postcontruct annotation it is working fine.

I looked up online but could not find examples of using this in a @postcontruct annotation, but i need this to be used there is there any other alternative?

**Comment by RohitGupta31** [comment]
[user.zip](https://github.com/spring-cloud/spring-cloud-netflix/files/1689489/user.zip)

**Comment by RohitGupta31** [comment]
Attached a test project with which the issue is reproducible

**Comment by ryanjbaxter** [comment]
Please learn how to [format code on GitHub](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

I would imagine that your `@PostConstruct` code is running before Ribbon is fully initialized.  I am not sure what we could do about that.

**Comment by RohitGupta31** [comment]
Ok.

Yep you are right, but the loadbalancerclient is autowired so I thought the server list to be set before we use it in @PostContruct, we would need the list of servers to be used during initialisation as there are calls to be made to S3 server to create a bucket.

Do you reckon  this as a bug otherwise is there an alternative. Appreciate your reply.

**Comment by spencergibb** [comment]
We've generally not recommended using ribbon during initialization phases. This may help: http://cloud.spring.io/spring-cloud-static/Edgware.SR1/single/spring-cloud.html#ribbon-child-context-eager-load

**Comment by RohitGupta31** [comment]
Thanks, that property doesn't seem to have any effect, still getting the same error. I have added that to yaml file as follows. 

say-hello:
  ribbon:
    eureka:
      enabled: false
    eager-load:
      enabled: true
      clients: localhost:8090,localhost:9092,localhost:9999
    listOfServers: localhost:8090,localhost:9092,localhost:9999
    ServerListRefreshInterval: 15000

Is that the correct way?

**Comment by spencergibb** [comment]
no, clients is the ribbon client name. In your case `say-hello`.

**Comment by RohitGupta31** [comment]
oops unfortunately even that doesn't seem to have any effect. Getting the same error.
[user.zip](https://github.com/spring-cloud/spring-cloud-netflix/files/1690906/user.zip)


```
say-hello:
  ribbon:
    eureka:
      enabled: false
    eager-load:
      enabled: true
      clients: say-hello
    listOfServers: localhost:8090,localhost:9092,localhost:9999
    ServerListRefreshInterval: 15000
```

**Comment by spencergibb** [comment]
eager-load can't be under `say-hello:`. It needs to be:
```
ribbon:
  eureka:
     enabled: false
  eager-load:
    enabled: true
    clients: say-hello
say-hello:
  ribbon:
    listOfServers: localhost:8090,localhost:9092,localhost:9999
    ServerListRefreshInterval: 15000
```

**Comment by RohitGupta31** [comment]
Still no luck tho. Getting the same error in the startup log I noticed that ribbon.eager-load property is matched.

   RibbonAutoConfiguration#ribbonApplicationContextInitializer matched:
      - @ConditionalOnProperty (ribbon.eager-load.enabled) matched (OnPropertyCondition)

**Comment by spencergibb** [comment]
Not sure what else to say:
> We've generally not recommended using ribbon during initialization phases.

**Comment by RohitGupta31** [comment]
Just wondering if adding ribbon.eager-load.enabled property does not list the servers during startup, could this be a bug?

**Comment by spencergibb** [comment]
@RohitGupta31 only if you provide a minimal project that recreates the problem.

**Comment by ArtemZubenko** [comment]
Hi Rohit, 
Try deleting 
  @Bean
    public IRule ribbonRule(IClientConfig config) {
        return new AvailabilityFilteringRule();
    }
from your SayHelloConfiguration.java

**Comment by anhtuanluu36** [comment]
@spencergibb I have the same issue like @RohitGupta31. I added the following lines in application.yaml:
```
ribbon:
  eager-load:
    enabled: true
    clients: merchant-security
  eureka:
    enabled: false
merchant-security:
  ribbon:
    listOfServers: localhost:8081, localhost:8082
    ServerListRefreshInterval: 15000
```
I used @FeignClient:
`@FeignClient(name = "merchantSecurityPermissionClient", serviceId = "merchant-security")`

In the method "public void configure(HttpSecurity http) throws Exception" of the Configuration class (this class extends ResourceServerConfigurerAdapter.java). I called @FeignClient and it return an error:
`Caused by: com.netflix.client.ClientException: Load balancer does not have available server for client: merchant-security`

However, after Spring Boot StartUp, I call @FeignClient again and it works fine.
