### ISSUE TITLE
Fallback being called by hystrix even when services are taking more time to respond

### ISSUE THREAD

**Issue by bsushant-athena** [spring-cloud/spring-cloud-netflix#2719]
I've added ZuulFallbackProvider(in my api-gateway) with below configuration. So now the problem we are seeing is that when services are taking more than 10 seconds to respond then they are seeing the fallback message(which we have added). But ideally it should be 504 http timeout request. 

To regenerate this one can simply try to create an app with an api which takes more than the hystrix timeout value and when you hit that through api-gateway(where fallback is implemented) you should see 503 with custom fallback message. 

Can someone look into this?

```
ribbon:
  ReadTimeout: 120000
  ServerListRefreshInterval: 5000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
      circuitBreaker:
        enabled:  true
        sleepWindowInMilliseconds: 5000
        errorThresholdPercentage: 50
      fallback:
        enabled:  true
```
