### ISSUE TITLE
How to dynamically ribbon.listOfserver from database

### ISSUE THREAD

**Issue by shengnian** [spring-cloud/spring-cloud-netflix#2736]
can i create this part:

```
 users:
  ribbon:
    listOfServers: example.com,google.com
```
dynamically in my source code? The listOfServers depends on database
and Add or delete `server host` dynamically without spring cloud config, without eureka? thanks.

**Comment by spencergibb** [comment]
No. What you would want to do is create a custom ribbon `ServerList`

**Comment by shengnian** [comment]
Thanks a lot @spencergibb !!

here it's code:
```

public class CustomServerList extends AbstractServerList<Server>  {

    @Autowired
    private ServerListRepository repository;

	private IClientConfig clientConfig;
		
	@Override
	public List<Server> getInitialListOfServers() {
	    return getUpdatedListOfServers();
	}

	@Override
	public List<Server> getUpdatedListOfServers() {
// get servers from database by clientName
        String ListOfServers = repository.findByClientName(this.clientConfig.getClientName());
        return derive(listOfServers);
	}

	@Override
	public void initWithNiwsConfig(IClientConfig clientConfig) {
	    this.clientConfig = clientConfig;
	}
	
	private List<Server> derive(String value) {
	    List<Server> list = Lists.newArrayList();
		if (!Strings.isNullOrEmpty(value)) {
			for (String s: value.split(",")) {
				list.add(new Server(s.trim()));
			}
		}
        return list;
	}
}
```

The `getUpdatedListOfServers` method to executed every thirty seconds (the default `PollingServerListUpdater` config) and the question is how to disable this task and 
 only triggered `ServerListUpdater.UpdateAction`  when the database servers list changes

**Comment by holy12345** [comment]
@shengnian 

In the `RibbonClientConfiguration `I found the following code：

```
@Bean
@ConditionalOnMissingBean
public ServerListUpdater ribbonServerListUpdater(IClientConfig config) {
	return new PollingServerListUpdater(config);
}
```
Perhaps we can customize the realization of `ServerListUpdater ` interface.

Hope this helps you, thanks

**Comment by shengnian** [comment]
@holy12345 thanks, i'll try.  i have another question how to disable  `AntPathMatcher ` use absolute path? 

```
zuul:
  routes:
    service-a:
      path: /service-a/Netflix/zuul -->   #  do not use /service-a/**
      url: https://github.com/Netflix/zuul
    service-b:
      path: /service-b/Netflix/zuul -->  # disable /service-b/**
      url: https://github.com/Netflix/zuul
```

and how to use Hystrix  without eureka, without ribbon, without feign.. or how to custom the hystrix command for httpclient? thanks!
