### ISSUE TITLE
spring cloud zuul support Placeholder?

### ISSUE THREAD

**Issue by ypg521** [spring-cloud/spring-cloud-netflix#2766]
Sorry for my bad Englist first.
spring cloud zuul support Placeholder???
Like this:
```yaml
zuul:
  routers:
    users:
      path:  /cities/{areaCode}/
      url: http://{areaCode}.google.com
```
