### ISSUE TITLE
[QUESTION] Proxying calls from Gateway to UI

### ISSUE THREAD

**Issue by ayulit** [spring-cloud/spring-cloud-netflix#2787]
I have a few Spring Cloud microservices with a Zuul gateway running on port 8080.

<pre>
   browser
      |
      |
    gateway   (:8080)
     /   \
    /     \
   /       \
resource   UI (:8090)
</pre>

There is a UI microservice on port 8090, which has a controller with a method inside, returning index.html.

I configured Zuul routing like this for UI (I'm using Eureka too):

```
zuul:
  routes:
    ui:
      path: /ui/**
      serviceId: myproject.service.ui
      stripPrefix: false
      sensitiveHeaders:
```
If I call `http://localhost:8080/ui/` everything works fine and I see rendering of my index.html.

Is it possible to configure Spring Cloud in some way to make the following flow work: calling `http://localhost:8080/` redirects us to controller of UI microservice, which returns index.html?

So the idea is to open UI from the root of my site.

Thanks in advance!

**Comment by ryanjbaxter** [comment]
I think you could do this simply if your UI service could be accessed at the root.  That way you could do something like this
```
zuul:
  routes:
    ui:
      path: /u
      serviceId: myproject.service.ui
      stripPrefix: false
```

Of course this depends on your UI as well.

If you can't access the UI at the root then you might have to get creative with using a zuul filter to rewrite the request.  

Also if you have not seen the [Spring Cloud Gateway](https://github.com/spring-cloud/spring-cloud-gateway) project yet you might want to look at that project as this use case could easily be solved with that project.
