### ISSUE TITLE
Auto detect applications provide hystrix stream to turbune

### ISSUE THREAD

**Issue by rnemykin** [spring-cloud/spring-cloud-netflix#2798]
Hi.
I want to aggregate my histryx stream via turbine. 
So i need to configure application, provided hystix stream and turbine application.

ok, for turbine we have a configuration smth like this
```
turbine:
  aggregator:
    clusterConfig: MYCLUSTER
  appConfig: app1
  clusterNameExpression: metadata['cluster'] 
```

so, application `app1` will have config like
```
spring.application.name=app1
spring.cloud.consul.discovery.tags=cluster=MYCLUSTER
```

if i have more than one applications like `app`: app2, app3, appN, i need to change `turbine` application config to
```
turbine:
  aggregator:
    clusterConfig: MYCLUSTER
  appConfig: app1,app2,app3,...appN
  clusterNameExpression: metadata['cluster'] 
```
it is very uncomfortable, because i don't know how many applications will provide hystrix stream.
why not automate this, for example
```
String turbineTag = StringUtils.substringBetween(turbineProperties.getClusterNameExpression(), "'", "'");
        String hystrixApplicationNames = discoveryClient.getServices().stream()
                .map(appId -> {
                    List<ServiceInstance> instances = discoveryClient.getInstances(appId);
                    return instances.stream().anyMatch(i -> turbineClusterName.equals(i.getMetadata().get(turbineTag))) ? appId : "";
                })
                .filter(StringUtils::isNotEmpty)
                .collect(Collectors.joining(","));
        turbineProperties.setAppConfig(hystrixApplicationNames);
```
where `turbineClusterName` is
```
@Value("${turbine.aggregator.clusterConfig}")
 private String turbineClusterName;
```

and don't set `turbine.appConfig`
