### ISSUE TITLE
zuul route config. Is It possible to add different prefix for each route or append the path as prefix?

### ISSUE THREAD

**Issue by biwugang** [spring-cloud/spring-cloud-netflix#2850]
using the following zuul config as example
```
zuul:
  ignored-services: "*"
  routes:
    a:
      path: /a/**
      serviceId: a_service
    b:
      path: /b/**
      serviceId: _service
```
the url /a/** will transfer to a_service with url /**
the url /b/** will transfer to b_service with url /**  

I want to pass /a/** to a_service and /b/** to b_service
Is it possible?
