### ISSUE TITLE
Ribbon ReadTimeout and ConnectTimeout not working

### ISSUE THREAD

**Issue by mfhfeon** [spring-cloud/spring-cloud-netflix#2857]
My Spring Cloud version is Edgware.SR3.My configuration is:
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 5000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1

I found that ReadTimeout and ConnectTimeout not working.What's the problem?

**Comment by mfhfeon** [comment]
Yes, I used feign.But ReadTimeout and ConnectTimeout not working.

**Comment by ryanjbaxter** [comment]
> We need more information. Perhaps attach the code as a git repo or zip.

**Comment by mfhfeon** [comment]
I tested repeatedly.They can work, but max value of ConnectTimeout is 2000.What's the problem?

**Comment by mfhfeon** [comment]
Here is my configuration
```
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 6000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule
```
