### ISSUE TITLE
DC/OS application registration in Eureka with wrong port number

### ISSUE THREAD

**Issue by Kirill-Bezugly** [spring-cloud/spring-cloud-netflix#2883]
Hello,
Could you help me to resolve the issue which possibly related to "Eureka configuration inconsistence between Dalston.SR4 and Edgware #2525".
I have the farm of Spring Boot Microservices run in Docker containers at the DC/OS platform. Microservices uses Eureka server for service discovery. The problem is following - the old microservices which used Spring Cloud Dalston release registered in Eureka with correct IP:PORT values which is dynamically distributed by DC/OS, but microservices which use Spring Cloud version Edgware and later are registered with port number always set to server.port.
So, for the following configuration the port number of registered application will be always 9997.

```
server.port: 9997

eureka:
  client:
    enabled: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8762}/eureka/
    healthcheck:
      enabled: true
  instance:
    hostname: ${LIBPROCESS_IP:localhost}

```

I tried to set it using secure and non-secure ports but it has't effect.
Is it possible to setup it correctly some how?
