### ISSUE TITLE
forward: /url does not route to serviceIds

### ISSUE THREAD

**Issue by CluEleSsUK** [spring-cloud/spring-cloud-netflix#2934]
Hi all,

I have some legacy routes that I wish to reroute to new microservices, and have a zuul config as follows:
```
zuul:
  routes:
    email-reroute:
      path: /email/form/**
      stripPrefix: true
      url: forward:/notifications/email/

    notifications:
      path: /notifications/**
      serviceId: notifications
```

Initially, it pattern matches the `/email/form` fine,
```Matching pattern:/email/form/**
2018-05-15 12:08:01.902 DEBUG [gateway,internal] route matched=ZuulRoute{id='email-reroute', path='/email/form/**', serviceId='null', url='forward:/notifications/email/', stripPrefix=true, retryable=null, sensitiveHeaders=[], customSensitiveHeaders=false, }
```

It then rewrites this URL as expected:
` DispatcherServlet with name 'dispatcherServlet' processing POST request for [/notifications/email/]`

However, it fails to find my subsequent notification service mapping:
`Matching patterns for request [/notifications/email/] are [/**]`

If I hit the `/notifications/email` endpoint directly, it makes a request to the notifications microservice as expected.
