### ISSUE TITLE
invoke service using ribbon slowly first time, second time is so fast

### ISSUE THREAD

**Issue by liyinsong** [spring-cloud/spring-cloud-netflix#2936]
I'm getting read timeout for a service that is taking a long time and throw the socket timeout exception, but next time call the same service very fast. Then i change the timeout time and disable the hystrix timeout like below:

```
ribbon:
  ConnectTimeout: 300000
  ReadTimeout: 300000
hystrix:
    command:
        default:
            execution:
                timeout:
                    enabled: false
```
Now there is no exception but also takes a long time to call the servcie, also the next invoke it's fast.
So i change the ribbon load to the eager-load strategy, but also have the same problem. 

```
ribbon:
      eager-load:
        enabled: true
```

The version is Dalston.SR4, can your guys give me some suggests?
