### ISSUE TITLE
Eureka Server in docker container not working properly behind nginx proxy

### ISSUE THREAD

**Issue by bolrock** [spring-cloud/spring-cloud-netflix#2940]
Hi all,

So I have a Spring Boot Eureka server deployed in a docker container

My **Dockerfile** contains

```
FROM openjdk:8-jdk-alpine

ENV JAVA_OPTS="-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1 -XshowSettings:vm"
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /usr/share/service/app.jar" ]
ARG JAR_FILE
ADD target/${JAR_FILE} /usr/share/service/app.jar

```

and my **docker-compose.yml**

```
version: '3.5'

services:

    discovery-service:
        image: springio/discovery-service:1.0.0-SNAPSHOT
        container_name: discovery-service
        restart: always
        ports:
          - "8761:8761"
        networks:
          - default
          - proxy
    
networks:
    proxy:
      external:
        name: proxy_network
```
For my nginx container, the default conf contains 

```
    ...
    set $portainer_upstream portainer:9000;
    set $api_discovery_upstream discovery-service:8761;
   ...
       location /portainer/ {
        rewrite ^/portainer/(.*) /$1 break;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_pass http://$portainer_upstream;
        proxy_buffers 16 16k;  
        proxy_buffer_size 16k;
    }
    location /eureka/ {
        rewrite ^/eureka/(.*) /$1 break;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_pass http://$api_discovery_upstream;
    }
   ...

```
When I'm trying to reach http://myhost:8761, it's working fine.

When I'm trying whith http://myhost/eureka, the page is displaying but all the static resources are not loaed.

![sans titre](https://user-images.githubusercontent.com/24407905/40171839-d0716fca-59cc-11e8-93c9-44e70358bfeb.png)

**Comment by bolrock** [comment]
For those who are looking for the solution :

In the nginx part don not rewrite the url, pass the full url to the container

```
    location /eureka/ {
        #rewrite ^/eureka/(.*) /$1 break;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_pass http://$api_discovery_upstream;
    }

```
In the application.yml, add the context-path of teh servlet

```
server:
  port: 8761
  servlet:
    context-path: /eureka

```
