### ISSUE TITLE
Client load-balancing not working when instances running on different datacenters

### ISSUE THREAD

**Issue by fiunchinho** [spring-cloud/spring-cloud-netflix#2964]
We are running Spring Cloud applications on AWS, using Eureka as service discovery, and hystrix+feign+ribbon to service to service communication.

We are now migrating applications to another datacenter, so we want to start deploying a single instance of one of our applications to that datacenter, but still using the same Eureka cluster as service discovery, so that services can communicate with each other. Our Eureka cluster consist on three different instances running on the same AWS region, each instance running on a different availability zone.

As soon as we deploy one instance of APPLICATION-1 and it's running on the new cluster, all the requests coming to APPLICATION-1 (requests coming from APPLICATION-2 or APPLICATION-3) end up on this instance, and the AWS instances for APPLICATION-1 get no requests at all.

If we remove the instance running on the new datacenter, then all APPLICATION-1 instances running on AWS start receiving traffic normally.

This is our Eureka instance configuration for all our applications
```
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    useDnsForFetchingServiceUrls: true
    eurekaServerDNSName: ${CLOUD_EUREKA}
    eurekaServerPort: 8080
    eurekaServerURLContext: eureka-server/v2
    region: eu-west-1
  instance:
    hostname: ${HOSTNAME}
    nonSecurePort: 80
    preferIpAddress: false
    instanceId: ${INSTANCE_ID}
```

And the application that's trying to send requests to the app called "myapp"
```
feign:
  hystrix:
    enabled: true
ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 2000
  MaxAutoRetries: 1
myapp:
  value: "myapp"
  ReadTimeout: 1000
  ConnectTimeout: 1000
```

We detected that the information being stored on Eureka about all the instances from APPLICATION-1 is different depending on where the instance is running. [Instances running on AWS have datacenter metadata information about AWS](https://cloud.spring.io/spring-cloud-netflix/multi/multi__service_discovery_eureka_clients.html#_using_eureka_on_aws), like the availability zone.
But instances running outside AWS, don't have that metadata, and it says the datacenter is "MyOwn".

Then this is the configuration I've tried (I randomly selected "eu-west-1a", but you could write "eu-west-1c")
```
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    useDnsForFetchingServiceUrls: true
    eurekaServerDNSName: ${CLOUD_EUREKA}
    eurekaServerPort: 8080
    eurekaServerURLContext: eureka-server/v2
    region: eu-west-1
  instance:
    hostname: ${HOSTNAME}
    nonSecurePort: 80
    preferIpAddress: false
    instanceId: ${INSTANCE_ID}
    metadataMap:
      zone: "eu-west-1a"
```

I tried hardcoding metadata information on the instance running outside AWS (the one that was receiving all the requests), then all the instances, both inside and outside AWS, start receiving traffic in a round robbin fashion.
This seems to work but I don't know why, or the potential implications of this change.

Any ideas?
