### ISSUE TITLE
TurbineAmqp with Eureka

### ISSUE THREAD

**Issue by ctatineni** [spring-cloud/spring-cloud-netflix#297]
Hello,

  I am trying to use turbine amqp to aggregate all the CB to one dashboard, when i run the turbine service with below configuration, i am getting 401 Bad request exception.i am using undertow, also i see that undertow is starting with port 8080 rather than 8989.

```
server
  port: 8989 

management:
  port: 8901

logging:
  level:
    root: INFO
    com.netflix.discovery: 'OFF'
    # org.springframework.integration: DEBUG

eureka:
  password: password
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    serviceUrl:
      defaultZone: ${vcap.services.${PREFIX:}eureka.credentials.uri:http://user:password@localhost:8761}/eureka/
```
