### ISSUE TITLE
Edgware+ ignores nonSecurePort

### ISSUE THREAD

**Issue by Kirill-Bezugly** [spring-cloud/spring-cloud-netflix#2984]
Hello,
Throughout #2883. After studying DC/OS documentation was found that $PORT_GATEWAY is DC/OS environment variable for named port mapping with name convention $PORT_{NAME} and this variable contains the mapped host port (so, it is not related to issue). 
Thereby, my problem is following - nonSecurePort ignored when I use Edgware and later versions. With this configuration:
```
server.port: 9997

eureka:
  client:
    enabled: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8762}/eureka/
    healthcheck:
      enabled: true
  instance:
    hostname: ${LIBPROCESS_IP:localhost}
    nonSecurePort: ${PORT_GATEWAY:1111}
```
my application registers always with {server.port} port number independently of what is in nonSecurePort value.
Could you help to find the misconfiguration in my Spring Boot application?
