### ISSUE TITLE
Eureka Peer Awareness in AWS using DNS

### ISSUE THREAD

**Issue by bsushant-athena** [spring-cloud/spring-cloud-netflix#2991]
Hi, I've following config and now I want to get rid of specifying server list and make it dynamic(mybe [DNS](https://github.com/Netflix/eureka/wiki/Deploying-Eureka-Servers-in-EC2)). Can somebody please suggest my what changes are needed in the below configuration?
```
eureka:
  server:
    port: 8093
    enable-self-preservation: false
  instance:
    hostname: localhost
    ipAddress: 127.0.0.1
    preferIpAddress: true
    instanceId: ${spring.application.name}-${HOST}-${PORT0}
    metadataMap:
      instanceId: ${spring.application.name}-${HOST}-${PORT0}
      dockerImage: "gateway"
      enableRegisterFilter: "false"
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  server:
    port: 8093
  eureka:
    datacenter: MyOwn
    hostname: localhost
    instance:
      preferIpAddress: true
      metadataMap:
        instanceId: ${spring.application.name}-${HOST}-${PORT0}
    client:
      serviceUrl:
        defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  sensitiveHeaders:
  routes:
    iam:
      path: /iam/**
      url: http://iams_auth:20020
server:
  port: 8093
```

Thanks,
Sushant
