### ISSUE TITLE
how can i use sidecar with zuul

### ISSUE THREAD

**Issue by zhongyusimon** [spring-cloud/spring-cloud-netflix#3031]
Question

I use sidecar with my php app, and zuul as the gateway. But when I forward my request to php app, it failed response 404 error, that means my request was responsed by sidecar instead of php app. How can I config my properties or write some ext code to fix this. thank you.

**Comment by spencergibb** [comment]
I don't know. Please provide more information such as your configuration or or a project that reproduces the problem

**Comment by zhongyusimon** [comment]
**zuul config**
```
spring:
  application:
    name: api-gateway
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
server:
  port: 8089
  tomcat:
    uri-encoding: UTF-8
logging:
  config: classpath:logback-spring.xml
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 120000
          semaphore:
            maxConcurrentRequests: 300
      fallback:
        isolation:
          semaphore:
            maxConcurrentRequests: 100
  threadpool:
    default:
      coreSize: 100
      maxQueueSize: 1000
      queueSizeRejectionThreshold: 500
ribbon:
  connectTimeout: 10000
  readTimeout: 60000
  maxAutoRetries: 1
  maxAutoRetriesNextServer: 2
zuul:
  ignoredServices: '*'
  semaphore:
    maxSemaphores: 300
  routes:
    test-com:
      path: /t**
      stripPrefix: false
      serviceId: sidecar1
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 10000
management:
  security:
    enabled: false
```

**sidecar config**
```
server:
  port: 5678
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: sidecar1
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
sidecar:
  port: 8091
  health-uri: http://localhost:8091/health.json
logging:
  config: classpath:logback-spring.xml
```

**Comment by zhongyusimon** [comment]
I think i found some way to resolve it. I config the sidecar as a zuul gateway, so I config it to forward the request to php app with the prefix /sidecar1/.

```yaml
server:
  port: 5678
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: sidecar1
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
sidecar:
  port: 8091
  health-uri: http://localhost:8091/health.json
logging:
  config: classpath:logback-spring.xml

zuul:
  semaphore:
    maxSemaphores: 300
  routes:
    sidecar1:
      path: /sidecar1/**
      stripPrefix: true
      url: http://localhost:${sidecar.port}/
management:
  security:
    enabled: false
```
