### ISSUE TITLE
PreDecorationFilter#addProxyHeaders append X-Forwarded-xx headers even if these headers are ignored

### ISSUE THREAD

**Issue by chanjarster** [spring-cloud/spring-cloud-netflix#3036]
Bug report

`PreDecorationFilter#addProxyHeaders` appends `X-Forwarded-Host`, `X-Forwarded-Port`, `X-Forwarded-Proto` headers even if these headers are ignored.

Below is how to reproduce the problem:

-------

## Echo server

I use echo server to see the headers send from zuul. Run a echo server:

```bash
docker run -p 9080:8080 -p 9443:443  -d --name echo-server gcr.io/google-containers/echoserver:1.10
```

## Zuul

`application.yaml`

```yaml
zuul:
  add-proxy-headers: true
  ignored-headers: X-Forwarded-Port,X-Forwarded-Host,X-Forwarded-Proto
  routes:
    echo-server:
      path: /echo-server/**
      url: http://localhost:9080/
```

`Application.java`

```java
@SpringBootApplication
@EnableZuulProxy
public class Application {

  public static void main(String[] args) {
    SpringApplication.run(Application.class, args);
  }

}
```

## Fire a request

```bash
curl -H 'X-Forwarded-Port:A' -H 'X-Forwarded-Host:B' -H 'X-Forwarded-Proto:C' http://127.0.0.1:8080/echo-server
```

**Actual result**

```
...
Request Headers:
 ...
	host=localhost:9080
	user-agent=curl/7.54.0
	x-forwarded-for=127.0.0.1
	x-forwarded-prefix=/echo-server
	x-forwarded-host=B,127.0.0.1:8080
	x-forwarded-port=A,8080
	x-forwarded-proto=C,http
...
```

**Expected result**

The old value of `x-forwarded-host, x-forwarded-port, x-forwarded-proto` should be abandoned, like this:

```
...
Request Headers:
 ...
	x-forwarded-host=127.0.0.1:8080
	x-forwarded-port=8080
	x-forwarded-proto=http
...
```
