### ISSUE TITLE
Zuul retry and ServerStats

### ISSUE THREAD

**Issue by siwydzik** [spring-cloud/spring-cloud-netflix#3053]
I came across some problems while testing Zuul retry logic. Acording to my tests ServerStats.successiveConnectionFailureCount is increased only in RibbonLoadBalancedRetryPolicy.updateServerInstanceStats. I've never seen ServerStats.clearSuccessiveConnectionFailureCount() being executed. The same goes for ServerStats.activeRequestsCount. It seems to me that the methods: noteResponse, noteRequestCompletion from LoadBalancerContext class are never executed. Could you please tell me if something is wrong with my config?

My config:
Springboot 1.5.13.RELEASE with Spring Cloud Edgware.SR3 and BestAvailableRule as a load balancing strategy.

I have spring-retry on my classpath.

```
zuul:
  health.enabled: true
  ribbonIsolationStrategy: SEMAPHORE
  retryable: true
  ignoredServices: '*'
  routes:
    consumer:
      path: /consumer/**
      serviceId: consumer
      stripPrefix: false

consumer:
  ribbon:
    ConnectTimeout: 5000
    ReadTimeout: 60000
    MaxAutoRetriesNextServer: 3
    MaxAutoRetries: 0
    OkToRetryOnAllOperations: true

hystrix:
  command:
    default:
      circuitBreaker:
        enabled: true
      execution:
        timeout:
          enabled: true

```
