### ISSUE TITLE
Hystrix status has always been "UP", Can you help me?

### ISSUE THREAD

**Issue by Yvan0329** [spring-cloud/spring-cloud-netflix#3055]
I have two microservices , One is a movie microservice, one is a user microservice, the movie microservice is a service consumer, and the user microservice is a service provider. I use hystrix in the movie microservices. I have checked the status of hystrix in /health and it has always been "UP". Even if I turn off another microservice(user), I always display "UP". I don't know where I am wrong.
The version of spring boot I am using is 2.0.3 RELASE
The state of hystrix has been 
```
{
    "status": "UP"
}
```
But the result I want is
```
{
    "status": "CIRCUIT_OPEN"
    "openCircuitBreakers":[
            "controller::method"
     ]
}
```
This is my configuration in application.yml
```
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
hystrix:
  metrics:
    enabled: true
```
When I turn off the user as a service, I keep asking until it stops requesting, but returns directly
