### ISSUE TITLE
Eureka client serving wrong ip to server when docker is running

### ISSUE THREAD

**Issue by tobiasvdp** [spring-cloud/spring-cloud-netflix#3069]
Question / Bug report

Hi,

I have a service running on my local pc, connecting to a eureka server running on a remote machine in the office. When docker is running on the client, the client serves the docker bridge (docker0, 10.0.71.1) ip as discovery instead of the host ip it is running on (10.0.1.xxx). Client is running in intellij (debug mode).

When stopping the docker service it returns to its normal host ip.

Running on linux machines, ubuntu 16.04
Used versions
```
<spring-boot-dependencies.version>1.5.13.RELEASE</spring-boot-dependencies.version>
<spring-cloud-dependencies.version>Edgware.SR3</spring-cloud-dependencies.version>
```

client yml
```
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
```

Any suggestions, workarounds? Or is the actually a bug?

**Comment by ryanjbaxter** [comment]
You might want to debug in this method https://github.com/spring-cloud/spring-cloud-commons/blob/ca1a97a3a484910527b17e95ae2cc6e1c06722c6/spring-cloud-commons/src/main/java/org/springframework/cloud/commons/util/InetUtils.java#L76.  Seems like something might be going on in your environment.

**Comment by spencergibb** [comment]
It's likely picking the internal Network first. The docs have options to exclude our include certain networks

**Comment by ryanjbaxter** [comment]
http://cloud.spring.io/spring-cloud-static/Finchley.RELEASE/single/spring-cloud.html#ignore-network-interfaces

**Comment by tobiasvdp** [comment]
Thanks, for some reason the bridge was indeed targeted as interface instead of the external network.
ignoring the interface solved the issue.

**Comment by RodrigoPetter** [comment]
So let me see if I get it right.

In my docker swarm, I have a custom network `test_nerwork` (10.0.0.0/24).
When I try to deploy a new services that exposes a port, docker will create a `Ingress network` that is used for load balance and routing-mesh(in my case 10.255.0.0/16). I'm not 100% sure but not always this ingress network is the `eth0` interface inside the container (can't find any documentation).

The services containers can't use the ingress network for http communication.

With the default Eureka configs, the services will use the eth0 interface IP (docker Ingress network) for registration. All communications with this service will fail because of the wrong IP advertised by the container.

To solve this problem I have 3 options:

1. Explicit say what IP should by advertised by the service (this only works because of the docker swarm routing-mesh). You may use any of yours swarm nodes IP.
```
eureka:
  instance:
    preferIpAddress: true
    ip-address: $MY_HOST_IP
```
By doing this you may overload the host that you chose you IP from. I don't think this is a good option.

2. Ignore all networks interfaces and set a preferred one. 
```
spring:
  cloud:
    inetutils:
      ignoredInterfaces:
        - docker
        - eth.*
        - lo
      preferredNetworks:
        - 10.0.0
```
Only setting the preferred one will not work.

3. Not use an IP address at all.
```
eureka:
  instance:
    preferIpAddress: true
    hostname: $SERVICE_NAME
```
Where `$SERVICE_NAME` must be the name of the service in your swarm. 
It will be registered at Eureka as `http://myservice:6003` and will work fine if you don't have any service running from outside the docker swarm.
I just don't know how the load balance will behave (Ribbon + Swarm DNS).
