### ISSUE TITLE
Zuul expansion of service scheduling problem?

### ISSUE THREAD

**Issue by j2eegis** [spring-cloud/spring-cloud-netflix#3076]
```
zuul:
  ignored-services: '*'
  routes:
    goods-service: /goods/**
goods-service:
  ribbon:
    NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
    DeploymentContextBasedVipAddresses: goods-service
    ConnectTimeout: 1000
    ReadTimeout: 3000
    MaxTotalHttpConnections: 500
    MaxConnectionsPerHost: 100
```
When you expand the goods-service, it will schedule the goods-service that is still in startup. This will cause the front end call to be wrong, and how to solve it?
