### ISSUE TITLE
Zuul: Rewrite requests

### ISSUE THREAD

**Issue by fdomig** [spring-cloud/spring-cloud-netflix#308]
Hi! I struggle with the zuul configuration to get the following use-case working:

I have a service that has two endpoints `/endpoint1` and `/endpoint2`. I would like to proxy the requests from `/api/endpoint1` and `/api/endpoint2` to the specific service but strip the `/api` prefix. Unfortunately it seems that I can only strip the prefix completely but not parts of it. So this would require some rewriting of the URL.

I would like to see the option to configure this somehow like this:

``` yml
zuul:
  routes:
    endpoint1:
      path: /api/endpoint1
      rewrite: /endpoint1
      serviceId: foo-service
    endpoint2:
      path: /api/endpoint2
      rewrite: /endpoint2
      serviceId: foo-service
```

Another option that would make sense would be to have a rewrite syntax e.g. like this:

``` yml
zuul:
  my-service:
    path: '/api/:endpoint'
    rewrite: '/{endpoint}'
    serviceId: my-service
```

Am I missing an already existing feature or would an extension like this make sense? Thanks for your reply.

**Comment by aivans** [comment]
```
zuul:
  prefix: /api 
  stripPrefix: true
  routes:
    endpoint1:
      path: endpoint1
      serviceId: foo-service
    endpoint2:
      path: endpoint2
      serviceId: foo-service
```

This should work for the specific example you gave, but I don't know if it covers other implications you might have there.
