### ISSUE TITLE
EurekaClientAutoConfiguration reads management context path from deprecated property

### ISSUE THREAD

**Issue by dsteegen** [spring-cloud/spring-cloud-netflix#3088]
Hi,

After upgrading our Spring Cloud application from Dalston.SR4 to Finchley.RELEASE, I noticed that discovery clients are still reading the management context path from the property `management.server.context-path`. However since Spring Boot 2, this property has been moved to `management.server.servlet.context-path`.

The class containing the bug is `EurekaClientAutoConfiguration`. In method `eurekaInstanceConfigBean` at line number 144, you will see the incorrect lookup of this property. This is only an issue when the property is actually being used. Leaving it blank (default value), everything is fine. The issue was noticed after not seeing the applications being registered in the Spring Boot Admin server which uses this property to fetch application info and health.
As a work around for now we can add the property that Eureka Discovery Client expects until the problem is resolved.

It was also in my understanding that the information could be sent to Eureka via the following properties:

```
eureka:
  instance:
    metadata-map:
      management:
        port: ${management.server.port}
        context-path: ${management.server.servlet.context-path}
```

However this seems to be ignored.
