### ISSUE TITLE
Status Page and Health Indicator paths are broken when custom management context path is configured and server port is random

### ISSUE THREAD

**Issue by gbtec-ext-sergeyuzhakov** [spring-cloud/spring-cloud-netflix#3098]
Release: Edgware.SR4

When I use a random server port like

```
eureka:
  instance:
    health-check-url-path: /health
    status-page-url-path: /info
management:
  context-path: /admin
server:
  port: 0
```

then management.context-path is ignored and status page & health indicator paths are broken.

In Eureka I have something like this 
```
<statusPageUrl>http://my_ip:62980/info</statusPageUrl>
<healthCheckUrl>http://my_ip:62980/health</healthCheckUrl>
```

Test project is available here  https://github.com/gbtec-ag/health-indicator-dalston2edgware-issue
