### ISSUE TITLE
Zuul retry to https service is not working

### ISSUE THREAD

**Issue by kboczek** [spring-cloud/spring-cloud-netflix#3102]
Release: Edgware.SR4, Edgware.SR3

I have two instances of service which registers itselves to eureka.

First instance:
```
eureka:
  instance:
    secure-port: ${server.port}
    securePortEnabled: true
    hostname: one.service.com
```
Second instance:
```
eureka:
  instance:
    secure-port: ${server.port}
    securePortEnabled: true
    hostname: two.service.com
```
I'd like set up zuul to retry request to other instance when first it tries to connect goes down and there is a connection timeout. 

In zuul I set
```
zuul:
  retryable: true
```
and also put _spring-retry_ in the classpath. 

With this configuration zuul cannot connect to the https service.

The problem seems to be in RibbonServer class which represents service instance got from eureka. 

While ServiceInstanceChooser(RetryableRibbonLoadBalancingHttpClient) try to choose service to call then server is got from load balancer and instance of RibbonServer is created with constructor 
```
public RibbonServer(String serviceId, Server server) {
			this(serviceId, server, false, Collections.<String, String> emptyMap());
		}

public RibbonServer(String serviceId, Server server, boolean secure,
				Map<String, String> metadata) {
			this.serviceId = serviceId;
			this.server = server;
			this.secure = secure;
			this.metadata = metadata;
		}
```
It means that flag _secure_ is always false. This flag is taken then when URI is built 
```
public static URI getUri(ServiceInstance instance) {
		String scheme = (instance.isSecure()) ? "https" : "http";
		String uri = String.format("%s://%s:%s", scheme, instance.getHost(),
				instance.getPort());
		return URI.create(uri);
	}
```

So with this configuration there is always _http_
