### ISSUE TITLE
Eureka Client registry IP problem when deploying by Docker Swarm on multiple VM

### ISSUE THREAD

**Issue by nguacon90** [spring-cloud/spring-cloud-netflix#3144]
Dear spring-cloud-netflix team,
Having problem when eureka client register IP address when deploying by docker swarm. This case as following:
+ We have Docker Swarm: docker-manager (IP: 124.158.17.23), worker-1 (IP 124.158.17.24), woker-2 (IP 124.158.17.25). 
+ Also we only deployed eureka-server at docker-manager with following configuration:
```yaml
eureka:
  instance:
    hostname: localhost
  client:  
    registerWithEureka: false
    fetchRegistry: false
server:
  port: 1111
```
+ We deployed gateway-api at worker-1 with following configuration:
```yaml
eureka:
  client:
    serviceUrl:
      fetchRegistry: true
      registryFetchIntervalSeconds: 5
      defaultZone: http://124.158.17.23:1111/eureka/
```
+ we deploy auth-service at worker-2 with following configuration:
```yaml
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      fetchRegistry: true
      registryFetchIntervalSeconds: 5
      defaultZone: http://124.158.17.23:1111/eureka/
```
- Note: all service deployed in the same overlay network.

The problem: 
- When Calling auth-service via api-gateway, connection timeout occurs. The root cause is eureka client auth-service register IP of docker container instead of host IP (124.158.17.25) of worker-2, therefore api-gateway container cannot forward to auth-service container.

Can you give any idea or solution to fixed the issue? 
Thank you very much!

**Comment by spencergibb** [comment]
Have you searched any of the closed issues for docker? Or the documentation? The are options to ignore certain networks

**Comment by nguacon90** [comment]
I add config to eureka client:
```yaml
spring:
  cloud:
    inetutils:
      ignoredInterfaces:
        - docker0
        - veth.*
```
However, also discovery container IP address not host IP, seem to be that eth0 inet of container.
Can you give me some suggestions? 
Best Regard.
