### ISSUE TITLE
Question - Configuring multiple rabbitmq in Spring Boot application

### ISSUE THREAD

**Issue by legendjaks** [spring-cloud/spring-cloud-netflix#3228]
I will be receiving a message from rabbitmq A and after processing, I need to send data to another rabbitmq B(external). So far I have seen example with single rabbitmq configuration with spring-boot. I couldn't find config in properties. How multiple rabbitmq can be configured in spring-boot? It is unusual, but there is a need to receive message from one mq and push different data to another mq.

Following is a config for single mq,
```
spring:
  cloud:
    stream:
      bindings:
        jobs:
          destination: jobs
          group: test
  rabbitmq:
    host: localhost
    port: 5672
```

I have posted the same in [stackoverflow](https://stackoverflow.com/questions/52762317/configuring-multiple-rabbitmq-in-spring-boot-application)
