### ISSUE TITLE
What is the relationship between ribbon timeout and hystrix timeout in zuul with semaphore isolation

### ISSUE THREAD

**Issue by yaoyuanyy** [spring-cloud/spring-cloud-netflix#3338]
in English:
I config a application.yml in zuul project, as follow
```
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000
ribbon:
  ReadTimeout: 19000
  ConnectTimeout: 19000
```
then after running the projects
i visit: curl http://xxxx, I find that timeout  is not 5s but 19s, so  hystrix timeout not work, i can not understand, tell me why

in Chinese:
spring cloud zuul1.x中，hystrix的超时和ribbon的超时，两者之间有什么关系吗?
我在zuul网关项目的配置文件中配置如下：
```
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000
ribbon:
ReadTimeout: 19000
ConnectTimeout: 19000
```
浏览器访问：等19s后连接断掉，提示超时
curl http://localhost:5555/api-a/add?a=1&b=2&accessToken=12

从上可以看出，超时ribbon起了作用，而hystrix没有看到起什么作用。在zuul中hystrix的超时是通过一个启动定时线程池来实现的，而zuul的隔离策略是semphere信号量，对于semphere策略，hystrix的超时似乎没有任何作用？
我使用的spring cloud zuul的版本为1.3.5、Dalston.SR4
根据我debug zuul和hystrix源码和google发现，当隔离策略是thread时，hystrix超时会打断ribbon的超时；而当隔离策略是semphere时，hystrix超时**不会**打断ribbon的超时，这个为什么呢，不打断的原因是什么呢
