### ISSUE TITLE
Defect of hystrix stream queue configuration

### ISSUE THREAD

**Issue by Incarnation-p-lee** [spring-cloud/spring-cloud-netflix#3359]
I would like to config the send-Rate of hystrix.stream.queue with some yml configuration like below code.
```yml
hystrix:
  stream:
    queue:
      send-id: false
      #      gather-rate: 2500
      send-rate: 2000
```

But still not working as the client always send with 500ms. After some investigation of source code in below
https://github.com/spring-cloud/spring-cloud-netflix/blob/5ecd0842cec00914206742c1d95c4b0dcb8fc5a8/spring-cloud-netflix-hystrix-stream/src/main/java/org/springframework/cloud/netflix/hystrix/stream/HystrixStreamTask.java#L92-L118

It should use `sendRate` instead of `send-rate`, as it not come from properties bean, only obtain properties value.

From one user's view, these two format should both work well as expect. The `@Scheduled` should leverage the value from property bean instead of literal property.

I can prepare the PR for it later if no urgent for this issus.
