### ISSUE TITLE
Zuul : rewrite request

### ISSUE THREAD

**Issue by hlassiege** [spring-cloud/spring-cloud-netflix#338]
Hi,

Considering I have several url I want to proxify with Zuul : 

```
/admin/something
/admin/somethingelse
/admin
```

The only solution I found is the following : 

```
zuul:
  routes:
    adminhome:
      path: /admin
      url: http://localhost:8079/
    admin:
      path: /admin/**
      url: http://localhost:8079/admin
```

Is it really the only solution ? 

Could we imagine something like that ?

```
zuul:
  routes:
    admin:
      path: /admin(/?)(.*)
      url: http://localhost:8079/admin/$2
```

**Comment by hlassiege** [comment]
Thinking about that, I have another use case I can't fullfill right now with Zuul that would be resolved with such a syntax.

I sometimes end up in situation when I want to rewrite the url 

/something/admin
=> /admin/something

It would be possible like that :

```
zuul:
  routes:
    somethingadmin:
      path: /(something)/(admin)
      url: http://localhost:8078/$2/$1
```

I'm more used to nginx to do such a thing and I'm feeling kinda limited by the Zuul syntax.
