### ISSUE TITLE
I have a question with "zuul local forward"

### ISSUE THREAD

**Issue by laiyy0728** [spring-cloud/spring-cloud-netflix#3392]
when i use zuul local forward like this yml
```
server:
    port: 8989
zuul:
  routes:
    spring-cloud-provider-service-simple:
      path: /provider/**
      url: forward:/client
```

visit http://localhost:8989/provider/get-result， reponse is
```
{
    "timestamp": "2019-02-15T06:41:06.196+0000",
    "status": 404,
    "error": "Not Found",
    "message": "No message available",
    "path": "/provider/get-result"
}
```

but when i vistt http://localhost:8989/provider ，response is
```
zuul local forward!
```

---

i think visit `/provider/**` should forward to `/client`，but now，it's `404 Not Found`，why is that？

**Comment by OlgaMaciaszek** [comment]
Hello @laiyy0728 Please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue.

**Comment by laiyy0728** [comment]
**sure! my source code as follow**


## ZuulServer
#### pom
```xml
<dependencies>
    <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-starter-netflix-zuul</artifactId>
    </dependency>
    <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-starter-netflix-eureka-client</artifactId>
    </dependency>
</dependencies>
```

#### yml
```yml
spring:
  application:
    name: spring-cloud-zuul-simple
server:
  port: 8989
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
zuul:
  routes:
    spring-cloud-provider-service-simple:
      path: /provider/**
      url: forward:/client
      serviceId: spring-cloud-provider-service-simple
  add-host-header: true
```

#### application
```java
@SpringBootApplication
@EnableDiscoveryClient
@EnableZuulProxy
@RestController
public class SpringCloudZuulSimpleApplication {

    public static void main(String[] args) {
        SpringApplication.run(SpringCloudZuulSimpleApplication.class, args);
    }

    @GetMapping(value = "/client")
    public String zuulForward(){
        return "zuul local forward!";
    }

}
```


## Provider service

#### pom
```xml
<dependencies>
    <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-starter-netflix-eureka-client</artifactId>
    </dependency>
</dependencies>
```

#### yml

```yml
spring:
  application:
    name: spring-cloud-provider-service-simple

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

server:
  port: 8081
```

#### application

```java
@SpringBootApplication
@EnableDiscoveryClient
@RestController
public class SpringCloudProviderServiceSimpleApplication {

    @Value("${server.port}")
    private int serverPort;

    public static void main(String[] args) {
        SpringApplication.run(SpringCloudProviderServiceSimpleApplication.class, args);
    }

    @GetMapping(value = "/get-result")
    public String provider(HttpServletRequest request){
        Enumeration<String> headerNames = request.getHeaderNames();
        StringBuilder headers = new StringBuilder();
        while (headerNames.hasMoreElements()) {
            String header = headerNames.nextElement();
            String value = request.getHeader(header);
            headers.append("[").append(header).append("]: ").append(value).append("; ");
        }
        return "this is provider service! this port is: " + serverPort + " headers: " + headers;
    }
}
```



# my question
when i visit zuu server, like `http://localhost:8989/provider/get-result` ,response is 
```json
{
    "timestamp": "2019-02-15T06:41:06.196+0000",
    "status": 404,
    "error": "Not Found",
    "message": "No message available",
    "path": "/provider/get-result"
}
```

but `http://localhost:8989/provider`, response is 
```
zuul local forward!
```

and Console print request headers. I think `http://localhost:8989/provider/get-result` response should be `zuul local forward!`, but no. why is that?

**Comment by ryanjbaxter** [comment]
@laiyy0728 please package it as a zip or put it in a git repo

**Comment by laiyy0728** [comment]
sure, the repo url is  https://github.com/laiyy0728/spring-cloud-zuul-local-forward

**Comment by spencergibb** [comment]
You can't have url and service id on a route

**Comment by laiyy0728** [comment]
when i delete `serviceId`, only use `path` and `url`, it still does't work.

I found it on the official document. `https://cloud.spring.io/spring-cloud-static/Finchley.RELEASE/multi/multi__router_and_filter_zuul.html#_strangulation_patterns_and_local_forwards`

this example has `url`, so i use this example,  but, it not show the results I want. what should i do?

**Comment by ryanjbaxter** [comment]
Please update your sample with the code you tried

**Comment by laiyy0728** [comment]
i was updated repo `zuul server yml`, according to the official document, only delete `serviceId`.  from
```
zuul:
  routes:
    spring-cloud-zuul-provider-service:
      path: /provider/**
      url: forward:/client
      serviceId: spring-cloud-zuul-provider-service
```

to 
```
zuul:
  routes:
    spring-cloud-zuul-provider-service:
      path: /provider/**
      url: forward:/client
```
