### ISSUE TITLE
How to set cookies to routes by zuul server?

### ISSUE THREAD

**Issue by jeesim2** [spring-cloud/spring-cloud-netflix#3402]
## configuration
```
zuul:
  routes:
    site-a:
      path: /gateway/site-a/**
      url: http://10.10.10.10:9900/
    site-b:
      path: /gateway/site-b/**
      url: http://10.10.10.10:5500/
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
```

With above configuration,
`http://proxysite/gateway/site-a/index.html` is well proxied to
`http://1010.10.10:9900/index.html`

## problem
But in index.html there are a lot of resource urls.
So, when index.html loaded to the user's browse and make some resource requests for
```
  <link rel="shortcut icon" href="/favicon.ico">
  <script type="text/javascript" src="/assets/functions.js"></script>
  <a href="/">HOME</a>
```
prooxysite can not redirect the request because the url is not started with proxy path.

## question
Can I set a cookie(something like 'PROXY_PATH=/gateway/site-a') at the zuul so that back end site's front end stuffs can refer that cookie then make proxy compatible urls.

want to
```
  <link rel="shortcut icon" href="{{PROXY_PATH_COOKIE_SET_BY_ZOOL}}/favicon.ico">
  <script type="text/javascript" src="{{PROXY_PATH_COOKIE_SET_BY_ZOOL}}/assets/functions.js"></script>
  <a href="{{PROXY_PATH_COOKIE_SET_BY_ZOOL}}/">HOME</a>
<script>
someFunction(){
  $.ajax({url: "{{PROXY_PATH_COOKIE_SET_BY_ZOOL}}/api/getList.json", success: function(result){
    // get api result
  });
};
</script>
```
