### ISSUE TITLE
Zuul ignores url parameters

### ISSUE THREAD

**Issue by xxlabaza** [spring-cloud/spring-cloud-netflix#344]
Hi,

I have a Zuul configuration:

```
...
zuul:
  ignoredServices: '*'
  prefix: /api
  routes:
    my_route:
      path: /call/*
      url:  'http://localhost:9999/my_service?param1=1&param2=2'
...
```

And I try to request it by this command:

```
curl <zuul_host>/api/call?param3=3
```

I expect to see redirection like this:

```
http://localhost:9999/my_service?param1=1&param2=2&param3=3
```

But Zuul ignores param1 and param2 and the request looks like:

```
http://localhost:9999/my_service?param3=3
```
