### ISSUE TITLE
Invalid handling of 404 status codes by RestTemplate in Eureka Client

### ISSUE THREAD

**Issue by devas123** [spring-cloud/spring-cloud-netflix#3488]
I use Eureka Client with RestTemplate instead of Jersey, and if i restart my Eureka Server, the client never registers itself back.

I use the following starters for the client and the server respectively
spring-cloud-starter-netflix-eureka-client:2.0.2.RELEASE
spring-cloud-starter-netflix-eureka-server:2.0.2.RELEASE

The problem is that in DiscoveryClient.renew() method there is a check for response code of the HttpResponse, and if the response code is 404 then the DiscoveryClient runs register() logic again.
But when I use RestTemplate, there is no 404 code in the HttpResponse, instead a HttpClientException is thrown and the re-registration logic is skipped.

To reproduce the issue just start Eureka Server (with or without Jersey - does not matter) and Eureka Client (WITHOUT Jersey). Let the client register itself and then restart the server.

my properties for the server: 
spring-cloud-starter-netflix-eureka-server version 2.0.2.RELEASE

```
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enable-self-preservation: false

```

for the client:
spring-cloud-starter-netflix-eureka-client version 2.0.2.RELEASE

```
eureka:
  instance:
    health-check-url-path: "/actuator/health"
    status-page-url-path: "/actuator/info"
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    filter-only-up-instances: false
```
