### ISSUE TITLE
Error “Load balancer does not have available server for client” when using zuul and eureka

### ISSUE THREAD

**Issue by StarReider** [spring-cloud/spring-cloud-netflix#3493]
I have a couple of microservices on Heroku - eureka-server, Zuul server and some app services.

While I am trying to reach any of my services, for example, "gamification" via Zuul gateway, Zuul is unable to forward the request to the respective service (when I'm trying to run them locally everything works fine). I've found the following errors in Zuul logs:

`com.netflix.zuul.exception.ZuulException: Forwarding error 
Caused by: com.netflix.client.ClientException: Load balancer does not have the available server for the client: gamification`

Below are configurations of my services:

1) "zuul server" application.yml
```
server:
  port: ${PORT:8000}

zuul:
  prefix: /api
  ignoredServices: '*'
  routes:
    leaders:
      path: /leaders/**
      serviceId: gamification
      strip-prefix: false
   ...

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:5000}/eureka/
```
2) "eureka server" application.yml
```
server:
  port: ${PORT:5000}

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
```
3.1) "gamification" application.yml
```
server.port=${PORT:8081}
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:5000}/eureka/
```
3.2) "gamification" bootstrap.yml
```
spring:
  application:
    name: gamification
```
All microservices are visible in eureka dashboard.

If I change zuul routes to hard-coded url it works well but it is not what I'm looking for.
```
zuul:
  prefix: /api
  ignoredServices: '*'
  routes:
    leaders:
      path: /leaders/**
      url: http://url_of_service_1
      strip-prefix: false
```
Could you please help me with this issue?

**Comment by spencergibb** [comment]
What does http://<eureka>/eureka/apps say? What are zuuls dependencies? What versions are you using?

**Comment by StarReider** [comment]
> What does http:///eureka/apps say? What are zuuls dependencies? What versions are you using?

Spring boot version - 2.1.0.RELEASE
Spring cloud version - Greenwich.M1
Eureka apps shows following (https://heroku-service-registry.herokuapp.com/eureka/apps)
[apps.zip](https://github.com/spring-cloud/spring-cloud-netflix/files/3037428/apps.zip)

**Comment by ryanjbaxter** [comment]
`/eureka/apps` is not returning anything so it looks like nothing is being registered with the Eureka server.  I would try to look into why none of your clients are registering.

**Comment by StarReider** [comment]
It is because of sleep policy in heroku.
If app receives no web traffic in a 30-minute period, it will sleep.
https://devcenter.heroku.com/articles/dynos#dyno-sleeping

So if you want to open /eureka/apps you need to wake up gateway and gamification services. Or you can download attached zip with my results.

**Comment by StarReider** [comment]
Finally, I've found root cause :)
All services are registered in eureka using heroku hostname by default (like "085930c7-b893-4b34-88a7-6e37fbe7fa0f") which is not accessible outside.
But services are accessible by domain names.
So I just added domain name settings to application.properties of each service
```
eureka:
  instance:
    hostname: ${DOMAIN_NAME}
    nonSecurePort: 80
```
and now it works.

Beside of it I need to override status url and health url as default ones are also not accessible
![image](https://user-images.githubusercontent.com/11455350/55876379-2ed33780-5ba0-11e9-89e3-c9135b848f1d.png)
