### ISSUE TITLE
Default ribbon clients config through properties/yml file 

### ISSUE THREAD

**Issue by sabareeshkkanan** [spring-cloud/spring-cloud-netflix#3575]
I was looking for some documentation for configuration in properties for default ribbon clients but unable to find. I found this https://github.com/spring-cloud/spring-cloud-netflix/issues/1741 but this doesnt address the properties file

I tried both of the following but they dont seem to work
```
default:
  ribbon:
    MaxAutoRetries: 3
    MaxAutoRetriesNextServer: 2
    OkToRetryOnAllOperations: false
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule
```
```

ribbon:
  MaxAutoRetries: 3
  MaxAutoRetriesNextServer: 2
  OkToRetryOnAllOperations: false
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule
```
