### ISSUE TITLE
Not Able to access Microservice via zuul proxy.

### ISSUE THREAD

**Issue by scorpionaps** [spring-cloud/spring-cloud-netflix#3591]
Hi Team. I am trying hands on in micro services with spring  cloud. I have 1 acting microservices deployed in local host on port 8303. i have Eureka server deployed in 8302. Eureka server is acting as Zuul proxy as well. When I am trying to access business logic in eurka server all is good but when i try to access other micro service deployed on 8083 it gives me 

Mon Jul 08 13:41:56 SGT 2019
There was an unexpected error (type=Not Found, status=404).
No message available

From Eureka dashboard I can see service(8303) is registered. Direct access via rest endpoints are also working.

Eureka Server application yml:
```
server:
  port: 8302

eureka:
  server:
    peer-eureka-status-refresh-time-interval-ms: 10000
  client:
    registerWithEureka: false
    fetchRegistry: false
#    server:
  #    waitTimeInMsWhenSyncEmpty: 0
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: localhost
      
zuul:
 prefix: /api


Eureka Client application.yml:
server:
  port: 8303


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8302/eureka/
  instance:
    hostname: localhost
```
form service action from UI:
  	 <form action="/api/<Application_name_registered_in Eureka_server>/rest/fileProcessing/uploadFile" method="post" enctype="multipart/form-data">

<Application_name_registered_in Eureka_server> - this is correct as per registered in Eureka server.

Any help would be appreciated.

Thanks
Anand
