### ISSUE TITLE
Zuul doesn't work serviceId on Tomcat server

### ISSUE THREAD

**Issue by Nyamkhuub** [spring-cloud/spring-cloud-netflix#3599]
my zuul config yaml file:
```
zuul:
    ignored-services: '*'
    routes:
        auth_server:
            path: /auth/**
            serviceId: auth_server
            stripPrefix: true
```
So I call URL like that.
`https://1xx.xx.xxx:8443/zuul/auth`
Response:
Bad Request
This combination of host and port requires TLS.

But I call URL like that.
`https://1xx.xx.xxx:8443/zuul/auth/`

In this case, viewing Tomcat home page. ???
Help me, please??
