### ISSUE TITLE
Eureka client defaults to http://localhost:8761/eureka/apps/ when project parent is not spring-cloud-starter-parent

### ISSUE THREAD

**Issue by bagerman** [spring-cloud/spring-cloud-netflix#360]
I am trying to make my existing services cloud aware by adding spring-cloud-starter-eureka dependency to my pom.xml file. I added `<dependencyManagement/>` for spring-cloud-starter-parent but can not make my service recognize non-localhost located eureka server. 

My services run as a war in tomcat and tried everything from setting in my application.yml:

```
eureka:
  client:
    serviceUrl:
      defaultZone: http://XXiXX:8080/registry/eureka/
```

 to setting in my catalina.properties: `eureka.client.serviceUrl.defaultZone=http://XXiXX:8080/registry/eureka/`

to no avail.

What can be wrong with my setup?
