### ISSUE TITLE
Routing to URL through proxy

### ISSUE THREAD

**Issue by weeyen91** [spring-cloud/spring-cloud-netflix#3604]
I'm using Spring Cloud Netflix 2.0.2 as an API gateway without Eureka Client with Spring Boot 2.0.3. My application.yml is as follows:
```
zuul:
  routes:
    admin:
      #path: /xx/xx/**
      #stripPrefix: false
      url: http://localhost:8999/admin
      serviceId: admin
```
In my development server, this setup works. The flow will be like

Application A > Zuul Gateway > Application B.

However, when deployed to my corporate network, the gateway will not be able to access Application B server directly, I will need to go through a proxy server like this.

Application A > Zuul Gateway > (My Corporate Proxy) > Application B

How do I configure this with Zuul?

Usually it's done with httpclient like below, but is there any configuration I can set on zuul? Thanks.
```
HttpHost proxy = new HttpHost("www.proxy.com", 8080, "http");
HttpClient httpClient = HttpClientBuilder.create().setProxy(proxy).build();
```
