### ISSUE TITLE
Sidecar does not respect adapted configuration of management endpoints

### ISSUE THREAD

**Issue by cplaetzinger** [spring-cloud/spring-cloud-netflix#3614]
We are using the Spring Cloud Netflix stack for a bunch of microservices. In order to integrate some none JVM applications we use the Sidecar. All our services are configured to  expose the health and info endpoints at /management instead of /actuator  (which is the default). This is done by the following properties:
```
management:
  endpoints:
    web:
      base-path: /management
eureka:
  instance:
    status-page-url-path: ${management.endpoints.web.base-path}/info
    health-check-url-path: ${management.endpoints.web.base-path}/health
```
This configuration is used for the Sidecar application as well. Unfortunately this configuration is not taken into account by org.springframework.cloud.netflix.sidecar.SidecarConfiguration. It just uses the defaults which point to /actuator/health and /actuator/info. Thus the wrong health and info endpoints get published to eureka.

Another issue is that the org.springframework.cloud.netflix.sidecar.SidecarController uses a hard coded link to point to /actuator/health. I guess this not as worse because it's just a local issue and does not affect the service registration.

The Sidecar application is running Spring Boot 2.1.6.RELEASE and Spring Cloud Greenwich.SR1
