### ISSUE TITLE
The spring-security default login form could not be routed correctly

### ISSUE THREAD

**Issue by FJiayang** [spring-cloud/spring-cloud-netflix#3633]
I was routing to a spring-security-based service using zuul, but a 404 error occurred when I submitted the form using the spring-security default login page

After checking, I found that the route of the login page was in line with expectations, and the address was: `http://localhost:9007/manager/login`

But the form submission path is `/login`, but the request is actually routed to `http://localhost:9007/login`, and the expected path is `http://localhost:9007/manager/login`

The version I used:

spring-boot version: 2.1.4.RELEASE

spring-cloud version: Greenwich.SR1

Here is my zuul configuration

```yaml
server:
  port: 9007
spring:
  application:
    name: gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
zuul:
  add-host-header: true
  routes:
    manager:
      path: /manager/**
      serviceId: MANAGER
  sensitive-headers: ''
```

spring-security service configuration

```yaml
server:
  port: 9004
spring:
  application:
    name: manager
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
```

I've already configured a `LocationRewriteFilter`

```java
@Bean
public LocationRewriteFilter locationRewriteFilter() {
    return new LocationRewriteFilter();
}
```

spring security default form

```html
<form class="form-signin" method="post" action="/login">
    <h2 class="form-signin-heading">
        Please sign in
    </h2>
    <p>
        <label for="username" class="sr-only">Username</label> <input type="text" id="username" name="username" class="form-control" placeholder="Username" required="" autofocus="">
    </p>
    <p>
        <label for="password" class="sr-only">Password</label> <input type="password" id="password" name="password" class="form-control" placeholder="Password" required="">
    </p><input name="_csrf" type="hidden" value="6d95f9d1-f9b0-4456-9c6c-d2e8c4abd2c6"> <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
</form>
```
