### ISSUE TITLE
Instance info is not adjusted to the registered vip context path

### ISSUE THREAD

**Issue by bagerman** [spring-cloud/spring-cloud-netflix#369]
While pulling information from hostname/eureka/apps I can see the following:
<homePageUrl>http://serviceAHost/</homePageUrl>
<statusPageUrl>http://serviceAHost/info</statusPageUrl>
<healthCheckUrl>http://serviceAHost/health</healthCheckUrl>
<vipAddress>serviceA</vipAddress>

when I would expect urls to point context specific url, something like that
<homePageUrl>http://serviceAHost/serviceA</homePageUrl>
<statusPageUrl>http://serviceAHost/serviceA/info</statusPageUrl>
<healthCheckUrl>http://serviceAHost/serviceA/health</healthCheckUrl>

both info and health endpoints only available in the context of the service. Is it right?

I am not sure if this is related but when I get "uri" from the ServiceInstance instance it does not have service (vipAddress ?) embedded there either.

**Comment by spencergibb** [comment]
How are you setting the context of the service?  Is it deployed via a war or are you setting the servletPath via config?  [The docs](http://projects.spring.io/spring-cloud/docs/1.0.1/spring-cloud.html#_status_page_and_health_indicator) say you can customize those:
```
eureka:
  instance:
    homePageUrlPath: ${server.servletPath}/
    statusPageUrlPath: ${server.servletPath}/info
    healthCheckUrlPath: ${server.servletPath}/health
```

Please show what you are experiencing from the "uri" of the `ServiceInstance`.
