### ISSUE TITLE
503 Service Unavailable for 90 seconds after restart of client

### ISSUE THREAD

**Issue by lafual** [spring-cloud/spring-cloud-netflix#3752]
Hi,

We are using the Hoxton version of Cloud. We have a Gateway and a number of micro-services / clients all linked via Eureka. When restarting a client (generally in STS while developing), it takes around ~90 seconds get from HTTP 503 to 200.

Following the advice on the reference document "Why is it so slow to register a service", it suggests changing the `lease-renewal-interval-in-seconds` to a lower value, but this seems to have no effect.

Is there another way to reduce the delay?

The client(s) are defined as;
```
eureka:
  client:
    service-url:
      default-zone: http://myserver:8760/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
```

The server is running in "standalone" mode and defined as;
```
server:
  port:8760
eureka:
  client:
     allow-redirects: true
     register-with-eureka: false
     fetch-registry: false
     service-url:
       default-zone: http://myserver:8760/eureka
```
