### ISSUE TITLE
Eureka server unavailable-replicas issue

### ISSUE THREAD

**Issue by Pengpengwanga** [spring-cloud/spring-cloud-netflix#3782]
**Describe the bug**
Please provide details of the problem, including the version of Spring Cloud that you
are using. 
Spring boot : 2.2.2.RESLEASE
Srping cloud : Hoxton.SR1

Anyone can help me? I am running 2 Eureka Servers, all servers are up, but the Eureka Server's Dashboard displaying the replicas in the unavailable-replicas section.  I don't know, why replicas displaying in the unavailable-replicas section?

my eureka server1 pom
```pom
  <dependencies>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-netflix-eureka-server</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>
```
my eureka server2 pom
 ```pom
	<dependencies>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-netflix-eureka-server</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>
```
my eureka server1 main class
```Java
@SpringBootApplication
@EnableEurekaServer
public class EurekaServer {

	public static void main(String[] args) {
		SpringApplication.run(EurekaServer.class, args);
	}
}
```
my eureka server2 main class 
```Java
@SpringBootApplication
@EnableEurekaServer
public class EurekaServer2 {

	public static void main(String[] args) {
		SpringApplication.run(EurekaServer2.class, args);
	}
}
```
my eureka server1 application.yml
```yaml
server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
       defaulZone: http://eureka7002.com:7002/eureka/
```
my eureka server2 application.yml
```yaml
server:
  port: 7002
eureka:
  instance:
    hostname: eureka7002.com
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
       defaulZone: http://eureka7001.com:7001/eureka/
```
My hosts file (windows10)
127.0.0.1  eureka7001.com
127.0.0.1  eureka7002.com

Thanks
