### ISSUE TITLE
spring-cloud-netflix-eureka-client reports wrong health-check-url , when server.servlet.context-path  and eureka.instance.health-check-url-path=${server.servlet.context-path:}/myHealthCheck is set

### ISSUE THREAD

**Issue by MadeInChina** [spring-cloud/spring-cloud-netflix#3808]
**Describe the bug**
spring-cloud-netflix-eureka-client reports wrong health-check-url , when server.servlet.context-path  and eureka.instance.health-check-url-path=${server.servlet.context-path:}/myHealthCheck is set

config
```
eureka:
  instance:
    metadata-map:
      management:
        context-path: ${server.servlet.context-path:}/actuator
    leaseRenewalIntervalInSeconds: 10
    status-page-url-path: ${server.servlet.context-path:}/actuator/info
    health-check-url-path: ${server.servlet.context-path:}/actuator/health

  servlet:
    context-path: /uaa
```

Issue is that if 
  set 
```
   status-page-url-path: ${server.servlet.context-path:}/actuator/info
   health-check-url-path: ${server.servlet.context-path:}/actuator/health
servlet:
    context-path: /uaa
```

status-page-url-path is correct in eureka server
  http://10.42.1.114:5000/uaa/actuator
but 
health-check-url-path is not correct in eureka server
  http://10.42.1.114:5000/uaa/uaa/actuator/health
  context-path are duplicated  /uaa/uaa/

the root caused by fix 
https://github.com/spring-cloud/spring-cloud-netflix/issues/2702

Unit test case
```
	@Test
	public void healthCheckUrlPathWithServerPortAndContextPathKebobCase() {
		TestPropertyValues.of("server.port=8989",
				"server.servlet.context-path=/servletContextPath",
				"eureka.instance.health-check-url-path=${server.servlet.context-path:}/myHealthCheck")
				.applyTo(this.context);
		setupContext(RefreshAutoConfiguration.class);
		EurekaInstanceConfigBean instance = this.context
				.getBean(EurekaInstanceConfigBean.class);
		assertThat(instance.getHealthCheckUrl()
				.endsWith(":8989/servletContextPath/myHealthCheck"))
						.as("Wrong health check: " + instance.getHealthCheckUrl())
						.isTrue();
	}
```

**Sample**
<img width="1439" alt="Screen Shot 2020-06-05 at 8 01 13 PM" src="https://user-images.githubusercontent.com/1201118/83888641-b99bcc00-a77c-11ea-8f22-045caad57e9a.png">
<img width="1172" alt="Screen Shot 2020-06-05 at 8 34 31 PM" src="https://user-images.githubusercontent.com/1201118/83888674-c15b7080-a77c-11ea-86da-fc41f8b455e2.png">
<img width="1214" alt="Screen Shot 2020-06-05 at 8 33 59 PM" src="https://user-images.githubusercontent.com/1201118/83888700-c91b1500-a77c-11ea-959f-4b89b4d613c6.png">
<img width="1214" alt="Screen Shot 2020-06-05 at 8 33 59 PM" src="https://user-images.githubusercontent.com/1201118/83888713-ccae9c00-a77c-11ea-8349-fe462f5ab73f.png">
