### ISSUE TITLE
Eureka client only use the first service url in configure

### ISSUE THREAD

**Issue by wangzw** [spring-cloud/spring-cloud-netflix#3830]
Version: Hoxton.SR5

I have two eureka servers configured in application's bootstrap.yml, but only the first is used when application is trying to bootstrap. When the first eureka server is down, application cannot start.

```
eureka:
    client:
        serviceUrl:
            defaultZone: http://uat4-eureka:8761/eureka,http://uat5-eureka:8761/eureka
```
