### ISSUE TITLE
Zuul: Route to secure URL

### ISSUE THREAD

**Issue by kazarian** [spring-cloud/spring-cloud-netflix#385]
I am implementing a secure gateway architecture - based off Dave Syer's Spring Security and Angular JS Guide. 

One of the UIs in my world is a legacy PHP web application that requires HTTPS connectivity. When I attempted to route calls through the gateway to the PHP application, using Zuul routes, I receive a socket timeout. 
```
zuul:
  routes:
    phpapp:
      url: http://localhost:80
    phpssl:
      url: https://somelocalserver/phpinfo.php
```
Making calls to the 'phpapp' route above works fine.

I tested another configuration calling Google over HTTPS and still I receive a socket timeout - HTTP works fine (granted I get redirected to their HTTPS site https://www.google.com/?gws_rd=ssl).
```
zuul:
  routes:
    phpapp:
      url: http://localhost:80
    phpssl:
      url: https://somelocalserver/phpinfo.php
    google:
      url: https://www.google.com
```
Is there some configuration that I'm missing here?
