### ISSUE TITLE
Filter to route some requests through an external proxy

### ISSUE THREAD

**Issue by devansh-dalal** [spring-cloud/spring-cloud-netflix#3906]
I have been trying to find solution for this for days now, 

My problem
```
zuul:
  routes:
    test:
      path: /test/**
      serviceId: test
      url: http://my.api.server.com
    test2:
      path: /test2/**
      serviceId: test2
      url: http://my.api.server.com // but through an external proxy
```

I could find this https://github.com/spring-cloud/spring-cloud-netflix/issues/2320 at the best. But that would requiring extending the default `SimpleHostRoutingFilter ` with 2 different `CloseableHttpClient ` and is too much code change, this is probably unavoidable in my setting. any suggestions pls?
