### ISSUE TITLE
zuul proxy return Empty Response when using spring.main.lazy-initialization=true

### ISSUE THREAD

**Issue by kioyong** [spring-cloud/spring-cloud-netflix#3913]
**Describe the bug**
i am using @EnableZuulProxy to proxy my service, but when i add spring.main.lazy-initialization=true,  all proxy response become empty response,

**Sample**
refer https://github.com/kioyong/zuul-proxy-issue-reproduce
when add below config in application.yml, all proxy response become empty
```yml
spring:
  main:
    lazy-initialization: true # zuul proxy routes return empty response when lazy-initialization is true
```
