### ISSUE TITLE
sideCar can not un-register service once nodeJS service is down

### ISSUE THREAD

**Issue by xhe** [spring-cloud/spring-cloud-netflix#395]
I suspect this is an issue, please have a check:

In my sideCar application, I have application.yml:
```
server:
  port: 5678
spring:
  application:
    name: nodeservice
    
sidecar:
  port: ${nodeServer.instance.port:3000}
  health-uri: http://localhost:${nodeServer.instance.port:3000}/app/health.json
  
eureka:
  instance:
    hostname: ${host.instance.name:localhost}
    leaseRenewalIntervalInSeconds: 5 #default is 30, recommended to keep default
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
```

And in my main spring config app, I have:
```
String url_node = "";
		try {
			InstanceInfo instance = discoveryClient.getNextServerFromEureka("nodeservice", false);
			// InstanceInfo instance = discoveryClient.getNextServerFromEureka("foo", false);
			url_node = instance.getHomePageUrl();
		} catch (Exception e) {
		}
```
Now I start my nodeJS server, I have in spring app:

url for nodeService is: http://SJCC02MT0NUFD58.local:3000/

This is perfect, but after I shutdown my nodeJS server, 
http://localhost:3000/app/health.json url is totally down, BUT, in the main java spring app, I still see the same output there.

So it seemed even if the NodeJS service is no longer available, eureka is still remembering that in memory.

Anything wrong for my configuration?
