### ISSUE TITLE
Eureka Report HTTP status code 400; discarding 1 replication tasks

### ISSUE THREAD

**Issue by lidengke** [spring-cloud/spring-cloud-netflix#3961]
when I install eureka cluster by two instances on my pc, after application start up, ERROR log as followed appear:

2021-01-27 20:37:23.264 ERROR 4888 --- [rget_server1-17] c.n.e.cluster.ReplicationTaskProcessor   : Batch update failure with HTTP status code 400; discarding 1 replication tasks
2021-01-27 20:37:23.264  WARN 4888 --- [rget_server1-17] c.n.eureka.util.batcher.TaskExecutors    : Discarding 1 tasks of TaskBatchingWorker-target_server1-17 due to permanent error
 
so, what happens?

My Code：
pom.xml
```xml
 <properties>
    <java.version>1.8</java.version>
    <spring-cloud.version>Finchley.RELEASE</spring-cloud.version>
  </properties>
<dependencies>
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-netflix-eureka-server</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-test</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-dependencies</artifactId>
        <version>${spring-cloud.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
```
```yaml
application.yaml
spring:
  application:
    name: eureka-server
```
application-server1.yaml
```yaml
server:
  port: 8761
eureka:
  server:
    enable-replicated-request-compression: true
    peer-eureka-nodes-update-interval-ms: 10000
  instance:
    hostname: server1
    prefer-ip-address: false
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://server2:8762/eureka/
```
application-server2.yaml
```yaml
server:
  port: 8762
eureka:
  server:
    enable-replicated-request-compression: true
    peer-eureka-nodes-update-interval-ms: 10000
  instance:
    hostname: server2
    prefer-ip-address: false
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://server1:8761/eureka/
```
/etc/hosts

127.0.0.1 server1
127.0.0.1 server2
