### ISSUE TITLE
Discovery of third party apps, such as databases (redis)

### ISSUE THREAD

**Issue by marcosbarbero** [spring-cloud/spring-cloud-netflix#403]
Recently I was working with redis-sentinel and spring-boot adding some params config, eg.

```
redis.sentinel:
  master: my-master-name
  nodes: 127.0.0.1:6379
```

I was thinking if should not be good to have an discoverable configuration for those nodes using eureka/consul, instead of passing the node IP we just pass the application sidecar name.  

Would be something like this:

```
redis.sentinel:
  loadBalanced: true
  master: my-master-name
  appname: my-sentinal-sidecar
```

I don't know if it's a good idea or have any issue about performance, I would like to discuss about it.  

Moved from [spring-boot #3262](https://github.com/spring-projects/spring-boot/issues/3262)
