### ISSUE TITLE
Eureka datacenter and environment not displayed on the Eureka dashboard

### ISSUE THREAD

**Issue by prashdeep** [spring-cloud/spring-cloud-netflix#4032]
I am using Eureka server - version 3.0.3 and have configured the datacenter and environment information using the below configuration:

```
eureka:
  datacenter: Mumbai
  environment: QA
  server:
    enable-self-preservation: false
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    register-with-eureka: false
    fetch-registry: false
```
I do not see the Datacenter and Environment information in the Eureka dashboard. In the older versions of Eureka, the information used to be displayed. Is there any change in the configuration with the current release?
