### ISSUE TITLE
Spring boot application ,accessing routs with gateway service gives white label error?

### ISSUE THREAD

**Issue by phantom2152** [spring-cloud/spring-cloud-netflix#4146]
Hey Guys I was developing a simple project with spring boot, which has 2 services user and blogs and I am using eureka server and I tried to implement a gateway service and it also got registered on the eureka server also but I cannot access the route paths of either user or blog service can anyone please help me with this. This the application.yml file for the gateway service

![image](https://user-images.githubusercontent.com/70034285/206014201-888c3abb-ad52-4c66-a09b-d52745174781.png)
![image](https://user-images.githubusercontent.com/70034285/206014256-11c5a56b-2608-4131-8541-175712b8fb34.png)

```
server:
  port: 3030
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: userModule
          uri: http://localhost:3001/
          predicates:
            - Path=/users/**
        - id: blogModule
          uri: http://localhost:3002/
          predicates:
            - Path=/blogs/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3000/eureka
  registerWithEureka:
    - true
  fetchRegistry:
    - true

```
