### ISSUE TITLE
Can I use the dashboard endpoint to help me figure out why my settings aren't working?

### ISSUE THREAD

**Issue by DongJu-Na** [spring-cloud/spring-cloud-netflix#4227]
```
server:
  port: 8761
spring:
  application:
    name: eureka
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  instance:
    hostname: localhost
    preferIpAddress: true
  server:
    waitTimeInMsWhenSyncEmpty: 0
management:
  endpoints:
    web:
      exposure:
        include: "*"
```

Sorry, I'm using a translator.

Even though service-url: defaultZone: ${EUREKA URI:http://localhost:8761/eureka/} is set
When connected to localhost:8761/ the dashboard will load.

Can you tell me why I see a white label when connecting to localhost:8761/eureka/?
