### ISSUE TITLE
Discovery client can't register -> 401 error

### ISSUE THREAD

**Issue by Issamhanzaz** [spring-cloud/spring-cloud-netflix#4234]
When running the Discovery Client it'll not register to the Discovery Server caused by a 401 error. 
```
c.n.d.s.t.d.RetryableEurekaHttpClient    : Request execution failure with status code 401; retrying on another server if available
``` 
it works when I disable Spring Security in the discovery server but it doesn't when security is enabled. The username and password are given in the DefaultZone url. 

When I CURL the Discovery server with username and password in the URL it works, it seems like something goes wrong in the Discovery Client.

**This returns 200 success:** 
`curl http://user:password@localhost:8761`

**Spring cloud version: 2022.0.3
Spring boot version: 3.1.5**

**Discovery server -> Security Config (Disable CSRF)**
```java
@Configuration
@EnableWebSecurity
public class SecurityConfig{
    @Bean
    public SecurityFilterChain filterChain(HttpSecurity http) throws Exception {
        return http
                .csrf(AbstractHttpConfigurer::disable)
                .securityMatcher("/eureka/**")
                .build();
    }
}
``` 

**Discovery server -> application.yml**
```yml
spring:
  application:
    name: DiscoveryServer
  security:
    user:
      name: user
      password: password
server:
  port: 8762
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://user:password@localhost:${server.port}/eureka/
``` 

**Discovery client -> application.yml**
```yml
spring:
  application:
    name: GDPRAgent
server:
  port: 8099
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://user:password@localhost:8762/eureka/
```
