### ISSUE TITLE
cannot register to eureka server with random port and AOT

### ISSUE THREAD

**Issue by vladgon** [spring-cloud/spring-cloud-netflix#4235]
`mavenBom 'org.springframework.cloud:spring-cloud-dependencies:2023.0.0`

According to 
> https://github.com/spring-cloud/spring-cloud-release/wiki/AOT-transformations-and-native-image-support and other documentation `spring.cloud.refresh.enabled` should be `false` when AOT compiling.

Application works fine when spring.cloud.refresh.enabled is true, but fails to register (registers with the port 0 ) when refresh is disabled 

Server application.yaml
```
spring:
  application:
    name: demo-eureka-server

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true

  dashboard:
    path: /dashboard
```
Client application.yaml
```
server:
  port: 0

spring:
  application:
    name: GreetingServer
  cloud:
    refresh:
      enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
    status-page-url-path: '/'
    instance-id: ${spring.application.name}:${random.long[0,90000000000000000]}
    leaseExpirationDurationInSeconds: 1
    lease-renewal-interval-in-seconds: 1
```
