### ISSUE TITLE
Eureka sets management port incorrectly

### ISSUE THREAD

**Issue by redijedi** [spring-cloud/spring-cloud-netflix#425]
It appears as if services that register with the Eureka server ignore the management.port value and use the server.port for resolving the links to the management endpoints. Consider this abridged application.yml:

```
server:
  port: 8000

management:
  port: 9000
  context-path: /admin

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

  instance:
    preferIpAddress: true
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
```

The link in the Eureka admin app always points to `http://192.168.2.220:8000/admin/info` when the proper link should be `http://192.168.2.220:9000/admin/info`.

Perhaps I missed a configuration, else this seems to be a bug.

**Comment by spencergibb** [comment]
That syntax you used works if _just_ `management.context-path` is set.  If you set the port as well, you likely need to set `eureka.instance.statusPageUrl` and `eureka.instance. healthCheckUrl` and set the whole url.  If that works, we likely just need to update the docs.  If not, it's a bug.

**Comment by redijedi** [comment]
That's tricky if I don't want to specify the host. That is, if I want the
host to be dynamically resolved, then hard coding a value for the full path
would be undesirable.

Cheers,
Todd

**Comment by spencergibb** [comment]
I figured as such.  It's eureka code that uses the `*UrlPath`, port and hostname to build the url.  We could probably trigger something if `management.port` is set.

**Comment by Aloren** [comment]
Hi! We have just faced the same issue.
In our application.properties we have:
```
server.port=8115
management.port=8116

eureka.instance.statusPageUrlPath=/info
eureka.instance.healthCheckUrlPath=/health
```

Such configuration resolves url incorrectly. Eureka redirects to:
http://HOSTNAME:8115/info

@spencergibb, is there any workaround for the following issue?

Thanks!

**Comment by ojacquemart** [comment]
Hello!

Almost the same issue here with:
```
server:
    port: 0
    context-path: /foo
  
  management:
    port: 0
    context-path: /admin
```

The apps starts with effective ports:
```
server.port: 42230
management.port: 33208
```

Eureka always registers the instance with the management port (33208 instead of 42330) and then zuul routes fails to route the requests.

Is there a workaround or is it a known bug?
