### ISSUE TITLE
Looking for a way to block patterns in zuul

### ISSUE THREAD

**Issue by andreasevers** [spring-cloud/spring-cloud-netflix#445]
Currently it is possible to ignore an entire service in the zuulProxy:

```yaml
 zuul:
  ignoredServices: '*'
  routes:
    users: /myusers/**
```

I would like to go one step further and have a property `zuul.ignoredRoutes` or `zuul.ignoredPatterns` which could hold an ant pattern that when matched, doesn't forward the request.

The specific use case is where I am trying to allow actuator endpoints to be reachable directly on the microservice, but not through the gateway (to not expose them to the outside world).
While the actuator is the main reason, there would also be other resources to hide to the outside.

**Comment by dsyer** [comment]
I would have thought securing the endpoints you don't want people to access was a lot easier to implement and understand. Isn't that really what you want to do?

**Comment by andreasevers** [comment]
I'd like to secure endpoints in such a way that when accessed directly on the server they are unsecured (perfect for internal management tools such as Spring Boot Admin or hystrix and turbine dashboard), but when going through zuul they wouldn't get exposed.

Not sure if I'm over-engineering this or not.

**Comment by dsyer** [comment]
It sounds reasonable to me (assuming the proxy is the only server on an accessible network). Security constraints can be applied in the proxy.

**Comment by andreasevers** [comment]
Can I create a pull request?
I would imagine something like this:

```
 zuul:
  ignoredServices: '*'
  ignoredPatterns: /myusers/**/admin,/mycustomers/**/admin
  routes:
    users: /myusers/**
```
```ignoredPatterns``` would be a comma-separated list of ant patterns which would supersede any route defined.
