### ISSUE TITLE
Zuul metadata aware routing

### ISSUE THREAD

**Issue by jmnarloch** [spring-cloud/spring-cloud-netflix#458]
I had this crazy idea that I would like to share and see what would be the feedback. We have a setup within Zuul that forward a set of paths with protocol version paths ex:

```
/api/v1 -> rest-service-v1
/api/v2 -> rest-service-v2
```

This is perfectly fine and works like a charm, although I can think of much more generic approach through Eureka metadataMap.

```
zuul:
  routes:
    api:
      path: /api/{version}/**
      serviceId: rest-service
```

```
eureka:
  instance:
    hostname: rest-service
    metadataMap:
      version: v1
```

With such approach it wouldn't be required to update the proxy routing and set new route in the future without restart or refresh of the proxy instances.
