### ISSUE TITLE
Zuul SimpleHostRoutingFilter defaults HTTPS to port 8443

### ISSUE THREAD

**Issue by cfieber** [spring-cloud/spring-cloud-netflix#461]
https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/zuul/filters/route/SimpleHostRoutingFilter.java#L316

SchemeRegistry is keyed on scheme name, so the second registration of https at 8443 overwrites the standard default port of 443

To work-around, explicitly qualify the port for an outbound https endpoint

**Comment by cfieber** [comment]
This specifically affects trying to do something like this (I was looking at the https://github.com/dsyer/spring-security-angular oauth2-vanilla example and testing against a real 3rd party authserver when I found this):

```
zuul:
  routes:
    user:
      path: /user/**
      url: https://my.https.userinfo.com:443/idp/userinfo.openid
```

It took debugging all the way in to the guts of httpclient to figure out why it was failing with a socket timeout without explicitly qualifying the https port
