### ISSUE TITLE
SimpleHostRoutingFilter does not honor https.proxy

### ISSUE THREAD

**Issue by ktong** [spring-cloud/spring-cloud-netflix#510]
config zuul as below:
```
zuul:
  routes:
    li:
      path: /li/**
      url: https://api.${li.api.domain}:443/${li.api.version}
```
and set system properties https.proxy, but zuul cannot connect to api via proxy.
