### ISSUE TITLE
Allow Zuul proxy to hit endpoints on application it is embedded in

### ISSUE THREAD

**Issue by mikegehard** [spring-cloud/spring-cloud-netflix#536]
I have the following use case:

I have an existing API that I wish to rewrite in Spring. This application is running in production and I want to incrementally develop the new application while I keep the old application running by moving endpoints from the old application into the new application. 

My desire is to configure the new Spring application with @EnableZuulProxy using the following configuration:

```
zuul:
  routes:
    oldApp:
      path: /**
      url: http://old.server.com
```
so that the clients of the API do not have to worry about the conversion once the new application is put in front of the old application. They will simply hit the new application from the start and never know that the old application has gone away.

As I move endpoints from the old application, I would like to exclude paths using the "ignoredPatterns" configuration setting like so:

```
zuul:
  ignoredPatterns: 
    - /movedEndpoint1
    - /movedEndpoint2
  routes:
    oldApp:
      path: /**
      url: http://old.server.com
```

When I do this, I would like the path /movedEndpoints1 to be forwarded to the new application that contains the @EnableZuulProxy annotation. Currently it seems that the ZuulController intercepts all requests to the new application because the path is /** and when it sees that the ignoredPatters contains /movedEndpoint1 it returns a 404 for that path but still forwards any non-excluded requests to the old application.

Is there a way to do this?
Am I missing something?

For an example that demonstrates this behavior, see:
https://github.com/mikegehard/springCloudZuulProxy/commit/b7aff943cda2f0a1e61be4b90506ab56a4621d23

The workaround is to explicitly map each endpoint in the proxy settings. See:
https://github.com/mikegehard/springCloudZuulProxy/commit/ddeaa8ad56f9f912e6bb8ee66c71d7d2b34fd187
