### ISSUE TITLE
How to forward all requests to specific version (of same service) during deployment using netflix?

### ISSUE THREAD

**Issue by GauravAjmera** [spring-cloud/spring-cloud-netflix#549]
I have 4 instance of the same service running on different hosts. I am deploying new version for that service node by node. While deployment, incoming requests get forwarded according to the load balancer to any version (host). Is there any way in netflix where I can forward all incoming requests to a specific version?

Is there any generic way where we can define version (for same serviceId). And if incoming requests has version defined in header, we can use that to forward the requests to specific version.
Could be something like:
In Zuul Proxy,
```
zuul:
  routes:
    sample:
      path: /sample/{version}/**
      serviceId: sample-service
```
In sample-service,
```
eureka:
  instance:
    appname: sample-service
    metadataMap:
      version: v1
```
or any other mechanism to achieve versioning?
