### ISSUE TITLE
nonSecurePort in bootstrap has no effect. Using Cloud Foundry

### ISSUE THREAD

**Issue by bogdatov** [spring-cloud/spring-cloud-netflix#679]
Hello 
I'm trying to deploy my service on CloudFoundry and in CF there is router which forwards request from URL on port 80 to actual service. My problem is that even set ( as per documentation)

eureka.instance.hostname: ${vcap.application.uris[0]}
eureka.instance.hostname.nonSecurePort: 80

It still shows up in /eureka/apps as different port ( port 6300):
```
<application>
  <name>USERMANAGEMENT</name>
<instance>
  <hostName>usermanagement.cfappstpanpaz2.mycompany.com</hostName>  
  <app>USERMANAGEMENT</app>
  <ipAddr>blah-blah</ipAddr>
  <status>UP</status>
  <overriddenstatus>UNKNOWN</overriddenstatus>
  <port enabled="true">63600</port>
  <securePort enabled="false">443</securePort>
   <countryId>1</countryId>
```

How do I make sure that I use proper port ONLY for that specific profile ? I have multiple profiles, some of them are running inside CloudFoundry, some of them are regular jars running on Unix box

Here is part of my bootstrap.yml
```
---
spring:
 profiles: development-cloud
eureka.instance.hostname: ${vcap.application.uris[0]}
eureka.instance.hostname.nonSecurePort: 80
eureka:
 client:
  serviceUrl:
   defaultZone: http://service-discovery-locator.cfappstpanpaz2.mycompany.com/eureka/
 instance:
  metadataMap:
   instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${eureka.instance.hostname.nonSecurePort}:${random.value}}}

```

I'm using this to enable Eureka client
```
@Configuration
@EnableEurekaClient
public class AppConfig {
```

I do not use any custom Eureka related beans. Here is what I use from Maven central
```
<dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-eureka</artifactId>
      <version>1.0.3.RELEASE</version>
      <scope>compile</scope>
    </dependency>
```
