### ISSUE TITLE
Zuul and oauth config

### ISSUE THREAD

**Issue by vajda** [spring-cloud/spring-cloud-netflix#681]
Hi, I'm having following situation in my config file on frontend which is also zuul proxy:

```
security.oauth2:
  client:
    accessTokenUri: http://localhost:9090/auth-server/oauth/token
    userAuthorizationUri: http://localhost:9090/auth-server/oauth/authorize
    clientId: foo
  resource:
    jwt:
      keyValue: |
        -----BEGIN PUBLIC KEY-----
        SOME_KEY
        -----END PUBLIC KEY-----

zuul:
  routes:
    auth-server:
      serviceId: auth-server
      stripPrefix: false
    resource-server1:
      serviceId: resource-server1
    resource-server2:
      serviceId: resource-server2
```

What bothers me is that address to oauth2 endpoints is hardcoded, I would like to use serviceId (auth-server in particular) there also, since I'm using eureka as discovery service. How can I achieve that?
