### ISSUE TITLE
Eureka SideCar. eureka.instance.hostname not used in Cloud Foundry

### ISSUE THREAD

**Issue by bogdatov** [spring-cloud/spring-cloud-netflix#684]
Hello,

I have weird issue with sidecar. All my other apps, which use @EnableEurekaClient work fine, but this one - side car, returns wrong eureka.instance.hostname, not the one I want in bootstrap.yml.

Here is what I have in bootstrap.yml
```
eureka.instance.statusPageUrlPath: /swagger-ui.html

---
spring:
 profiles: development-cloud
eureka.instance.hostname:  ${vcap.application.uris[0]}
eureka.instance.nonSecurePort: 80
eureka:
 client:
  serviceUrl:
   defaultZone: http://${SERVICE_DISCOVERY_HOST:service-discovery-locator.cfappstpanpaz2.mycompany.com}:${SERVICE_DISCOVERY_PORT:80}/eureka/
 instance:
  metadataMap:
   instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}:${random.value}}}

```
Then, I print EurekaInstanceConfigBean at startup:
```
@Configuration
@RefreshScope
@EnableEurekaClient
@EnableSidecar
public class AppConfig {
	private static final Logger LOGGER = LoggerFactory.getLogger(AppConfig.class);
	
    @Value("${eureka.instance.hostname:localhost}")
    private String hostName;

    @Autowired
    EurekaInstanceConfigBean eurekaInstanceConfigBean;
    
    @Bean
    public String eurekaInfo() {
    	LOGGER.info("eureka.instance.hostname: {}", hostName);
    	LOGGER.info("eurekaInstanceConfigBean: {}", eurekaInstanceConfigBean);
    	return hostName;
    }
    
	}
```
When I look at runtime logs I see that although my eureka.instance.hostname is correct: eureka.instance.hostname: service-sidecar-server.cfappstpanpaz2.mycompany.com

But it does no get into the bean, so my bean has hostname provided by CF ( see this 1922mma8o5i as hostname):
```
Wed Dec 02 2015 14:21:31 GMT-0500 (Eastern Standard Time) [App/0] OUT 2015-12-02 19:21:31,221 33 INFO [main] c.v.u.s.s.server.config.AppConfig [AppConfig.java:37] --- eureka.instance.hostname: service-sidecar-server.cfappstpanpaz2.mycompany.com 

Wed Dec 02 2015 14:21:31 GMT-0500 (Eastern Standard Time) [App/0] OUT 2015-12-02 19:21:31,221 33 INFO [main] c.v.u.s.s.server.config.AppConfig [AppConfig.java:38] --- eurekaInstanceConfigBean: EurekaInstanceConfigBean(hostInfo=[10.254.3.202, 1922mma8o5i], appname=service-sidecar-server, appGroupName=null, instanceEnabledOnit=false, nonSecurePort=80, securePort=443, nonSecurePortEnabled=true, securePortEnabled=false, leaseRenewalIntervalInSeconds=30, leaseExpirationDurationInSeconds=90, virtualHostName=service-sidecar-server, secureVirtualHostName=null, aSGName=null, metadataMap={instanceId=207bc122b4424175acf4383702a6d3f7}, dataCenterInfo=org.springframework.cloud.netflix.eureka.EurekaInstanceConfigBean$IdentifyingDataCenterInfo@4df379e5, ipAddress=10.254.3.202, statusPageUrlPath=/swagger-ui.html, statusPageUrl=http://1922mma8o5i:63713/info, homePageUrlPath=/, homePageUrl=http://1922mma8o5i:0/, healthCheckUrlPath=/health, healthCheckUrl=http://1922mma8o5i:63713/health, secureHealthCheckUrl=null, namespace=eureka, hostname=service-sidecar-server.cfappstpanpaz2.mycompany.com, preferIpAddress=false, initialStatus=UP) 

Wed Dec 02 2015 14:21:31 GMT-0500 (Eastern Standard Time) [App/0] OUT 2015-12-02 19:21:31,289 33 INFO [main] o.s.j.e.a.AnnotationMBeanExporter [MBeanExporter.java:431] --- Registering beans for JMX exposure on startup 
``` 

And then ... in Eureka server dashboard it shows my that weird hostname, and it also does not respect this:
eureka.instance.statusPageUrlPath: /swagger-ui.html

How do I get around it ? So my hostname will be: service-sidecar-server.cfappstpanpaz2.mycompany.com

**Comment by bogdatov** [comment]
I'm using 
```
	<parent>
		<groupId>org.springframework.cloud</groupId>
		<artifactId>spring-cloud-starter-parent</artifactId>
		<version>Angel.SR3</version>
		<relativePath /> <!-- lookup parent from repository -->
	</parent>
...
<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-netflix-sidecar</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-eureka</artifactId>
		</dependency>
```

**Comment by spencergibb** [comment]
You need to set the full url for the status page, `eureka.instance.statusPageUrl=...`

**Comment by bogdatov** [comment]
It works for other apps, with just this:
```
spring:
 application: 
  name: trail-design-get
eureka.instance.statusPageUrlPath: /swagger-ui.html
```

On Eureka dashboard it translates into this link:
http://trail-design-get.cfappstpanpaz2.mycompany.com/swagger-ui.html

But for sidecar similar setup:
```
spring:
 application: 
  name: service-sidecar-server
endpoints.env.keys-to-sanitize: eureka.instance.statusPageUrlPath: /swagger-ui.html
```

translates into this link: http://1922q6n6vpu:62629/info
So it does not respect anything from:
eureka.instance.statusPageUrlPath: /swagger-ui.html
eureka.instance.hostname:  ${vcap.application.uris[0]}
eureka.instance.nonSecurePort: 80

**Comment by spencergibb** [comment]
@bogdatov is your yaml pasted as is? or is it missing the two space indentation?

**Comment by bogdatov** [comment]
This is my bootstrap.yml with related info - sidecar - posted as is:
```
spring:
 application: 
  name: service-sidecar-server
eureka.instance.statusPageUrlPath: /swagger-ui.html

---
spring:
 profiles: development-cloud
eureka.instance.hostname:  ${vcap.application.uris[0]}
eureka.instance.nonSecurePort: 80
eureka:
 client:
  serviceUrl:
   defaultZone: http://${SERVICE_DISCOVERY_HOST:service-discovery-locator.cfappstpanpaz2.mycompany.com}:${SERVICE_DISCOVERY_PORT:80}/eureka/
 instance:
  metadataMap:
   instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}:${random.value}}}


```
