### ISSUE TITLE
Zuul routes cannot be removed dynamically

### ISSUE THREAD

**Issue by aivans** [spring-cloud/spring-cloud-netflix#705]
I noticed that it is possible to add routes via Spring cloud Config (or by changing the yml directly), but it is not possible to remove routes.

Scenario:
- routed defined:

```
zuul:
ignored-services: "*"
  routes:
    echo3:
      path: /echo3/**
      url: http://www.aaa.com
```
- route shows fine in /admin/routes
- remove route from yml
- hit /admin/refresh() endpoint. The response mentions that changes were detected about the route
- Problem: /admin/routes still shows the route
