### ISSUE TITLE
Zuul routes cannot be changed dynamically from "url" to "serviceId"

### ISSUE THREAD

**Issue by aivans** [spring-cloud/spring-cloud-netflix#706]
I noticed that it is possible to edit routes via Spring cloud Config (or by changing the yml directly) with the same type <code>url</code>, but it is not possible to change the route to point to a service VIP

Scenario:
- routed defined:

```
zuul:
ignored-services: "*"
  routes:
    echo3:
      path: /echo3/**
      url: http://www.aaa.com
```
- route shows fine in /admin/routes
- change route to

```
zuul:
ignored-services: "*"
  routes:
    echo3:
      path: /echo3/**
      serviceId: echo-service
```
- hit /admin/refresh() endpoint. The response mentions that changes were detected about the route
- Problem: /admin/routes still shows the old route, pointing to <code>url</code>

**Comment by aivans** [comment]
It worked when adding this code to a configuration class. The idea is to have the ```ZuulProperties``` bean with ```@RefreshScope```

```
    @Bean(name="zuul.CONFIGURATION_PROPERTIES")
    @RefreshScope
    @ConfigurationProperties("zuul")
    public ZuulProperties zuulProperties() {
    	return new ZuulProperties();
    }
```

**Comment by rohitghatol** [comment]
Hi 

I followed your comment about ZuulProperites. Are you trying to say with the changes you mentioned in the comments the routes gets deleted dynamically?

I tried with the following code but to no effect, by routes are not getting deleted dynamically. I do see the log after I deleted route2

`2016-03-01 00:48:12.648  INFO 8900 --- [MOQVri6LhXrwQ-1] o.s.cloud.bus.event.RefreshListener      : Received remote refresh request. Keys refreshed [spring.cloud.client.hostname, zuul.routes.route2.url, zuul.routes.route2.path]`

Before:
```

zuul:
  ignoredServices: "*"
  routes:
    route2:
      path: /r2
      url: https://api.github.com/users/rohitghatol/repos
    route3:
      path: /r3
      url: https://api.github.com/users/rohitghatol/repos
```

After:
```
zuul:
  ignoredServices: "*"
  routes:
    route3:
      path: /r3
      url: https://api.github.com/users/rohitghatol/repos
```


----------------------------------------------------------------------------------------------------------------
# Code 
----------------------------------------------------------------------------------------------------------------
```
@SpringBootApplication
@EnableAutoConfiguration
@EnableZuulProxy
@EnableConfigurationProperties({ZuulProperties.class})
public class ApiGatewayServiceApplication {

  @Bean(name = "zuul.CONFIGURATION_PROPERTIES")
  @RefreshScope
  @ConfigurationProperties("zuul")
  public ZuulProperties zuulProperties() {
    System.out.println("======> Called");
    return new ZuulProperties();
  }

  public static void main(String[] args) {
    SpringApplication.run(ApiGatewayServiceApplication.class, args);
  }
}

```
