### ISSUE TITLE
Eureka Server not Accessible for Traditional war Deployment in Docker

### ISSUE THREAD

**Issue by abhijitsarkar** [spring-cloud/spring-cloud-netflix#741]
Eureka boot gradle project [here](https://github.com/abhijitsarkar/java-ee/tree/master/discovery-service). Works fine when I run `bootRun`, Eureka binds to port 8080 on localhost, accessible from browser, everyone happy. When started as a Docker container, it binds to `docker-machine` IP:8080 but I cannot access from browser.

I know that there are several example of Eureka on Docker but none using gradle and traditional deployment. 

Command I use to start a container: `docker run -it -p 8080:8080 -e DOCKER_HOST="$(echo $DOCKER_HOST | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}')" xxx`

**Log Snippet**:
```
Adding replica node: http://192.168.99.107:8080/eureka/
2015-12-26 03:35:42.959  INFO 7 --- [ost-startStop-1] n.a.javaee.discovery.DiscoveryServer     : Started DiscoveryServer in 8.167 seconds (JVM running for 12.804)
```

**application.yml**:

```
server:
  port: ${PORT:8080}

eureka:
  instance:
    hostname: ${DOCKER_HOST:localhost}
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
```

**Dockerfile**:
```
FROM abhijitsarkar/docker:tomcat8

ADD build/libs/*.war $CATALINA_HOME/webapps/discovery.war

CMD ["supervisord", "-c", "/etc/supervisord.conf"]
```

**DiscoveryServer**:
```
@SpringBootApplication
@EnableEurekaServer
public class DiscoveryServer extends SpringBootServletInitializer {
    public static void main(String[] args) {
        SpringApplication.run(DiscoveryServer.class, args);
    }

    @Override
    protected SpringApplicationBuilder configure(SpringApplicationBuilder application) {
        return application.sources(DiscoveryServer.class);
    }
}
```
