### ISSUE TITLE
Sidecar doesn't support multiple instances for the same service

### ISSUE THREAD

**Issue by codependent** [spring-cloud/spring-cloud-netflix#744]
A usual microservice allows us to start several instances using profiles and all those instances get registered in Eureka. e.g:
```
---
spring:
  application:
    name: images-microservice
  profiles: images1
server:
  port: 9999
eureka:
  client:
    serviceUrl:
      defaultZone: http://archimedes2:8762/eureka/,http://archimedes1:8761/eureka/
    healthcheck:
      enabled: true
---
spring:
  application:
    name: images-microservice
  profiles: images2
server:
  port: 9998
eureka:
  client:
    serviceUrl:
      defaultZone: http://archimedes2:8762/eureka/,http://archimedes1:8761/eureka/
    healthcheck:
      enabled: true
```
Eureka console:
```
IMAGES-MICROSERVICE	n/a (2)	(2)	UP (2) - myhost:images-microservice:9998/info , myhost:images-microservice:9999/info
```

However let's say I have two instances of a node.js microservice, one running on port 3000 and the other on port 3100. I start two instances of the sidecar, pointing at the corresponding ports:
```
---
spring:
  application:
    name: author-ms
  profiles: author1
server:
  port: 9595
sidecar:
  port: 3000
  health-uri: http://localhost:${sidecar.port}/health.json
eureka:
  client:
    serviceUrl:
      defaultZone: http://archimedes2:8762/eureka/,http://archimedes1:8761/eureka/
    healthcheck:
      enabled: true
---
spring:
  application:
    name: author-ms
  profiles: author2
server:
  port: 9696
sidecar:
  port: 3100
  health-uri: http://localhost:${sidecar.port}/health.json
eureka:
  client:
    serviceUrl:
      defaultZone: http://archimedes2:8762/eureka/,http://archimedes1:8761/eureka/
    healthcheck:
      enabled: true
```
In this case, only the last sidecar to start gets registered in Eureka (???)

Eureka console:
```
AUTHOR-MS	n/a (1)	(1)	UP (1) - myhost   ----> port 9595
```

**Comment by aivans** [comment]
```
AUTHOR-MS   n/a (1) (1) UP (1) - myhost   ----> port 9595
```
Something seems wrong in your setup.
AUTHOR-MS ports should be 3000 or 3100. 9595 is the port of the sidecar process.
Did you add `@EnableSidecar` annotation?

**Comment by codependent** [comment]
@aivans Actually this line points at the sidecar /info endpoint, which is correct:

    AUTHOR-MS	n/a (1)	(1)	UP (1) - myhost ---> http://myhost:9595/info

This is my Spring Boot App:
```
@EnableSidecar
@SpringBootApplication
public class AuthorMsSidecarApplication {
	
    public static void main(String[] args) {
    	new SpringApplicationBuilder(AuthorMsSidecarApplication.class).web(true).run(args);
    }
}
```

**Comment by spencergibb** [comment]
@aivans is correct, you need a unique instance id or eureka uses host as the id, therefore, only one service is registered. See [Making the Eureka Instance ID Unique](http://projects.spring.io/spring-cloud/docs/1.0.3/spring-cloud.html#_service_discovery_eureka_clients), for Angel. It should be automatic for Brixton. Feel free to reopen if that doesn't work and you provide a sample application showing the problem.

**Comment by codependent** [comment]
@spencergibb One question:

With "normal" microservices a config like this:
```
---
spring:
  application:
    name: random-number-ms
  profiles: images1
server:
  port: 9999
---
spring:
  application:
    name: images-microservice
  profiles: images2
server:
  port: 9998
```

Gets you two services in which the Eureka Id is the host+name+port. So in the Eureka console I see:

`RANDOM-NUMBER-MS	n/a (2)	(2)	UP (2) - myhost:random-number-ms:9999 , myhost:random-number-ms:9998`

Now I want to achieve the same with a sidecar app that calls two instances of node.js services:
```
spring:
  application:
    name: random-letter-ms
  profiles: random-letter-sidecar1
        
server:
  port: 9595

sidecar:
  port: 3000
  health-uri: http://localhost:3000/health.json

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
```
spring:
  application:
    name: random-letter-ms
  profiles: random-letter-sidecar1
        
server:
  port: 9696

sidecar:
  port: 3001
  health-uri: http://localhost:3000/health.json

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
```
Oddly enought in this case, although I start two sidecar instances only one shows up in Eureka console. I don't understand why with sidecars the id isn't made up of host+name+port as happened with normal microservices...

`RANDOM-LETTER-MS	n/a (1)	(1)	UP (1) - EXPRF026.suministrador.local`

I'm preparing a sample project to show this behaviour. I'll add a new comment as soon as it's ready.
