### ISSUE TITLE
ProxyRouteLocator hard-codes prefix to '*'

### ISSUE THREAD

**Issue by abhijitsarkar** [spring-cloud/spring-cloud-netflix#753]
`ProxyRouteLocator` fails to remove the prefix for path like `**/*`.

```java
if (route.isStripPrefix()) {
    // Shouldn't the * come from ZuulProperties.getPrefix() ?
    int index = route.getPath().indexOf("*") - 1;
    if (index > 0) {
        String routePrefix = route.getPath().substring(0, index);
	targetPath = targetPath.replaceFirst(routePrefix, "");
	prefix = prefix + routePrefix;
    }
}
```

**Comment by dsyer** [comment]
I'm not sure what you mean really. If your route has a path of `**/*` (is that even legal?) then there is no way to strip a prefix ,and the code above is not going to do anything, so that seems consistent.

**Comment by abhijitsarkar** [comment]
Perhaps explaining the use case will help. What I'm looking to do is for Zuul to be a central point of authentication/authorization. Each service may have additional security checks but Zuul must enforce  common auth rules.
The way I tried to achieve this was something like the following:
```
zuul:
  routes:
    auth: /**/*
```

If the `ProxyRouteLocator`, instead of doing `indexOf("*")`, did `lastIndexOf("*")`, then it could indeed strip whatever is matched by the `**` prefix. I could save that in `com.netflix.zuul.context.RequestContext` using a Zuul `pre` filter, and once the auth response comes back, I could then, in a `post` filter, use the previously saved prefix to forward to that service.

The workaround I currently have lists each service by name, as shown below, and then uses a custom [Zuul routing filter](https://github.com/abhijitsarkar/java-ee/blob/master/daily-update-microservices/gateway-service/src/main/java/name/abhijitsarkar/javaee/gateway/web/AuthAwareRoutingFilter.java) to achieve what I described above:
```
#  Disable Ribbon routing. We're rolling our own that can do auth.
  RibbonRoutingFilter.route.disable: true
  ignoredServices: '*'
  routes:
    movie-service:
      path: /movies/**
      stripPrefix: false
    news-service:
      path: /news/**
      stripPrefix: false
    weather-service:
      path: /weather/**
      stripPrefix: false
    daily-update-service:
      path: /dailyupdate/**
      stripPrefix: false
```
