### ISSUE TITLE
Eureka-UI : enable to configure or reuse management.context-path

### ISSUE THREAD

**Issue by cforce** [spring-cloud/spring-cloud-netflix#780]
I use management.context-path: /management for all services (even eureka itself). The Eureka still doesn't care and renders standard path to myineurekaregisteredservice:123/info instead of myineurekaregisteredservice:123/management/info

**Comment by spencergibb** [comment]
According to the [documentation](http://projects.spring.io/spring-cloud/docs/1.0.3/spring-cloud.html#_status_page_and_health_indicator), set the following:
```
eureka:
  instance:
    statusPageUrlPath: ${management.contextPath}/info
    healthCheckUrlPath: ${management.contextPath}/health
```
