### ISSUE TITLE
eureka client registration determines wrong statuspageurl and healthurl after update from brixton m3 to m4

### ISSUE THREAD

**Issue by pcornelissen** [spring-cloud/spring-cloud-netflix#789]
I am building an application that uses eureka and spring-cloud. I evaluated brixton m3 and everything works fine, but after an update to m4 the clients could not connect to each other anymore.

After some investigation I found out that the eureka client now sends the wrong statuspageurl and healthurl after the update.

I have attached the corresponding log with debug info from the apache http lib to show the difference:
[brixton-m3.txt](https://github.com/spring-cloud/spring-cloud-netflix/files/102399/brixton-m3.txt)
[brixton-m4.txt](https://github.com/spring-cloud/spring-cloud-netflix/files/102400/brixton-m4.txt)

The important part is this:
M3: "homePageUrl":"http://192.168.99.1:48090/","statusPageUrl":"http://192.168.99.1:48090/internal/info","healthCheckUrl":"http://192.168.99.1:48090/internal/health","vipAddress":"lunchdeals"
M4: "homePageUrl":"http://192.168.99.1:48090/","statusPageUrl":"http://192.168.99.1:8080/info","healthCheckUrl":"http://192.168.99.1:8080/health","vipAddress":"lunchdeals"
This is the eureka config that is used by the client:

Have a look at the ports, M3 uses the correct 48090 and m4 uses 8080 which is wrong the app is not bound to this port at all. (the port is completely free)

```
eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /internal/info
    healthCheckUrlPath: /internal/health
    non-secure-port: 0
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
      password: ${security.user.password}
  client:
    serviceUrl:
      defaultZone: ${vcap.services.${PREFIX:}eureka.credentials.uri:http://user:password@dockermachine:8761}/eureka/
```

To clarify what I did:
do a clean build with m3 run against my eureka server, capture network traffic, switch to m4 clean again and run the app. So no residual old libs should be present.
