### ISSUE TITLE
Zuul Server with @EnableOAuth2Sso to proxy service with @EnableOAuth2Resource

### ISSUE THREAD

**Issue by raphsoft** [spring-cloud/spring-cloud-netflix#796]
I would appreciate your comments regarding this question:

I do have an spring-boot application annotated with @EnableZuulProxy which is intended to be our edge server and should proxy request to our backend spring-boot rest services. So as I understand, Zuul will automatically relay the token if the @EnableOAuth2Sso annotation is present. 

So we also have everything running in Cloud Foundry and actually the Zuul server with OAuth2 works fine: it redirects you to our SSO Login when the user is not authenticated and is able to respond non-proxied request (for instance: environment information in the /env path provided by actuator).

Then I go to my backend service and set values for the spring.oauth2.client.* properties with the same as those for the Zuul server:

```
spring:
  oauth2:
    client:
      clientId: id_from_zuul
      clientSecret: secret_from_zuul
      accessTokenUri: https://sso.login.myorg.com/oauth/token
      userAuthorizationUri: https://sso.login.myorg.com/oauth/authorize
      clientAuthenticationScheme: header
    resource:
      userInfoUri: https://sso.login.myorg.com/userinfo
      preferTokenInfo: false
```

Also, I add the @EnableOAuth2Resource annotation to my spring-boot backend service and add the  configuration for the XSRF Token:

```
@SpringBootApplication
@EnableEurekaClient
@EnableOAuth2Resource
public class CacheApplication extends WebSecurityConfigurerAdapter {

    public static void main(String[] args) {
        if ("true".equals(System.getenv("SKIP_SSL_VALIDATION"))) {
            SSLValidationDisabler.disableSSLValidation();
        }
        SpringApplication.run(CacheApplication.class, args);
    }


    @Override
    protected void configure(HttpSecurity http) throws Exception {
        http.antMatcher("/**").authorizeRequests().anyRequest()
                .authenticated().and().csrf()
                .csrfTokenRepository(csrfTokenRepository()).and()
                .addFilterAfter(csrfHeaderFilter(), CsrfFilter.class);
    }


    private Filter csrfHeaderFilter() {
        return new OncePerRequestFilter() {
            @Override
            protected void doFilterInternal(HttpServletRequest request,
                                            HttpServletResponse response, FilterChain filterChain)
                    throws ServletException, IOException {
                CsrfToken csrf = (CsrfToken) request
                        .getAttribute(CsrfToken.class.getName());
                if (csrf != null) {
                    Cookie cookie = new Cookie("XSRF-TOKEN",
                            csrf.getToken());
                    cookie.setPath("/");
                    response.addCookie(cookie);
                }
                filterChain.doFilter(request, response);
            }
        };
    }

    private CsrfTokenRepository csrfTokenRepository() {
        HttpSessionCsrfTokenRepository repository = new HttpSessionCsrfTokenRepository();
        repository.setHeaderName("X-XSRF-TOKEN");
        return repository;
    }
}
```

However, I still get 403 (Forbidden) when I try to access the backend service through the zuul proxy,  after doing a successful login with SSO.
