### ISSUE TITLE
Zuul routes: Possible to use eureka serviceId + url

### ISSUE THREAD

**Issue by flindby** [spring-cloud/spring-cloud-netflix#818]
Hi, 

I have a microservice: "invoice-service" registered with Eureka. I use Zuul as a API-Gateway for routing. In invoice service I have URL like: "/v1/invoices", "/v1/invoices/{invoiceId}", "/v2/invoices" (InvoiceController V1 /V2). 

How can I combine eureka instanceId with the URL so I can configure Zuul like so:

```
zuul:
  routes:       
    invoice-serviceV1:
      path: /v1/invoices/**
      url: {invoice-service}/v1/invoices/**
    invoice-serviceV2:
      path: /v2/invoices/**
      url: {invoice-service}/v2/invoices/**
```

When I use this config:

```
zuul:  
  routes:    
    invoice-service: /v1/invoices/**
```

I have to write: http://localhost:8765/v1/invoices/v1/invoices to access my invoice-service, which is not desireable.

Any suggestions?

**Comment by Koizumi85** [comment]
Hello,

you can write the following:

```
zuul:  
  routes:    
    invoice-service: /v1/invoices/**
    strip-prefix: false
```

this should cause Zuul to not remove the /v1/invoices from the path when dispatching the request to your invoice-service.

**Comment by flindby** [comment]
Thanks, I thought I tried that several times, but apparently not. I had to write It like this though:
```
zuul:
  routes:
    invoice-service:
      path: /v1/invoices/**
      stripPrefix: false
```
