### ISSUE TITLE
Eureka on AWS not registering Instance Info

### ISSUE THREAD

**Issue by anthonyikeda** [spring-cloud/spring-cloud-netflix#833]
I'm really stumped on this one and it used to work.

I'm using:

        springBootVersion = "1.3.2.RELEASE"
        springCloudVersion = "Brixton.M4"

With:

    compile 'org.springframework.cloud:spring-cloud-starter-eureka-server'
    compile 'org.springframework.cloud:spring-cloud-aws-autoconfigure'
    runtime 'joda-time:joda-time:2.8.2'

I've set up a basic Eureka Application:

    @SpringBootApplication
    @EnableEurekaServer
    public class DiscoveryServer {
        public static void main(String[] args) {
            SpringApplication.run(DiscoveryServer.class, args);
        }
    }

And configure an AWS profile (bootstrap.yml):

    server:
      port: 8761

    spring:
      application:
        name: discoveryServer
      cloud:
        config:
          discovery:
            enabled: false

    eureka:
      instance:
        prefer-ip-address: false
      client:
        registerWithEureka: false
        fetchRegistry: false
    ---
    spring.profiles: aws-standalone

    cloud:
      aws:
        credentials:
          instanceProfile: false
        region:
          auto: true
        stack:
          auto: false

    eureka:
      environment: stage
      datacenter: us-east-1
      instance:
        hostname: ec2-xx-xx-xx-xx.compute-1.amazonaws.com
        prefer-ip-address: false
      client:
        registerWithEureka: false
        fetchRegistry: false

There is an EIP configured and the AMI instance is accessible through the EIP.

My AWS Key and Secret are correctly configured as environment properties on the AMI - I can see the logs accessing the AWS URIs for the metadata (some are just 404-ing):

    c.amazonaws.internal.EC2MetadataClient   : Connecting to EC2 instance metadata service at URL: http://169.254.169.254/latest/user-data/
    com.amazonaws.util.EC2MetadataUtils      : Unable to retrieve the requested metadata.

The EC2 instance has a role with AmazonEC2ReadOnlyAccess (as well as AmazonEC2ContainerServiceForEC2Role from other testing) and the credentials configured (AWS_ACCESS_KEY_ID & AWS_SERET_ACCESS_KEY) on the AMI has the following policy:

    {
        "Statement": [
            {
                "Sid": "Stmt1358974336152",
                "Action": [
                    "ec2:*"
                ],
                "Effect": "Allow",
                "Resource": "*"
            },
            {
                "Sid": "Stmt1358974395291",
                "Action": [
                    "autoscaling:DescribeAutoScalingGroups"
                ],
                "Effect": "Allow",
                "Resource": "*"
            }
        ]
    }

No matter how I configure the application, there is a Replica at localhost:8761 being registered (listed as registered and unavailable), and the AMI properties on the dashboard are not showing (I can only see a blank Environment and the Datacenter set to the value in the config - us-east-1)

I've tried overriding properties at the command line (setting hostname to the EIP hostname):

    java -Deureka.instance.host-name=ec2-xx-xx-xx-xx.compute-1.amazonaws.com -jar discovery_server.jar

or

    java -Deureka.instance.hostname=ec2-xx-xx-xx-xx.compute-1.amazonaws.com -jar discovery_server.jar

But nothing seems to set the hostname of the instance and it keeps registering itself as a replica.

I tried adding in an ApplicationInfoBean as per http://cloud.spring.io/spring-cloud-aws/spring-cloud-aws.html#_using_amazon_web_services but that still doesn't seem to change anything.

Accessing the <hostname>/env shows what looks to be the right values, however the springCloudClientHostInfo doesn't look right:

    springCloudClientHostInfo: {
        spring.cloud.client.hostname: "ip-172-31-60-110.ec2.internal",
        spring.cloud.client.ipAddress: "172.31.60.110"
    }

Has something changed in the Brixton.M4 build that may not be documented yet? I've tried the BUILD-SNAPSHOT also but to no success.

![image](https://cloud.githubusercontent.com/assets/1300193/13187835/adfaa87a-d702-11e5-82f7-4e06945b15db.png)

![image](https://cloud.githubusercontent.com/assets/1300193/13187845/b880fe2a-d702-11e5-9e81-fd84c626c08e.png)

I'm going to start from scratch again using Angel.SR6 and see if that works. Otherwise if there is something that I've missed could someone point it out?

Anthony

**Comment by dsyer** [comment]
I think it's all working fine from what I can tell (the replica is "unavailable"). It's slightly irritating that a standalone instance feels to need to clutter up it's UI with that stuff, but it doesn't mean the server isn't working. Or do you have some other data?

**Comment by anthonyikeda** [comment]
Well I've somewhat cleaned up my deployment a bit with the following:

- Removed spring-cloud-aws
  - This just seems to be not compatible right now and I keep getting an IllegalAccessError with the aws-sdk. Could be an amazon thing, but for now I'm just doing away with it
- Trimmed down my bootstrap.yml and application.yml to bare minimum
  - I originally was just working with bootstrap.yml but splitting the config across to application.yml seems to have had some effect:

```
    server:
      port: 9761
    eureka:
      environment: development
      instance:
        hostname: localhost
      client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
          defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      server:
        waitTimeInMsWhenSyncEmpty: 0
        enableSelfPreservation: false
    ---
    spring.profiles: aws-standalone

    eureka:
      instance:
        hostname: ec2-XX-XX-XX-XX.compute-1.amazonaws.com
        nonSecurePort: 80
      us-east-1:
        availabilityZones: us-east-1c
      serviceUrl:
        us-east-1c: http://ec2-XX-XX-XX-XX.compute-1.amazonaws.com/eureka/

```
- I also put NGINX in front the discovery server
  - though I doubt this is affecting anything but explains why I have the nonSecurePort set to 80
- My IDE (IntelliJ) is registering **eureka.us-east-2.availabilityZones** and **eureka.serviceUrl.us-east-1c** as unknown variables but it seems there is no way to validate whether they are working or no
- It seems the Replica list is no longer populating (which is good)
- I can't see any AWS Instance details

![image](https://cloud.githubusercontent.com/assets/1300193/13229210/9c0da60e-d954-11e5-8e88-dccf4c542796.png)

I'm going to raise another ticket for the IllegalAccessError and spring-cloud-aws.

Anthony
