### ISSUE TITLE
Sidecar applications don't register with the default Eureka instance id, as happens with normal microservices

### ISSUE THREAD

**Issue by codependent** [spring-cloud/spring-cloud-netflix#847]
With "normal" microservices a config like this:
```
---
spring:
  application:
    name: random-number-ms
  profiles: random1
server:
  port: 9999
---
spring:
  application:
    name: random-number-ms
  profiles: random2
server:
  port: 9998
```

Gets you two services registered in which the Eureka Id is the host+name+port. So in the Eureka console I see:

`RANDOM-NUMBER-MS	n/a (2)	(2)	UP (2) - myhost:random-number-ms:9999 , myhost:random-number-ms:9998`

Now I want to achieve the same with a sidecar app that calls two instances of node.js services:
```
spring:
  application:
    name: random-letter-ms
  profiles: random1
        
server:
  port: 9595

sidecar:
  port: 3000
  health-uri: http://localhost:${sidecar.port}/health.json

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true

spring:
  application:
    name: random-letter-ms
  profiles: random2
        
server:
  port: 9696

sidecar:
  port: 3001
  health-uri: http://localhost:${sidecar.port}/health.json

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
```

Oddly enough in this case, although I start two sidecar instances only one shows up in Eureka console. I don't understand why with sidecars the id isn't made up of host+name+port as happened with normal microservices...

`RANDOM-LETTER-MS	n/a (1)	(1)	UP (1) - myhost`

There is a sample project with instructions in [GitHub](https://github.com/codependent/spring-cloud-sidecar-test)

**Comment by spencergibb** [comment]
You didn't set the instanceId like I said to do in #744

**Comment by codependent** [comment]
@spencergibb Sorry for reopening... I'll check it out tomorrow and close the issue if everything's ok.

**Comment by codependent** [comment]
@spencergibb As you said, setting manually the eureka instanceId for each sidecar solved the problem.
```
...
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}
...
---
...
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}
...
```
According to the documentation: 
>Spring Cloud Eureka provides a sensible default that looks like this: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}}.

Shouldn't it be applied in sidecar apps by default as happens with normal microservices?
