### ISSUE TITLE
Unable to register application in two Eureka servers

### ISSUE THREAD

**Issue by bogdatov** [spring-cloud/spring-cloud-netflix#848]
I'm using Angel.SR6 and trying to register application to two Eureka Servers.I only see my app registered in 1st Eureka, not 2nd Eureka. I specified both Eureka servers in 
eureka.client.serviceUrl.defaultZone

How do I make my app register in both servers ?

This is my bootstrap.yml profile:
```
---
spring:
 profiles: development-cloud
server:
  tomcat:
    remote_ip_header: x-forwarded-for
    protocol_header: x-forwarded-proto
ribbon.IsSecure: true     
eureka.instance.hostname: ${vcap.application.uris[0]}
eureka.instance.securePortEnabled: true
eureka.instance.nonSecurePortEnabled: false
eureka.instance.statusPageUrl: https://${eureka.instance.hostname}/swagger-ui.html
eureka.instance.homePageUrl: https://${eureka.instance.hostname}/
eureka.instance.healthCheckUrl: https://${eureka.instance.hostname}/health
eureka.instance.secureVipAddress: ${spring.application.name}
eureka.instance.secureVirtualHostName: ${spring.application.name}
eureka:
 client:
  serviceUrl:
   defaultZone: https://${SERVICE_DISCOVERY_HOST:service-discovery-locator-dev.cfappstpanpz1.ebiz.verizon.com}:${SERVICE_DISCOVERY_PORT:443}/eureka/,https://${PEER_SERVICE_DISCOVERY_HOST:service-discovery-locator-dev.cfappstpanpz2.ebiz.verizon.com}:${PEER_SERVICE_DISCOVERY_PORT:443}/eureka/
 instance:
  metadataMap:
    instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}:${random.value}}}
```
