### ISSUE TITLE
Zuul  "No message available" in the Services

### ISSUE THREAD

**Issue by tiarebalbi** [spring-cloud/spring-cloud-netflix#890]
I'm trying just send a request to the services mapped into the Zuul Gateway, but the problem is that i'm getting 404 when i try to request.

The setup is simple:

```
zuul:
  ignoredServices: '*'
  add-proxy-headers: true
  prefix: /v1
  routes:
    receptor-dados:
      path: /receptor/**
      sensitiveHeaders: Set-Cookie
    gerenciador-dados:
      path: /dados/**
      sensitiveHeaders: Set-Cookie
    auth-server:
      path: /auth/**
      sensitiveHeaders: Set-Cookie
```

I'm trying to request the address: /v1/dados/ponto  (ponto is the name of the repository mapped in the 'gerenciador-dados'). If i try request '/ponto' directly I don't have problem. The problem only happen when i try to request through  the gateway.

**Response:**

```
{"timestamp":1457526628204,"status":405,"error":"Method Not Allowed","exception":"org.springframework.web.HttpRequestMethodNotSupportedException","message":"Request method 'POST' not supported","path":"/preferences"}
```

**Header:**

```
Accept:application/json, text/plain, */*
Accept-Encoding:gzip, deflate
Accept-Language:pt,en-US;q=0.8,en;q=0.6
Authorization:Bearer 9df6d319-ce46-4983-9ac7-5a109dbb3b9d
Cache-Control:no-cache
Connection:keep-alive
Content-Length:53
Content-Type:application/json;charset=UTF-8
DNT:1
Host: DOMAIN
Origin:DOMAIN
Pragma:no-cache
Referer:DOMAIN
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36
```
