### ISSUE TITLE
Complex ignoredPatterns with embedded wildcards do not work with Zuul

### ISSUE THREAD

**Issue by orias407** [spring-cloud/spring-cloud-netflix#910]
I'm trying to use "ignoredPatterns" to omit url patterns in my API. Unfortunately "ignoredPatterns" does not work in my configs. Following is the config that I'm using.

```
zuul:
  ignoredServices: "*"
  ignoredPatterns: /mapper/**/mapper
  routes:
    experience:
      path: /experience/**
    mapperservicev1:
      path: /v1/mapper/**
      stripPrefix: false
      serviceId: mapperservice
    mapperservicev2:
      path: /v2/mapper/**
      stripPrefix: false
      serviceId: mapperservice
    mapperservicehelath:
      path: /mapper/**
      stripPrefix: true
      serviceId: mapperservice
```

This will allow calls to both "/v1/mapper/" and "**mapper**/v1/**mapper**/" possible. We want to remove the 2nd option and only allow calls to routses such as "/v2/mapper/abc" and "/v1/mapper/abc" without having mapper twice in the route. Need to use "mapper/health" too.

We used "ignoredPatterns: /mapper/**/mapper", but it allows route to have "mapper" twice.

Please advice.

**Note**: I have also added same comment in https://github.com/spring-cloud/spring-cloud-netflix/issues/445

**Comment by orias407** [comment]
@dsyer. Will you be able to help us in this issue?

**Comment by dsyer** [comment]
I don't think I understand the question. Can you give a more detailed description of which paths get handled where?

**Comment by tharakawilfred** [comment]
hi @dsyer ,
Below is the config we use in our Zuul service.

```
zuul:
  ignoredServices: "*"
  ignoredPatterns: /mapper/**/mapper
  routes:
    experience:
      path: /experience/**
    mapperservicev1:
      path: /v1/mapper/**
      stripPrefix: false
      serviceId: mapperservice
    mapperservicev2:
      path: /v2/mapper/**
      stripPrefix: false
      serviceId: mapperservice
    mapperservicehelath:
      path: /mapper/**
      stripPrefix: true
      serviceId: mapperservice

```
In the micro service registered as "mapperservice" (serviceId: mapperservice) it has the below routes mapped in the controllers.
`"/v1/mapper/**" , "/v2/mapper/**", "/health".`
With the current Zuul configuration routes `"/v1/mapper/**" , "/v2/mapper/**"` is accessible as expected.
Additionally we want to restrict accessing routes like `"mapper/v1/mapper/**"` possibly using the "ignoredPatterns".
We cant get the restriction applied in Zuul to restrict the routes like `"mapper/v1/mapper/**"` and `"mapper/v2/mapper/**" `Please advice how this can be achieved.
Thanks.
