### ISSUE TITLE
Zuul url routing with multiple urls auto-configure ribbon

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-netflix#921]
It would be cool to have a config like this:

```
 zuul:
  routes:
    first:
      path: /first/**
      url: http://first1.example.com, http://first2.example.com
```

and have zuul autoconfigure ribbon to use a list of servers so url routing can take advantage of hystrix and ribbon without having to disable ribbon's eureka support or using java ribbon config for each serviceId.

/cc @dussab
