### ISSUE TITLE
Zuul sensitiveHeaders not working as documented

### ISSUE THREAD

**Issue by ukjbrown** [spring-cloud/spring-cloud-netflix#934]
Using spring-cloud-starter Brixton.RC1

```
zuul:
  routes:
    authentication:
      path: /authentication/**
      strip-prefix: false
      service-id: authentication
      sensitive-headers: Authorization
```

The Route ends up with the default Cookie, Set-Cookie (etc) values set for sensitveHeaders. Thus breaking the application login.
